### ISSUE TITLE
Blackfire / ZTS

### ISSUE THREAD

**Issue by temp** [mlocati/docker-php-extension-installer#1003]
### Version of install-php-extensions

v.2.6.1

### Error description

When installing blackfire extension for example in a php:8.3-zts-alpine container, it will result in this error:
```
91.43 PHP Warning:  PHP Startup: Unable to load dynamic library 'blackfire.so' (tried: /usr/local/lib/php/extensions/no-debug-zts-20230831/blackfire.so (Error relocating /usr/local/lib/php/extensions/no-debug-zts-20230831/blackfire.so: file_globals: symbol not found), /usr/local/lib/php/extensions/no-debug-zts-20230831/blackfire.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-zts-20230831/blackfire.so.so: No such file or directory)) in Unknown on line 0
```

I guess there should be a check for PHP_THREADSAFE and then download another variant of the blackfire.so (just checked it, I guess it should be (for php 8.3) .../83-zts instead of .../83 ([line](https://github.com/mlocati/docker-php-extension-installer/blob/091f76086fbf7ed8425b1b3abe5c099873465d1a/install-php-extensions#L2990C35-L2990C161))

### Docker image

php:8.3-zts-alpine

### Minimal Dockerfile

```Dockerfile
FROM php:8.3-zts-alpine
RUN curl -LsSf \
            -o /usr/local/bin/install-php-extensions \
            https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    && chmod +x /usr/local/bin/install-php-extensions \
    && install-php-extensions blackfire
```

**Comment by mlocati** [comment]
Thanks for the report!
Could you check if version 2.6.3 fixes the issue for you?

**Comment by temp** [comment]
@mlocati Works like a charm, thanks!
