### ISSUE TITLE
install swoole 6-beta for php 8.4

### ISSUE THREAD

**Issue by ariaieboy** [mlocati/docker-php-extension-installer#1008]
Hi, I want to know if installing swoole 6-beta on the PHP 8.4 docker image is possible.
swoole 6 adds support for PHP 8.4

**Comment by mlocati** [comment]
See https://github.com/swoole/swoole-src/issues/5531

**Comment by ariaieboy** [comment]
@mlocati Yes I know about that issue. installing 6-alpha is also enough for testing. 

I tried to install the swoole 6 on php.4 using this code:
```
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions swoole-^6
```
and I get this error:

```
86.36 configure: error: Package requirements (liburing) were not met:
86.36
86.36 Package 'liburing' not found
```

**Comment by mlocati** [comment]
The alpha version is really too old on PECL (2024-06-24) - see https://pecl.php.net/package/swoole

They should upload a new release on PECL

**Comment by NathanFreeman** [comment]
I have re-uploaded the Swoole installation package to PECL. You can try installing it using the command `pecl install swoole-6.0.0RC1`. @ariaieboy

**Comment by ariaieboy** [comment]
@mlocati `liburing-dev` must be installed so we can install swoole 6

**Comment by mlocati** [comment]
It seems that swoole requires at least version 2.5 of liburing , but debian bookworm provides version 2.3.

I have to check if liburing is really mandatory or if it's an optional stuff.

**Comment by ariaieboy** [comment]
@mlocati can you re-open this issue so I can track when it gets fixed?

**Comment by mlocati** [comment]
> can you re-open this issue so I can track when it gets fixed?

It got fixed 😉
