### ISSUE TITLE
Install xdebug 3@beta for php 8.4

### ISSUE THREAD

**Issue by tarlepp** [mlocati/docker-php-extension-installer#1014]
PHP 8.4 is out and there isn't official support with xdebug for PHP 8.4 but latest 3 beta supports that.

**Comment by mlocati** [comment]
Since xdebug doesn't officially support PHP 8.4, I don't think my script should either...

**Comment by reypm-provest** [comment]
@mlocati why not? even [PIE](https://github.com/php/pie) supports it. Would be great if we could have it, right now this is a "blocker" since is stopping me from migrate to PHP 8.4 :(

**Comment by reypm-provest** [comment]
you are correct I did not notice you could install beta as well, is working for me, I guess you say is not supported in the README table because xdebug for PHP8.4.x isn't in stable yet

**Comment by mlocati** [comment]
>  I guess you say is not supported in the README table because xdebug for PHP8.4.x isn't in stable yet

Yep, correct
