### ISSUE TITLE
[Question] Release docker image to GHCR

### ISSUE THREAD

**Issue by ToshY** [mlocati/docker-php-extension-installer#1015]
Hello 👋 

Is it possible to release the docker image to the GitHub Container Registry (GHCR) as well? Reason for asking: [Docker Hub rate limits](https://docs.docker.com/docker-hub/download-rate-limit/#whats-the-download-rate-limit-on-docker-hub)

Thanks in advance.

**Comment by mlocati** [comment]
Sure it's possible, provided one can tell me how to integrate it in [this step](https://github.com/mlocati/docker-php-extension-installer/blob/2.7.2/.github/workflows/readme-release.yml#L190-L210).

**Comment by ToshY** [comment]
> Sure it's possible, provided one can tell me how to integrate it in [this step](https://github.com/mlocati/docker-php-extension-installer/blob/2.7.2/.github/workflows/readme-release.yml#L190-L210).

With the current `docker/build-push-action` and without changing much of your current implementation, I think the easiest way would be like this example: https://docs.docker.com/build/ci/github-actions/push-multi-registries/

In short, an additional login with `docker/login-action@v3` and add `ghcr.io/mlocati/php-extension-installer` to the tags of the `docker/build-push-action`.

I can create the PR if you'd like.

**Comment by mlocati** [comment]
Done, thanks for the link!

**Comment by mlocati** [comment]
Now the most important question (I'm kidding, of course😉): do you know if a badge like this is available for pulls from the GitHub Container Registry?

[![Docker Hub pulls](https://img.shields.io/docker/pulls/mlocati/php-extension-installer)](https://hub.docker.com/r/mlocati/php-extension-installer)

**Comment by ToshY** [comment]
> Now the most important question (I'm kidding, of course😉): do you know if a badge like this is available for pulls from the GitHub Container Registry?
> 
> [![Docker Hub pulls](https://camo.githubusercontent.com/5a668a71734b9e26bf5c0973835f5f7f824cb390d4ec94b03940a720bfb1d16a/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f6d6c6f636174692f7068702d657874656e73696f6e2d696e7374616c6c6572)](https://hub.docker.com/r/mlocati/php-extension-installer)

Sadly doesn't seem an "easy" one that you can use like that one (also see https://github.com/badges/shields/issues/5594). Haven't test it myself, but there's one that includes "downloads", so you might be able to try to use https://github.com/ipitio/backage.

<a href="https://github.com/mlocati/docker-php-extension-installer/pkgs/container/php-extension-installer"><img src="https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fipitio.github.io%2Fbackage%2Fmlocati%2Fphp-extension-installer%2Fphp-extension-installer.json&query=%24.downloads&label=GHCR%20pulls" /></a>

For other (non-downloads) badges, maybe this: https://github.com/eggplants/ghcr-badge

[![Tags](https://ghcr-badge.egpl.dev/mlocati/php-extension-installer/tags?color=%2344cc11&ignore=latest&n=3&label=image+tags&trim=)](https://github.com/mlocati/docker-php-extension-installer/pkgs/container/php-extension-installer)

[![Latest](https://ghcr-badge.egpl.dev/mlocati/php-extension-installer/latest_tag?color=%2344cc11&ignore=latest&label=version&trim=)](https://github.com/mlocati/docker-php-extension-installer/pkgs/container/php-extension-installer)

[![Size](https://ghcr-badge.egpl.dev/mlocati/php-extension-installer/size?color=%2344cc11&tag=latest&label=image+size&trim=)](https://github.com/mlocati/docker-php-extension-installer/pkgs/container/php-extension-installer)

---

Thanks for adding it to GHCR 👍

**Comment by mlocati** [comment]
I ended up creating https://github.com/mlocati/docker-php-extension-installer/blob/master/.github/workflows/update-ghcr-badge.yml

**Comment by ToshY** [comment]
> I ended up creating https://github.com/mlocati/docker-php-extension-installer/blob/master/.github/workflows/update-ghcr-badge.yml

Hmm... If I understand correctly this will update your README with a new badge every day. While I find the approach interesting, will this not clutter your git history with `Update GitHub Registry badge` commits?

**Comment by mlocati** [comment]
That action doesn't update the readme, just this branch: https://github.com/mlocati/docker-php-extension-installer/tree/assets

**Comment by ToshY** [comment]
Oh I misunderstood then, thanks for clarifying. 👍
