### ISSUE TITLE
checking if that is sane... (swoole)

### ISSUE THREAD

**Issue by francoism90** [mlocati/docker-php-extension-installer#1031]
### Version of install-php-extensions

`v.2.7.1`

### Error description

```
checking Oracle Install-Dir... yes
checking if that is sane... configure: error: You need to tell me where to find your Oracle Instant Client SDK, or set ORACLE_HOME.
ERROR: `/tmp/pear/temp/swoole/configure --with-php-config=/usr/local/bin/php-config --enable-sockets=yes --enable-openssl=yes --enable-mysqlnd=yes --enable-swoole-curl=no --enable-cares=yes --enable-brotli=yes --enable-zstd=yes --enable-swoole-pgsql=no --with-swoole-odbc=no --with-swoole-oracle --enable-swoole-sqlite=yes --enable-swoole-thread=yes --enable-iouring=no' failed
Error: building at STEP "RUN install-php-extensions     @composer     apcu     bcmath     bz2     event     exif     ffi     gd     igbinary     intl     mbstring     msgpack     opcache     pcntl     pcov     pdo_mysql     pdo_pgsql     pgsql     redis     sockets     swoole     uv     zip": while running runtime: exit status 1
```

### Docker image

dunglas/frankenphp:php8.3-alpine

### Minimal Dockerfile

https://github.com/dunglas/frankenphp/blob/2676bffa988ccafc38e9bf9396a703e94e82cca3/Dockerfile#L26

I'm using the Frankenphp Dockerfile.

**Comment by francoism90** [comment]
@mlocati Sorry about that!

`install-php-extensions v.2.7.1`

**Comment by mlocati** [comment]
> install-php-extensions v.2.7.1

Try with the latest version

**Comment by mlocati** [comment]
> :+1:

@francoism90 does that thumbs up mean you are not experiencing the issue with the latest version?

**Comment by francoism90** [comment]
@mlocati No, sorry about that. :)

**Comment by mlocati** [comment]
> @mlocati No, sorry about that. :)

So, are you still having the issue with the very latest version (2.7.7)? I thought that this issue was already fixed by #1030...

**Comment by francoism90** [comment]
@mlocati I'm using the version of the image (`v.2.7.1`), not the latest one.

I haven't tested with the latest version, the frankenphp-alpine doesn't seem to use the latest. If this is recommended, I could make a PR to them. :)

**Comment by mlocati** [comment]
> the frankenphp-alpine doesn't seem to use the latest

They use the latest version of `install-php-extensions` ([see here](https://github.com/dunglas/frankenphp/blob/v1.3.3/Dockerfile#L29)).
But if you are using a docker image built 3 weeks ago, you'll have the latest version as of 3 weeks ago.
Your only option is to reinstall `install-php-extensions` ([see the readme](https://github.com/mlocati/docker-php-extension-installer/?tab=readme-ov-file#usage)).

**Comment by francoism90** [comment]
@mlocati Thanks for the details and help!

**Comment by francoism90** [comment]
@mlocati Just to confirm: using the latest version works fine and fixes the swoole build error.

Sorry for the noise. :)

**Comment by mlocati** [comment]
Thanks for confirming!
