### ISSUE TITLE
Geoip for php 8

### ISSUE THREAD

**Issue by jeff1326** [mlocati/docker-php-extension-installer#1034]
Could you use this repos instead for Geoip ?

https://github.com/rlerdorf/geoip

This is what we used for few years now.

P.S. Geoip2 would make sense too : https://github.com/maxmind/GeoIP2-php

**Comment by mlocati** [comment]
Is that extension published on pecl?

**Comment by mlocati** [comment]
> P.S. Geoip2 would make sense too : https://github.com/maxmind/GeoIP2-php

Is this a PHP module (aka extension)? Or it's a PHP project?

**Comment by jeff1326** [comment]
> Is that extension published on pecl?


No, unfortunately i can't find it on pecl.

Here's what we did on our side
```
RUN apk add --no-cache --update -t virt-deps $PHPIZE_DEPS geoip-dev mpdecimal-dev \
    && apk add --no-cache --update geoip \
    && cd /opt \
    && wget https://github.com/rlerdorf/geoip/archive/refs/tags/1.3.1.tar.gz \
    && tar xvf 1.3.1.tar.gz \
    && cd geoip-1.3.1/ \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && docker-php-ext-enable geoip \
    && cd ../ && rm -fr geoip-1.3.1 1.3.1.tar.gz \
    && apk del virt-deps
    
RUN mkdir -p /usr/share/GeoIP \
    && curl http://***.***.***.***/geoip/GeoIPCity.dat -o /usr/share/GeoIP/GeoIPCity.dat
```
Star in the curl address is a local server in our infrastructure for caching.





> > P.S. Geoip2 would make sense too : https://github.com/maxmind/GeoIP2-php
> 
> Is this a PHP module (aka extension)? Or it's a PHP project?
For Geoip2, an information about it would be interesting in the Supported PHP extensions list.

It's available by 2 way

- Pure php project available in phar here : https://github.com/maxmind/GeoIP2-php/releases
- By packagist here : https://packagist.org/packages/geoip2/geoip2

Here's a example how to use it : https://www.php.net/manual/en/book.geoip.php#123492

**Comment by mlocati** [comment]
About https://github.com/rlerdorf/geoip: keeping support for PHP modules that are not published on pecl requires a lot of manual support and special handling of updates. What about asking them to publish it on PECL?

About https://github.com/maxmind/GeoIP2-php: as you wrote, it's a PHP project, not a PHP extension written in C, so you can install it with composer and not with `install-php-extensions`.

**Comment by jeff1326** [comment]
For https://github.com/rlerdorf/geoip : An issue has been opened about that but there's nothing since 2021 https://github.com/rlerdorf/geoip/issues/1

For https://github.com/maxmind/GeoIP2-php : I think a mention should be put in your documentation to use that instead for Php 8 for new user who may need this functionality
