### ISSUE TITLE
Couldn't find pcre.h

### ISSUE THREAD

**Issue by dejan9393** [mlocati/docker-php-extension-installer#115]
I get the following error when trying to install the oauth extension on `php:7.4-fpm-alpine`:

```
### INSTALLING PECL MODULE oauth ###
downloading oauth-2.0.5.tgz ...
Starting to download oauth-2.0.5.tgz (49,641 bytes)
... (omitted for brevity)
configure: error: Couldn't find pcre.h, try installing the libpcre development/headers package
```

Workaround: add `pcre-dev` package

**Comment by mlocati** [comment]
The oauth extension is not supported yet (see https://github.com/mlocati/docker-php-extension-installer/blob/master/README.md#supported-php-extensions )

**Comment by mlocati** [comment]
I added support for the oauth extension (see #119)
