### ISSUE TITLE
Error configuring GD: unrecognized options

### ISSUE THREAD

**Issue by rizkysyazuli** [mlocati/docker-php-extension-installer#122]
Got stuck at this command when doing `docker build`:

    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

This is the error i got:

    configure: error: unrecognized options: --with-freetype-dir, --with-jpeg-dir

I'm using the `php:7.4.3-fpm-buster` image.

**Comment by mlocati** [comment]
Could you share your dockerfile (at least the part from the beginning up to the call to `install-php-extensions`)?

**Comment by rizkysyazuli** [comment]
Ah yes.. Sorry.

```dockerfile
FROM php:7.4.3-fpm-buster

RUN apt-get update -y && apt-get install -y nano openssl unixodbc zip unzip git wget libfreetype6-dev libjpeg62-turbo-dev libpng-dev libldb-dev libldap2-dev unixodbc-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
```

Turns out this issue has been posted in the [PHP docker repo issue #912](https://github.com/docker-library/php/issues/912#issuecomment-559918036). It's caused by [a change](https://github.com/docker-library/php/pull/910#issuecomment-559383597) in PHP version 7.4

**Comment by mlocati** [comment]
This repository is for the `install-php-extensions` command, not for the `docker-php-ext-...` commands...

**Comment by rizkysyazuli** [comment]
sorry. my bad. thx for the response though.

**Comment by mlocati** [comment]
The best advice I can give you is to get rid of `apt-get update`/`apt-get install`/`docker-php-ext-configure` calls and simply use a script like this:

```Dockerfile
FROM php:7.4.3-fpm-buster

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/

RUN install-php-extensions gd ldap
```

In other words, don't waste your time with all that messy system package requirements, let `install-php-extensions` do the dirty work :wink:

**Comment by rizkysyazuli** [comment]
oh wow. that looks much cleaner. thx!
