### ISSUE TITLE
install specific version

### ISSUE THREAD

**Issue by michabbb** [mlocati/docker-php-extension-installer#130]
hi, is there anything I missed, that gives me the chance to install a specific version of an extension ???

thanks

**Comment by mlocati** [comment]
Nope, it's not (yet) supported

**Comment by michabbb** [comment]
🆗 thanks

**Comment by glen-84** [comment]
Can this be left open as a feature request?

**Comment by piotrkochan** [comment]
How about this year?

**Comment by mlocati** [comment]
I'm planning to implement this, as soon as I have some spare time

**Comment by nesk** [comment]
If it can help, I install a specific version of `rdkafka` by monkey-patching the script:

```
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN sed -i -e $'s/rdkafka)/rdkafka)\\\n\\\t\\\t\\\tinstallPECLModule_actual="rdkafka-3.1.3"\\\n\\\t\\\t\\\t;;\\\n\\\t\\\trdkafka-latest)/' /usr/bin/install-php-extensions
RUN install-php-extensions rdkafka
```

It does the following replacements:

```diff
		raphf)
			if test $PHP_MAJMIN_VERSION -lt 700; then
				installPECLModule_actual="$1-1.1.2"
			fi
			;;
		rdkafka)
+			installPECLModule_actual="rdkafka-3.1.3"
+			;;
+		rdkafka-latest)
			if test $PHP_MAJMIN_VERSION -le 505; then
				installPECLModule_actual="$1-3.0.5"
			else
				installPECLModule_tmp=
				case "$DISTRO" in
```

It's crappy, but it works until the version feature is available.

**Comment by cytodev** [comment]
@mlocati This could possibly be resolved by changing [this line](https://github.com/mlocati/docker-php-extension-installer/blob/4157d994c964e6bece1a5413998091d0ce28a6a8/install-php-extensions#L1085) to split on hypens. Versions are usually notated behind the package name, separated by a hyphen. That way you can supply the installer versions to install (which pecl accepts) and strip them to enable them with `docker-php-ext-enable`.

**Comment by mrsrvman** [comment]
https://github.com/symfony/symfony/issues/39195

**Comment by evs-xsarus** [comment]
For XDEBUG, I've solved this temporary with:

```
# Explicitly install Xdebug 2.x as 3.x is now installed by mlocati's script. That version breaks Magento.
# Als install it after mlocati's script, that script will install all required packages for pecl and make.
RUN pecl install xdebug-2.9.8; \
    docker-php-ext-enable xdebug;
```

**Comment by mrsrvman** [comment]
+1
```
RUN    sed -i -e 's/xdebug)/xdebug)\n\t\t\tinstallPECLModule_actual="$1-2.9.8"\n\t\t\t;;\n\t\txdebug-latest)/' /usr/local/bin/install-php-extensions \
    && install-php-extensions xdebug \
```
