### ISSUE TITLE
Running install-php-extensions more than once

### ISSUE THREAD

**Issue by glen-84** [mlocati/docker-php-extension-installer#131]
I am doing something like this:

```dockerfile
FROM php:7.0.12-fpm

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/

ARG WITH_XDEBUG

RUN install-php-extensions \
    gd \
    opcache \
    pdo_mysql \
    redis \
    ${WITH_XDEBUG:+xdebug}
```

... and building two images, one with and one without Xdebug. I just realized that this is probably not optimal ITO layer caching, as the work of installing 4 of the 5 extensions is repeated.

Would it make sense to run `install-php-extensions` a second time? Is this normal/safe, and would any expensive work be repeated this way?

It would look like this:

```dockerfile
FROM php:7.0.12-fpm

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/

RUN install-php-extensions \
    gd \
    opcache \
    pdo_mysql \
    redis

ARG WITH_XDEBUG=false

RUN if [ $WITH_XDEBUG = "true" ]; then install-php-extensions xdebug; fi
```

**Comment by mlocati** [comment]
It should work flawlessly. The only downside is a longer build time.

**Comment by glen-84** [comment]
> The only downside is a longer build time.

Could you please elaborate on this a little bit?

**Comment by mlocati** [comment]
`install-php-extensions` does a lot of things under the hood: it calls `apt-get update`, it extracts the PHP source code, it downloads APT packages required for installing PHP extensions. Adter that, to free space, it removes the APT packages required only for installing extensions,. deletes the PHP source code, and resets the APT cache.
So, running `install-php-extensions` twice, those operations will be executed twice.

**Comment by glen-84** [comment]
Thanks, this is what I was referring to when I said "would any expensive work be repeated this way?".

Thinking about this more, it would actually not run a second time, because:

* For the first image, `WITH_XDEBUG` would be `false`, so it wouldn't run `install-php-extensions` for XDebug.
* For the second image, the layer with the first 4 extensions would be cached, and `install-php-extensions` would only be run for Xdebug.

So, a total of 2 runs over the 2 images, with the difference being that instead of building 4-5 extensions twice, it would build 4 extensions once, and 1 extension once (9 vs 5).

Unless I'm missing something, this should be a good option.

Thanks again.
