### ISSUE TITLE
Support custom temp directory

### ISSUE THREAD

**Issue by SamMousa** [mlocati/docker-php-extension-installer#145]
On latest alpine docker images `/tmp` is mounted as `noexec`.
This causes some extensions (in my case `xlswriter` from pecl) to fail to install.
The path `/tmp` is hardcoded in the script making it hard to work around this. 

Current workaround I use is:
```bash
# mkdir /tmp2 
# ln -s /tmp2 /tmp/pear
```
This is obviously an ugly solution and could be solved much better in this script.

Ideally it would also check whatever temp directory it is using is not mounted with `noexec` and provide a more informative error message.

**Comment by mlocati** [comment]
What's the output of `mktemp -d`?

**Comment by SamMousa** [comment]
Test script:
```bash
docker pull alpine:edge
docker run --rm -it alpine:edge
export TMPFILE=$(mktemp -d)
echo $TMPFILE
chmod +x $TMPFILE
$TMPFILE
```
Output:
```
$ docker run --rm -it alpine:edge
export TMPFILE=$(mktemp -d)
echo $TMPFILE
chmod +x $TMPFILE
$TMPFILE/ # export TMPFILE=$(mktemp -d)
/ # echo $TMPFILE
/tmp/tmp.cIDaif
/ # chmod +x $TMPFILE
/ # $TMPFILE
/bin/sh: /tmp/tmp.cIDaif: Permission denied
```

**Comment by mlocati** [comment]
Well, `mktemp -d` [creates a directory](https://www.gnu.org/software/autogen/mktemp.html), not a file, that's why you can't execute it.

Here's a session of mine:
```
PS C:\> docker pull alpine:edge
edge: Pulling from library/alpine
Digest: sha256:c22dc21793cd8d713df961ea1617b09de924f3dd5291970705037ff190f228a7
Status: Image is up to date for alpine:edge
docker.io/library/alpine:edge

PS C:\> docker run --rm -it alpine:edge sh
/ # printf '#!/bin/sh\necho Hi\n' > /tmp/test
/ # chmod +x /tmp/test
/ # /tmp/test
Hi
```

So, it seems that you can actually mark a file as executable, and execute it, even if it's in the `/tmp` directory (and ps: `mount | grep /tmp` returns nothing for me in `alpine:edge`)

**Comment by SamMousa** [comment]
Let me do another check soon, the issue was that tmp is noexec. Might have made a mistake in my reproduction code... Since I expected the error and didn't look closer

**Comment by mlocati** [comment]
@SamMousa any update?

**Comment by SamMousa** [comment]
No,  but thanks for the reminder,  will check today
