### ISSUE TITLE
Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease

### ISSUE THREAD

**Issue by alexpidhornyi** [mlocati/docker-php-extension-installer#16]
Hi! I'm using your code snippet to install pspell onto my docker container (php:7.1-apache-jessie), and I'm getting the following error:

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c chmod uga+x /usr/local/bin/install-php-extensions && install-php-extensions pspell' returned a non-zero code: 100

Maybe this has something to do with this: https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html?

Appreciate your help!

**Comment by mlocati** [comment]
> Maybe this has something to do with this: https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html?

Yes, I think that's the reason.

BTW it's something unrelated to this `docker-php-extension-installer` project...
