### ISSUE TITLE
Support for Maxmind

### ISSUE THREAD

**Issue by NapoSky** [mlocati/docker-php-extension-installer#161]
Hello,

Would it be possible to support Maxmind from https://github.com/maxmind/MaxMind-DB-Reader-php (the Optional C Extension) which need to be manually build to work ?

Actually I'm doing this inside my container and I think it would fit with how the installer works regarding "install-php-extensions" file.

RUN echo "deb http://deb.debian.org/debian/ buster main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update  && \
    apt-get -y --force-yes install libmaxminddb0 libmaxminddb-dev mmdb-bin geoipupdate
ADD 35-maxminddb.ini /etc/php/7.3/fpm/conf.d/35-maxminddb.ini
ADD GeoIP.conf /etc/GeoIP.conf
RUN cd /tmp && git clone https://github.com/maxmind/MaxMind-DB-Reader-php.git && \
    cd /tmp/MaxMind-DB-Reader-php/ext && phpize && ./configure -q && make -s && make -s install && \
    geoipupdate

Thanks for your work!

**Comment by mlocati** [comment]
A couple of months ago they published the package in the PECL archive, and that makes the installation much easier.
I've just added support for maxminddb (minimum PHP version is 7.2)
