### ISSUE TITLE
Missing imagick 

### ISSUE THREAD

**Issue by filipbekic01** [mlocati/docker-php-extension-installer#162]
Library imagick  is missing even if it's in the list.

**Comment by filipbekic01** [comment]
Maybe i misunderstood something but i can't use `docker-php-ext-install`. Instead, I had to use your `install-php-extensions` in order to install Imagick.
 
```
# Imagick
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && sync
RUN install-php-extensions imagick

# The rest
RUN docker-php-ext-install gd zip pdo_pgsql pdo_mysql mysqli exif
```

**Comment by mlocati** [comment]
>  can't use `docker-php-ext-install`. Instead, I had to use your `install-php-extensions` in order to install Imagick

Yep: `install-php-extensions` is the script provided by this project, and it can be used as described it its [README.md](https://github.com/mlocati/docker-php-extension-installer/blob/master/README.md#downloading-the-script-on-the-fly).

Is there something I can do to make it even more clear how to use this script?
