### ISSUE TITLE
pdo_firebird: build libs from firebird 3.x in alpine images

### ISSUE THREAD

**Issue by TwIsL** [mlocati/docker-php-extension-installer#164]
For alpine images pdo_firebird extension builds with libs from version firebird 2.5.9. It is possible to build libs from firebird 3.x?

**Comment by mlocati** [comment]
It doesn't seem possible to compile firebird 3 under Alpine Linux. I think that's because of a bug in the compiler (gcc 9.3.0) - see http://tracker.firebirdsql.org/browse/CORE-6400
