### ISSUE TITLE
Tag releases on master branch

### ISSUE THREAD

**Issue by mcfedr** [mlocati/docker-php-extension-installer#168]
It would be great to be able to use a specific version of the script when building docker images rather than just a general 'latest'. Moving forward this might also be helpful to maintainers in being able to remove support for older php versions and distros

**Comment by mlocati** [comment]
I'm not planning to remove support for old PHP version in the foreseeable future

**Comment by mcfedr** [comment]
sure - that was more an idea - In general - I'd rather `ADD ... some specific version` rather than the latest version, and update the version when i need to.

**Comment by 4n70w4** [comment]
Hi! It would be very convenient to have versioned releases to use the file of the required version. Your releases are now empty = (

![image](https://user-images.githubusercontent.com/38257723/98235292-ae8ad900-1f72-11eb-8574-6507a090ca57.png)

**Comment by mlocati** [comment]
Master is always the best available version ;)

**Comment by mmachatschek** [comment]
@mlocati tagging releases would help people with randomly breaking builds because of updates to the script, also seeing what has changed between the versions is a great benefit for most people.

@4n70w4 I currently add the script in my Dockerbuild with a fixed commit hash if you find this helpful

`ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/74623ad1310124442d360662ef39a7596d0f00a9/install-php-extensions /usr/local/bin/`

**Comment by 4n70w4** [comment]
@mmachatschek unfortunately this is workaround, `74623ad1310124442d360662ef39a7596d0f00a9` is magic constant without semantic.

This hash does not tell which version will be taken. We'll have to open the github to see the details.

**Comment by jvasseur** [comment]
Personally, even with tagged released I would still use a commit hash in my docker build because they are guaranteed to be stable where releases can be re-tagged.

**Comment by 4n70w4** [comment]
@jvasseur only checking the hash sum of the file gives a good guarantee. Everything else can be faked and replaced by an attacker.

**Comment by mlocati** [comment]
Fixed by https://github.com/mlocati/docker-php-extension-installer/commit/f9f060c1a786dfea474f49896ed5cd8c293aefe0

**Comment by mlocati** [comment]
> Fixed by [f9f060c](https://github.com/mlocati/docker-php-extension-installer/commit/f9f060c1a786dfea474f49896ed5cd8c293aefe0)

For example, I pushed https://github.com/mlocati/docker-php-extension-installer/commit/38b97cafff66af631f0a0a85af01c3b6dad09bec and that action ([see its log](https://github.com/mlocati/docker-php-extension-installer/runs/1364898960)) created the `1.0.1` tag and the [`v1.0.1` release](https://github.com/mlocati/docker-php-extension-installer/releases/tag/1.0.1).
