### ISSUE TITLE
Remove "no longer required" packages?

### ISSUE THREAD

**Issue by pavel-mironchik** [mlocati/docker-php-extension-installer#17]
After I used this script like `install-php-extensions --cleanup pdo_pgsql soap intl` I saw a message in a console saying:

```
The following packages were automatically installed and are no longer required:
  icu-devtools libpq5
Use 'apt autoremove' to remove them.
```

How about the `--cleanup` parameter will also run `apt autoremove` command to shrink the final image's size?

**Comment by mlocati** [comment]
I think it's a nice idea! What about submitting a pull request?

**Comment by pavel-mironchik** [comment]
Sure, I will make a PR.
