### ISSUE TITLE
gmp and pdo_dblib not build on arm arch because function getTargetTriplet not use

### ISSUE THREAD

**Issue by Tob1as** [mlocati/docker-php-extension-installer#219]
Hi,

the extension `gmp` and `pdo_dblib` not build on arm arch.

Example error message: `configure: error: Could not find /usr/lib/libsybdb.a|so`

In Line [1070](https://github.com/mlocati/docker-php-extension-installer/blob/7469664e92b3131bf24a816d8eebb96ac9c0c28e/install-php-extensions#L1070) and [1116](https://github.com/mlocati/docker-php-extension-installer/blob/7469664e92b3131bf24a816d8eebb96ac9c0c28e/install-php-extensions#L1116) are not use function `getTargetTriplet` from Line [893](https://github.com/mlocati/docker-php-extension-installer/blob/7469664e92b3131bf24a816d8eebb96ac9c0c28e/install-php-extensions#L893). There is `x86_64-linux-gnu` used.

With `sed -i "s|\/x86_64-linux-gnu\/|\/$\(getTargetTriplet\)\/|g" install-php-extensions` in my Dockerfile on RaspberryPi it build successful.
  
(I switched my dockerfile to php-extension-installer yesterday and I am excited. Makes a lot of things easier. Thanks!)

**Comment by mlocati** [comment]
I'll address this ASAP.
Out of curiosity: could you share your Dockerfile? I'm really curious to see how to setup PHP in an arm environment...

**Comment by Tob1as** [comment]
There is really no difference. :-) 
I use the offical docker images https://hub.docker.com/_/php , see Quick reference->Supported architectures (example: arm32v7). 
He my files (examples) [Dockerfile1-buster-php+apache2](https://github.com/Tob1asDocker/php/blob/master/debian.armhf.8_0_apache.Dockerfile) or [Dockerfile2-alpine-php+nginx](https://github.com/Tob1asDocker/php/blob/master/alpine.armhf.8_0_fpm_nginx.Dockerfile). And before i found you php-extension-installer it look like this [Dockerfile3-buster-php+apache2](https://github.com/Tob1asDocker/php/blob/39120c82eb9ecef160ea80faf2639a478d88ba10/debian.armhf.8_0_fpm.Dockerfile). But unfortunately Docker Hub does not support automatic arm builds, so I have to trick a bit. Not a good solution, but it works (for me :-) ).

**Comment by mlocati** [comment]
Nice! Thanks for sharing the info
