### ISSUE TITLE
Installation of composer broken

### ISSUE THREAD

**Issue by yannoff** [mlocati/docker-php-extension-installer#242]
Installation of composer via the `@composer` meta-package name seems to be broken since today :disappointed:  (worked perfectly yesterday)

Tried on `PHP 7.2 / Debian Buster` : 

```bash
root@6a85b3004018:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```bash
root@6a85b3004018:~# php -v
PHP 7.2.34 (cli) (built: Dec 11 2020 10:56:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

It seems like the installer mistakenly take `@composer` as a `PECL` extension :thinking: 

```bash
root@6a85b3004018:~# install-php-extensions @composer-1.10.19
### INSTALLING PECL MODULE @composer-1.10.19 ###
parsePackageName(): invalid package name "@composer" in "@composer-1.10.19"
invalid package name/package file "@composer-1.10.19"
install failed
root@6a85b3004018:~# 
```

**Comment by mlocati** [comment]
Are you sure you are using the most recent version of `install-php-extensions`?

**Comment by yannoff** [comment]
Damn, you're right, my bad ! :disappointed: 

I used the [COPY FROM](https://github.com/mlocati/docker-php-extension-installer#copying-the-script-from-a-docker-image) way to install the script, but I had an old version of the image cached from previous installs...

Refreshing the image with a `docker pull mlocati/php-extension-installer` solved it all :v: 

Closing this, thus :wink:

**Comment by mlocati** [comment]
Thanks for the quick feedback. I'm thinking about adding a version string to the script, in order to help people detecting such issues.

**Comment by yannoff** [comment]
> Thanks for the quick feedback. I'm thinking about adding a version string to the script, in order to help people detecting such issues.

@mlocati As an afterthought on this...

In the meantime maybe it would be a good idea to add a caveat in the README about that pitfall, ie **copying from**  may result in using an old, out-of-date previously cached image. What do you think ?

**Comment by mlocati** [comment]
That's a good idea! What about submitting a pull request?

**Comment by yannoff** [comment]
Why not :smiley_cat: I will get on it ASAP
