### ISSUE TITLE
Let to configure Imagick

### ISSUE THREAD

**Issue by shandak** [mlocati/docker-php-extension-installer#247]
Following https://imagemagick.org/script/advanced-unix-installation.php#install I need to set `./configure --with-openjp2=yes` to have `jp2` been delegated.
it would be great to have the ability to set additional options when Imagick is configuring there
https://github.com/mlocati/docker-php-extension-installer/blob/master/install-php-extensions#L1459

**Comment by mlocati** [comment]
The `--with-openjp2=yes` configure option is for `ImageMagick` (which is a system library).

The `configure` command [you are referring to](https://github.com/mlocati/docker-php-extension-installer/blob/1.1.31/install-php-extensions#L1463) is for `imagick` (which is the PHP extension that allows you to use `ImageMagick` within PHP).

We don't compile `ImageMagick` (so, we don't run its `configure` command): we install a pre-compiled version provided by the Linux distribution ([`imagemagick`](https://pkgs.alpinelinux.org/package/v3.12/community/x86_64/imagemagick) for Alpine, and [`libmagickwand-6.q16-...`](https://packages.debian.org/buster/libmagickwand-6.q16-6) + [`libmagickcore-6.q16-...-extra`](https://packages.debian.org/it/buster/libmagickcore-6.q16-6-extra) for Debian)

And `imagick` [doesn't have any configure options](https://mlocati.github.io/pecl-info/#imagick)...
