### ISSUE TITLE
Microsoft ODBC drivers must be installed for sqlsrv and pdo_sqlsrv extensions

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#264]
see https://github.com/atk4/image/pull/35/files

how to install on different OS that Alpine: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#alpine17

**Comment by mlocati** [comment]
The PHP extensions are loaded without problems.
Do you have a sample (and simple) PHP script to showcase the issue?

**Comment by mvorisek** [comment]
CI result https://github.com/atk4/dsql/runs/1729467953?check_suite_focus=true

build pass, but `pdo_sqlsrv` can not connect to DB when ODBC drivers are not installed

**Comment by mlocati** [comment]
Is it possible, using the PHP extensions, to check if the odbc drivers are installed correctly without having a running mssql instance?

**Comment by mvorisek** [comment]
I am not an expect for MSSQL, but according https://github.com/atk4/image/pull/35/files#diff-8aad5bc8efe55f15feea83ad1cb1febdd84a072ef653e323afa72d9810890429R28 I think it is possible to check presence of some binary executable
