### ISSUE TITLE
Add PHP 8.1 support

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#271]
PHP 8.1 alpha2 is available, feature request to add PHP 8.1 support.

**Comment by mlocati** [comment]
Adding support for a new php version requires tons of hours. And working with a development version would require to do that whenever something changes.
So, I'm not going to officially add support for 8.1-dev, but I'd of course accept pull requests that fix support for 8.1 (provided that those changes don't break support for the current php versions).
