### ISSUE TITLE
CI cron job should test everything

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#275]
Currently, cron job tests build of only some recent extensions.

I propose:
- matrix with all php versions, eg. generate jobs for each individual php version
- OR implemented cron using current hour modulo N, eg. during one CI schedule test only some extensions, like test every hour lines from `supported-extensions` with (line number % 12) == (current hour (when started) % 12).

**Comment by mlocati** [comment]
In practice that would reserve a whole virtual machine to docker-php-extension-installer, since we'd likely run many hours/day our tests.
I don't know if people at GitHub would accept that...

**Comment by mvorisek** [comment]
They will, in `atk4/data` we burn burn testing almost constantly :)
