### ISSUE TITLE
Request: Ignore not available extensions

### ISSUE THREAD

**Issue by GM-Alex** [mlocati/docker-php-extension-installer#298]
It would be nice to ignore not available extensions or at least have a option to skip these extensions and only print a warning.

**Comment by mlocati** [comment]
Why?

**Comment by GM-Alex** [comment]
We use for example a build hook to build our containers for different php versions. If available we need for example ioncube. Without this option I need a wrapper script to detect the php version and exclude ioncube for php 8.0. So in my opinion it would make it nearly perfect with this option.

**Comment by mlocati** [comment]
That would overcomplicate the script imho, and only for a specific use case.

Furthermore, if I ask the script to install extension XYZ, and that extension is not supported, I'd expect that it fails, not that XYZ gets ignored...
I don't think I'll add support for this.

I'd suggest you to use `ARG`s or `ENV`s in your dockerfile to fine tune the list of PHP extensions to be installed  or add an extra `RUN` section where you drcide the extensions.

**Comment by GM-Alex** [comment]
Ok to bad, so I will stick to my wrapper script. At least it will mange the dependencies of the extension for me, that's also a win.
