### ISSUE TITLE
Plans to merge it with Official Docker image for PHP?

### ISSUE THREAD

**Issue by pedrofurtado** [mlocati/docker-php-extension-installer#3]
That is an awesome library, man! 

It will be a great idea to merge this with the Official Docker image for PHP, because it's frustating to install the PHP extensions in Docker with only `docker-php-ext-install` and a lot of bugs or missing apt packages.

Do you have any plan to propose a merge?

**Comment by mlocati** [comment]
I don't know if the PHP Docker maintainers want to maintain this library, but maybe it could be included in their main [readme](https://github.com/docker-library/php/blob/master/README.md)...  @tianon ?

**Comment by mlocati** [comment]
I guess that all we can do is just https://github.com/docker-library/docs/pull/1639

**Comment by mlocati** [comment]
Fixed by
