### ISSUE TITLE
Request: PHP Ds

### ISSUE THREAD

**Issue by designermonkey** [mlocati/docker-php-extension-installer#304]
PHP Ds is an excellent extension providing some much needed performance improvements in the form of data structures. I use it on every project now.

It would be great to have this added to your library. It's not difficult to do manually in docker, however I would love to just add it to the list this extension handles.

Thanks :)

**Comment by mlocati** [comment]
Is this one https://pecl.php.net/package/ds ?

**Comment by designermonkey** [comment]
Sorry I should have pointed that out. Yes it's that one.

**Comment by mlocati** [comment]
Done
