### ISSUE TITLE
Tags not updating anymore in Dockerhub?

### ISSUE THREAD

**Issue by pataar** [mlocati/docker-php-extension-installer#307]
I'm not sure why, but it seems that not all new releases are tagged in Dockerhub anymore:

Docker:

![image](https://user-images.githubusercontent.com/3403851/109136061-020a7800-7758-11eb-958a-a15bf5ec11a5.png)

Github:
![image](https://user-images.githubusercontent.com/3403851/109136098-0d5da380-7758-11eb-843a-d59a7603bdc0.png)

**Comment by mlocati** [comment]
I don't know what changed, maybe the docker version in the GitHub Action.

With https://github.com/mlocati/docker-php-extension-installer/commit/137eb23a75cc8ba6656f15d536175793d99896ca we should be sure that we push all the tagged images to docker hub

**Comment by pataar** [comment]
Thanks!
