### ISSUE TITLE
Wrong XDebug version is installed on PHP 5.6

### ISSUE THREAD

**Issue by evs-xsarus** [mlocati/docker-php-extension-installer#315]
Currently, the latest 2.x version is installed. This fails on PHP 5.6 as the latest supported is 2.5.5

I expect that the logic takes into account the PHP version for which the module is installed.

For now, I've used this workaround:

```
RUN if [ "$version" = "8.0-cli" ]; then \
        # PHP 8.x
       install-php-extensions xdebug-^3; \
   elif [ "$version" = "5.6-cli" ]; then \
        # PHP 5.6
       install-php-extensions xdebug-2.5.5; \
   else \
        # PHP 5.x and 7.x
       install-php-extensions xdebug-^2; \
   fi
```

**Comment by mlocati** [comment]
The logic is there: https://github.com/mlocati/docker-php-extension-installer/blob/1.2.19/install-php-extensions#L2146-L2162, and indeed it works:

```sh
# Launch with docker run --rm -it php:5.6-cli bash
$ curl -sSLf \
    -o /usr/local/bin/install-php-extensions \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
$ chmod +x /usr/local/bin/install-php-extensions
$ install-php-extensions xdebug
install-php-extensions v.1.2.19
[...]
$ php --ri xdebug | grep -i version
Version => 2.5.5
```

**Comment by evs-xsarus** [comment]
Mmm. somethings goes wrong though, this is the output when I don't use the elif:

> \Removing intermediate container 91dcc330fdf9
>  ---> 6b33bcff7ff8
> Step 14/17 : RUN if [ "$version" = "8.0-cli" ]; then        install-php-extensions xdebug-^3;    else        install-php-extensions xdebug-^2;    fi
>  ---> Running in 33d18aabdbec
> /install-php-extensions v.1.2.19
> \Updating channel "pecl.php.net"
> /Channel "pecl.php.net" is up to date
> ### INSTALLING REMOTE MODULE xdebug ###
> |  (installing version 2.9.8)
> /pecl/xdebug requires PHP (version >= 7.1.0, version <= 7.4.99), installed version is 5.6.40
> No valid packages found
> install failed
> -ERROR: Service 'phpcli56' failed to build : The command '/bin/sh -c if [ "$version" = "8.0-cli" ]; then        install-php-extensions xdebug-^3;    else        install-php-extensions xdebug-^2;    fi' returned a non-zero code: 1

**Comment by mlocati** [comment]
> `RUN if [ "$version" = "8.0-cli" ]; then install-php-extensions xdebug-^3; else install-php-extensions xdebug-^2; fi`

If you specify the version, the script always installs that version. If you use the `^` operator (eg `^2`), the script always install the most recent version (eg `2.9.8`), without considering the PHP version.

To solve the issue, you can simply have

```Dockerfile
RUN install-php-extensions xdebug
```

It will install the most recent version compatible with the PHP version.

**Comment by evs-xsarus** [comment]
Well, I need max. v2.x on PHP 5.x and 7.x . Hence the if..else construction.  When, on PHP 5.6, this line is used:

```install-php-extensions xdebug-^2; \```

The error as shown in https://github.com/mlocati/docker-php-extension-installer/issues/315#issuecomment-793605788 occurs.  

As shown on https://2.xdebug.org/docs/compat , the latest version for PHP 5.6 is XDebug v2.5.x , but the installer script tries to install 2.9.8. 

![image](https://user-images.githubusercontent.com/44158071/110452045-1722c780-80c5-11eb-852a-0ae456e11ef2.png)

The logic you've linked to , specifies that 2.5.5 must be installed though.

**Comment by mlocati** [comment]
> Well, I need max. v2.x on PHP 5.x and 7.x

Since xdebug 3 is compatible with PHP 7.2+ (see [this other project of mine](https://mlocati.github.io/pecl-info/#xdebug)), I'd write this:

```Dockerfile
RUN if [ "${version#7.2}" != "$version" ] || [ "${version#7.3}" != "$version" ] || [ "${version#7.4}" != "$version" ]; then install-php-extensions xdebug-^2 ;\
    else install-php-extensions xdebug ;\
    fi
```

Which in English would be "if `$version` starts with `7.2`, `7.3` or `7.4`, install `xdebug-^2` otherwise install `xdebug`"

> The logic you've linked to , specifies that 2.5.5 must be installed though.

Not exactly. Here's how it works:
1. the `installRemoteModule_version` is initialized [here](https://github.com/mlocati/docker-php-extension-installer/blob/1.2.19/install-php-extensions#L1516). So, if if you pass `^2` to it, the script sets `installRemoteModule_version` to `2.9.8` (which is the most recent 2.x version
2. [the lines I linked above](https://github.com/mlocati/docker-php-extension-installer/blob/1.2.19/install-php-extensions#L2146-L2162) are executed only if `installRemoteModule_version` is empty (and it's not the case if you pass `^2`).

**Comment by evs-xsarus** [comment]
Thank you for this explanation, I get it now :).
