### ISSUE TITLE
Option to keep dependencies (oposite of the deprectaed cleanup option)

### ISSUE THREAD

**Issue by fnagel** [mlocati/docker-php-extension-installer#326]
Is there an option to NOT clean specific package dependencies? For example, my applications needs ImageMagick but not only Imagick but the real `convert` bin too. Any chance to do this?

**Comment by mlocati** [comment]
You'd risk to have many other unwanted dependencies, I'm not going to implement that...

What about installing your dependencies on your own?

**Comment by fnagel** [comment]
Ok, that makes sense. 

I initially hoped not to install those dependencies on my own as they (at least) depend on the PHP version (and docker-php-extension-installer does a wonderful job for most cases!). Too bad TYO3 CMS needs the IM bins and not only the PHP extension.

Anyway, this did not work for me with PHP 7.4 Apache image (but should install IM 7.x)
```
RUN apt-get update \
    && apt-get install -y wget build-essential \
    && wget https://imagemagick.org/download/ImageMagick.tar.gz \
    && tar xvzf ImageMagick.tar.gz \
    && cd ImageMagick-7* \
    && ./configure \
    && make \
    && make install \
    && ldconfig /usr/local/lib \
    && make check
```

This works, bit only installs the bundled version 6.9.x:
```
RUN apt-get update \
    && apt install -y --no-install-recommends libmagickwand-dev imagemagick
RUN pecl install imagick \
    && docker-php-ext-enable imagick
```

Thanks for your help!

**Comment by mlocati** [comment]
When installing the imagick PHP extension, install-php-extensions doesn't install the whole imagemagick system package, but only these system packages: https://github.com/mlocati/docker-php-extension-installer/blob/1.2.23/install-php-extensions#L587-L588

> this did not work for me

"Did not work" doesn't help that much to understand what's going wrong... do you have an error message?

**Comment by fnagel** [comment]
> When installing the imagick PHP extension, install-php-extensions doesn't install the whole imagemagick system package, but only these system packages

Which explains why my CMS package does not work with this only.

> "Did not work" doesn't help that much to understand what's going wrong... do you have an error message?

No error message, but IM does not work and when printing out version information it seems there are no "Delegates (built-in)" installed at all.

**Comment by mlocati** [comment]
@fnagel I don't understand which are your needs. Isn't the imagick PHP extension working for you?

Here's a sample session, which shows the currently supported formats for the imagick PHP extension as installed with `install-php-extensions`:

```sh
$ docker run --rm -it php:7.4-cli bash
$ curl -sSLfo /usr/local/bin/install-php-extensions \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
$ chmod +x /usr/local/bin/install-php-extensions
$ install-php-extensions imagick
$ php -r 'echo json_encode(Imagick::queryFormats());'
["3FR","3G2","3GP","AAI","AI","ART","ARW","AVI","AVS","BGR","BGRA","BGRO","BIE","BMP","BMP2","BMP3","BRF","CAL","CALS","CANVAS","CAPTION","CIN","CIP","CLIP","CMYK","CMYKA","CR2","CRW","CUR","CUT","DATA","DCM","DCR","DCX","DDS","DFONT","DJVU","DNG","DOT","DPX","DXT1","DXT5","EPDF","EPI","EPS","EPS2","EPS3","EPSF","EPSI","EPT","EPT2","EPT3","ERF","EXR","FAX","FILE","FITS","FRACTAL","FTP","FTS","G3","G4","GIF","GIF87","GRADIENT","GRAY","GRAYA","GROUP4","GV","H","HALD","HDR","HEIC","HISTOGRAM","HRZ","HTM","HTML","HTTP","HTTPS","ICB","ICO","ICON","IIQ","INFO","INLINE","IPL","ISOBRL","ISOBRL6","J2C","J2K","JBG","JBIG","JNG","JNX","JP2","JPC","JPE","JPEG","JPG","JPM","JPS","JPT","JSON","K25","KDC","LABEL","M2V","M4V","MAC","MAGICK","MAP","MASK","MAT","MATTE","MEF","MIFF","MKV","MNG","MONO","MOV","MP4","MPC","MPEG","MPG","MRW","MSL","MSVG","MTV","MVG","NEF","NRW","NULL","ORF","OTB","OTF","PAL","PALM","PAM","PANGO","PATTERN","PBM","PCD","PCDS","PCL","PCT","PCX","PDB","PDF","PDFA","PEF","PES","PFA","PFB","PFM","PGM","PGX","PICON","PICT","PIX","PJPEG","PLASMA","PNG","PNG00","PNG24","PNG32","PNG48","PNG64","PNG8","PNM","PPM","PREVIEW","PS","PS2","PS3","PSB","PSD","PTIF","PWP","RADIAL-GRADIENT","RAF","RAS","RAW","RGB","RGBA","RGBO","RGF","RLA","RLE","RMF","RW2","SCR","SCT","SFW","SGI","SHTML","SIX","SIXEL","SPARSE-COLOR","SR2","SRF","STEGANO","SUN","SVG","SVGZ","TEXT","TGA","THUMBNAIL","TIFF","TIFF64","TILE","TIM","TTC","TTF","TXT","UBRL","UBRL6","UIL","UYVY","VDA","VICAR","VID","VIFF","VIPS","VST","WBMP","WEBP","WMF","WMV","WMZ","WPG","X","X3F","XBM","XC","XCF","XPM","XPS","XV","XWD","YCbCr","YCbCrA","YUV"]
```

**Comment by fnagel** [comment]
> I don't understand which are your needs. Isn't the imagick PHP extension working for you?

No, TYPO3 CMS needs the ImacgMagick bins and not only the PHP extension imagick.

https://docs.typo3.org/m/typo3/guide-installation/master/en-us/In-depth/SystemRequirements/Index.html

**Comment by mlocati** [comment]
I think you should ask the ImageMagick people: this project (`install-php-extensions`) is only for installing PHP extensions
