### ISSUE TITLE
Script treats "multi-image container" as unofficial container and exits.

### ISSUE THREAD

**Issue by Abhinav1217** [mlocati/docker-php-extension-installer#328]
I am working on a Laravel+vue app. 

Based on tips from here
https://stackoverflow.com/questions/44447821/how-to-create-a-docker-image-for-php-and-node
I am trying to build a single container for both php and node. 

```
FROM php:fpm-alpine as backend
FROM node:alpine as frontend

ADD ./www.conf /usr/local/etc/php-fpm.d/www.conf

# COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync
```

When I do this, the script exits with message that this script is meant to work with official php image only. I am using official image, it seems It is detecting inclusion of node as an Issue, (I tried without node and it worked but I don't want separate containers). 

I tried this format 
```
FROM php:fpm-alpine as backend
# /// php stuff

FROM node:alpine as frontend
# /// vuejs stuff.
```

Turns out that for some reason, final image doesn't have php in it, only nodejs ( I `tty`'ed  into it to find out )
 
Is there any workaround?

**Comment by mlocati** [comment]
The final docker image is build based on the last `FROM` image you have in your dockerfile.
Previous `FROM` directives are useful only to copy files from other images.
So, If you want to use node and a PHP image, you should do exactly what's reported in the stackoverflow article you mentioned: define a node image as `FROM node:latest AS node`.
**After** start your final docker image by adding `php:fpm-alpine` and copying data from the node image.
That's the way Docker works: a single dockerfile can build only a single docker image, which is based on a single base image.
