### ISSUE TITLE
Interest check: validate composer SHA

### ISSUE THREAD

**Issue by timacdonald** [mlocati/docker-php-extension-installer#329]
As per the official docs, the programmatic way to install composer is with the following script:

```sh
#!/bin/sh

EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
RESULT=$?
rm composer-setup.php
exit $RESULT
```

Source: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md#how-do-i-install-composer-programmatically-

Would you be open to a PR that implements the SHA check? This spreads the security out so that both composer and github would have to be compromised for someone to inject malicious code into the downloaded composer binary (and we've see how this is possible recently with the recent PHP git compromise).

Happy to give it a whirl myself, but wanted to check if the maintainers would be open to a PR before I spend the time on it.

Thanks for the fantastic project.

**Comment by mlocati** [comment]
What about https://github.com/mlocati/docker-php-extension-installer/pull/330?
