### ISSUE TITLE
ast (abstract syntax tree)

### ISSUE THREAD

**Issue by Jimbolino** [mlocati/docker-php-extension-installer#335]
I tried to add this package myself, but my sh scripting skills are not good enough
So I was wondering if someone could add it for me :)

When I install it via docker it goes like this:
```
apk add --no-cache --update --virtual .build-deps $PHPIZE_DEPS
pecl install ast
docker-php-ext-enable ast
```
https://pecl.php.net/package/ast
https://github.com/nikic/php-ast

**Comment by mlocati** [comment]
I've  just checked that the script can already install AST ;)
