### ISSUE TITLE
php8 apcu extension

### ISSUE THREAD

**Issue by miguelBarreiro85** [mlocati/docker-php-extension-installer#343]
when installing apcu extension it throws an error

image:  FROM wordpress:5-php8.0-fpm

using this script:

apt-get update -yqq && apt-get -f install -yyq wget

// download helper script
//see https://github.com/mlocati/docker-php-extension-installer/
wget -q -O /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions  \
    || (echo "Failed while downloading php extension installer!"; exit 1)

// install extensions

chmod uga+x /usr/local/bin/install-php-extensions && sync && install-php-extensions \
    opcache \
    xdebug \
    intl \
    pdo_mysql \
    gd \
    zip \
    xsl \
    soap \
    bcmath \
    igbinary \
    imagick \
    redis \
    json \
    mbstring \
    pspell \
    xml \
// apcu \ -> ERROR the other extensions are installed (this one just made it with pecl...)

**Comment by mlocati** [comment]
What's the error?

**Comment by miguelBarreiro85** [comment]
Im waiting to init a database with 17Gb but as soon as possible i let you know.  Was something inside a php classe or file, so i think it downloaded the extension but then crashed

**Comment by DDirlam** [comment]
Hello everyone, I also have an error. the server for https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions is not accessible 503 villeicht has something to do with it?

**Comment by mlocati** [comment]
@miguelBarreiro85 any update?
