### ISSUE TITLE
redis with igbinary

### ISSUE THREAD

**Issue by mehmetresatdilbaz** [mlocati/docker-php-extension-installer#349]
Hi,

I'm trying to install "redis" extension with "igbinary" support.

```
FROM php:8.0-cli
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions igbinary
RUN install-php-extensions redis
```

Is it possible to install redis with igbinary support?

**Comment by mlocati** [comment]
Have you tried to run `php --ri redis`? What's its output?

**Comment by mehmetresatdilbaz** [comment]
When trying to use with igbinary serializer : "Error: phpredis was not compiled with igbinary support!"

**Comment by mlocati** [comment]
What's the output of `php --ri redis` ?

**Comment by mehmetresatdilbaz** [comment]
`

redis
--
252 | &nbsp;
253 | Redis Support =&gt; enabled
254 | Redis Version =&gt; 5.3.4
255 | Redis Sentinel Version =&gt; 0.1
256 | Available serializers =&gt; php, json, igbinary
257 | Available compression =&gt; lzf, zstd
258 | &nbsp;
259 | Directive =&gt; Local Value =&gt; Master Value
260 | redis.arrays.algorithm =&gt; no value =&gt; no value
261 | redis.arrays.auth =&gt; no value =&gt; no value
262 | redis.arrays.autorehash =&gt; 0 =&gt; 0
263 | redis.arrays.connecttimeout =&gt; 0 =&gt; 0
264 | redis.arrays.distributor =&gt; no value =&gt; no value
265 | redis.arrays.functions =&gt; no value =&gt; no value
266 | redis.arrays.hosts =&gt; no value =&gt; no value
267 | redis.arrays.index =&gt; 0 =&gt; 0
268 | redis.arrays.lazyconnect =&gt; 0 =&gt; 0
269 | redis.arrays.names =&gt; no value =&gt; no value
270 | redis.arrays.pconnect =&gt; 0 =&gt; 0
271 | redis.arrays.previous =&gt; no value =&gt; no value
272 | redis.arrays.readtimeout =&gt; 0 =&gt; 0
273 | redis.arrays.retryinterval =&gt; 0 =&gt; 0
274 | redis.arrays.consistent =&gt; 0 =&gt; 0
275 | redis.clusters.cache_slots =&gt; 0 =&gt; 0
276 | redis.clusters.auth =&gt; no value =&gt; no value
277 | redis.clusters.persistent =&gt; 0 =&gt; 0
278 | redis.clusters.read_timeout =&gt; 0 =&gt; 0
279 | redis.clusters.seeds =&gt; no value =&gt; no value
280 | redis.clusters.timeout =&gt; 0 =&gt; 0
281 | redis.pconnect.pooling_enabled =&gt; 1 =&gt; 1
282 | redis.pconnect.connection_limit =&gt; 0 =&gt; 0
283 | redis.pconnect.echo_check_liveness =&gt; 1 =&gt; 1
284 | redis.pconnect.pool_pattern =&gt; no value =&gt; no value
285 | redis.session.locking_enabled =&gt; 0 =&gt; 0
286 | redis.session.lock_expire =&gt; 0 =&gt; 0
287 | redis.session.lock_retries =&gt; 10 =&gt; 10
288 | redis.session.lock_wait_time =&gt; 2000 =&gt; 2000

`

**Comment by mlocati** [comment]
Could you share some minimal code to reproduce the `phpredis was not compiled with igbinary support!` error?

**Comment by mehmetresatdilbaz** [comment]
I'm using laravel-lodash for override serializer for laravel.

in it's connector

``
protected function getSerializerFromConfig(string $serializer): int
    {
        switch ($serializer) {
            case 'igbinary':
                if (! defined('Redis::SERIALIZER_IGBINARY')) {
                    throw new InvalidArgumentException('Error: phpredis was not compiled with igbinary support!');
                }
                $flag = Redis::SERIALIZER_IGBINARY;
                break;
            case 'php':
                $flag = Redis::SERIALIZER_PHP;
                break;
            default:
                $flag = Redis::SERIALIZER_NONE;
                break;
        }

        return $flag;
    }
``

throws that exception.

**Comment by mlocati** [comment]
It's working fine for me...

```
$ docker run --rm -it php:8.0-cli bash

# curl -sSL -o /usr/local/bin/install-php-extensions \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
# chmod +x /usr/local/bin/install-php-extensions
# install-php-extensions igbinary redis
[...omissis...]
# php -r 'var_dump(defined("Redis::SERIALIZER_IGBINARY"));'
bool(true)
```

Please remark that, in order to have the redis PHP extension support igbinary, you have two options:

1. install igbinary *before* redis:
   ```sh
   install-php-extensions igbinary
   install-php-extensions redis
   ```
2. install igbinary and redis at the same time (install-php-extensions will take care of the order):
   ```sh
   install-php-extensions redis igbinary
   ```
