### ISSUE TITLE
Request: lzf php extension support

### ISSUE THREAD

**Issue by axelrtgs** [mlocati/docker-php-extension-installer#352]
There already is a pecl package available and installation is pretty simple `pecl install lzf` Would be really nice if support was added here so I can install everything in the same manner.

I looked at the code quickly and I was a bit lost on how I could contribute a PR to adding it. If you point me in the right direction I do not mind making the PR.

Thanks so much for you consideration.

**Comment by mlocati** [comment]
There's a compile time option for LZF (`enable-lzf-better-compression`) - see https://mlocati.github.io/pecl-info/#lzf

Should we enable it?

**Comment by axelrtgs** [comment]
I would not enable it by default. not sure how hard it is to have it an option.

for my use, I prefer the speed over size but im sure others would want size over speed so if its not too difficult then I would make it configurable.

Perhaps just have it as separate package name. 

lzf -> lzf-speed
lzf-speed -> default without `enable-lzf-better-compression`
lzf-size -> compiler flag set to`enable-lzf-better-compression`

I'm sure you know better than me the best way to achieve this.

**Comment by mlocati** [comment]
I'd use an environmental variable to enable that flag, something like

```sh
PHP_LZF_BETTERCOMPRESSION=1 install-php-extensions lzf
```

**Comment by axelrtgs** [comment]
that sounds perfect and much better than what came to my mind ❤️

**Comment by mlocati** [comment]
I used `IPE_LZF_BETTERCOMPRESSION` instead of `PHP_LZF_BETTERCOMPRESSION` (`IPE` stands for `install-php-extensions`) - see https://github.com/mlocati/docker-php-extension-installer/#configuration

**Comment by axelrtgs** [comment]
Awesome, thanks for this addition. Much appreciated
