### ISSUE TITLE
Opcache can not be installed for PHP 8.1-alpha1

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#355]
see https://github.com/mvorisek/image-php/runs/2865808256?check_suite_focus=true

is this an issue in docker-php-extension-installer?

**Comment by mlocati** [comment]
I think it's a PHP issue: https://bugs.php.net/bug.php?id=81133

**Comment by mvorisek** [comment]
Closing as it will be fixed probably with PHP 8.1-alpha2 release
