### ISSUE TITLE
Enable Avif on PHP 8.1 gd

### ISSUE THREAD

**Issue by shyim** [mlocati/docker-php-extension-installer#360]
Avif has finally land on PHP 8.1 to use it we need to install https://pkgs.alpinelinux.org/package/edge/community/x86_64/libavif-dev

See Commit: https://github.com/php/php-src/commit/81f6d36c90b8626660a6571cdc128265fa00697f

**Comment by shyim** [comment]
libavif package seems only availble in bullseye/sid on Debian. To enable it on Debian it will require Debian 11 as now 🤔

**Comment by mlocati** [comment]
I just tried compiling GD with avif, but:

1. on Debian Buster I have a segmentation fault when invoking `imageavif()`
2. on Alpine 3.14 I have the error `Error 2: imageavif(): avif error - Could not encode image: No codec available` when invoking `imageavif()`

**Comment by mlocati** [comment]
See https://bugs.php.net/bug.php?id=81217
