### ISSUE TITLE
The latest stable version of mongodb is alpha?

### ISSUE THREAD

**Issue by gander** [mlocati/docker-php-extension-installer#379]
Installer version: **v1.2.39** (also earlier)

```
### INSTALLING REMOTE MODULE mongodb ###
  - Installing mongodb (latest-stable): Downloading (100%)         
+-----------------------------------+--------------+
| Package name                      | mongodb      |
| Package version (current release) | 1.10.0alpha1 |
| Package status                    | alpha        |
+-----------------------------------+--------------+
```

I have to use this notation so that it is the last stable version:
```
mongodb-^1.9
```

**Comment by gander** [comment]
Also, **beta** is stable?
```
### INSTALLING REMOTE MODULE amqp ###
  (installing version beta)
  - Installing amqp (latest-beta): Downloading (100%)         
+-----------------------------------+------------+
| Package name                      | amqp       |
| Package version (current release) | 1.11.0beta |
| Package status                    | beta       |
+-----------------------------------+------------+
```

**Comment by mlocati** [comment]
Last time I checked mongodb we needed to force a specific version in order to make it work on PHP 7.0+.

Let's see if now we can use the latest stable release: see #380

**Comment by mlocati** [comment]
It seems that pickle is picking the very latest version if you don't specify a version (which is `1.10.0alpha1`).
You can force the very latest stable version by using `mongodb-stable`.

**Comment by llaville** [comment]
@mlocati adding the tip (force latest stable version) to the README page project (https://github.com/mlocati/docker-php-extension-installer#installing-specific-versions-of-an-extension) will be helpfull !

**Comment by mlocati** [comment]
Pull requests are very welcome 😉
