### ISSUE TITLE
Feature - Check supported version

### ISSUE THREAD

**Issue by llaville** [mlocati/docker-php-extension-installer#381]
Hello,

First, I found your project recently and I'd like it ! Very usefull :) 

Second, I think it will be great to have a check phase on supported version before trying to install. That will avoid a docker image build failure.
A warning message like for already module installed will be enough (for me) to notice uninstalled modules.

Example: If you try to install `propro` extension on PHP 8.0, compilation failed because this module is not supported for PHP 8+

Thanks in advance

**Comment by mlocati** [comment]
Hi!

That'd be rather complicated... we'd need to update the script whenever something changes, and we'd need to check if you also pass a version...

The quickest solution is that you check https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions before adding a new extension

**Comment by llaville** [comment]
I understand your point of view about complexity degree, but don't forget also that errors are human ;-)

**Comment by mlocati** [comment]
[For sure I know](https://github.com/mlocati/docker-php-extension-installer/pull/382) :wink:
