### ISSUE TITLE
Mongodb extension and PHP 8.1 support

### ISSUE THREAD

**Issue by llaville** [mlocati/docker-php-extension-installer#396]
Hello @mlocati 

**FYI only**, I've just tried to install latest release 1.10.0 (stable) of PECL [mongodb](https://pecl.php.net/package/mongodb) with docker image php:8.1.0beta1-pfm and run in trouble (cannot compile source code).
It was OK with docker image php:8.1.0alpha3-fpm (compile source code and install module).

**Comment by mlocati** [comment]
https://github.com/mongodb/mongo-php-library/issues/850

**Comment by llaville** [comment]
I'm happy to see that latest release https://github.com/mongodb/mongo-php-driver/releases/tag/1.11.0alpha1 is now compatible with PHP 8.1.0 RC1
