### ISSUE TITLE
Remove dev packages after building

### ISSUE THREAD

**Issue by Hipska** [mlocati/docker-php-extension-installer#4]
This script installs a lot of packages that are needed to build the php extensions. It would be nice that it also removes the ones that are not needed afterwards in order to keep layers small.

These are mostly the ones that end with `*-dev`.

**Comment by mlocati** [comment]
I agree.
Are you 100% sure that it's safe to `apt remove --purge` all the `*-dev` packages [listed here](https://github.com/mlocati/docker-php-extension-installer/blob/eca94d432b66589fed91b79c1b8f5bdcfca45d26/install-php-extensions#L108-L235)?
And what about other packages (like `cmake` for instance)?

**Comment by mlocati** [comment]
@Hipska #5 should implement this (and [here's](https://github.com/mlocati/docker-php-extension-installer/blob/c3d49327b83cd8012b7eccc2726a7a75e2487985/install-php-extensions#L292) the list of apt packages that will be removed.
