### ISSUE TITLE
Can php-extension-installer keep apt repo cache and downloaded packages?

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [mlocati/docker-php-extension-installer#418]
I'd love to integrate it with buildkit's `--mount=type=cache` which is intended to cache temporary files and NOT include them into the final image. The good thing is this this storage can keep downloaded packages and repo data so that the overall extension  installation can finish faster.

Documentation: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache
Some useful examples: https://github.com/FernandoMiguel/Buildkit#mounttypecache

**Comment by mlocati** [comment]
@AlexeyKupershtokh Do you mean you'd like a way to skip the execution of [these lines](https://github.com/mlocati/docker-php-extension-installer/blob/1.2.55/install-php-extensions#L2728-L2735)?

**Comment by AlexeyKupershtokh** [comment]
Yes exactly. So that we could reuse cache between runs and at the same time
do not bloat the image

чт, 12 авг. 2021 г., 23:14 Michele Locati ***@***.***>:

**Comment by mlocati** [comment]
Would something like https://github.com/mlocati/docker-php-extension-installer/pull/420 work for you?
For a description of what it'd do see the [description of the new `IPE_KEEP_SYSPKG_CACHE`](https://github.com/mlocati/docker-php-extension-installer/blob/7eabdbf791a68feebdb76f262608163389309003/README.md#configuration)

**Comment by AlexeyKupershtokh** [comment]
My internet connection wasn't the most stable today. Though I tried to build this dockerfile by changing the `echo and commenting/uncommenting the needed `RUN` instruction.

```dockerfile
FROM php:7.4-fpm

RUN echo 10000

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# install improved extension manager
COPY install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

# install php extensions
#RUN --mount=type=cache,id=ipe,target=/var/lib/apt/ --mount=type=cache,id=ipe2,target=/var/cache/apt --mount=type=cache,id=pear,target=/tmp/pear IPE_KEEP_SYSPKG_CACHE=1 \
#RUN \
    install-php-extensions @composer-1 \
    amqp apcu bcmath gd gmp intl mbstring opcache \
    pdo pdo_mysql pdo_pgsql pgsql soap sockets zip

```

The results are the following on my laptop, install-php-extensions run time measured:
```
no cache | hot | cold
98         85    98
103        83    124
96         85    104
113        83    98
```

So you can see that when the apt cache is hot it took ~18 seconds avg less than having no cache at all.

Though I think the most part of this save was not apt cache you took care of but keeping of downloaded packages by apt which is irrelevant to install-php-extensions. Though in the overall it looks perspective to me.

**Comment by mlocati** [comment]
So, #420 is pretty useless, isn't it?

**Comment by AlexeyKupershtokh** [comment]
It has only a partial effect. I've made more measurements with only downloaded packages cached:
```
packages only
95
92
97
91
```
would split this 18s benefit to these features approx half by half. I'd probably keep this in the codebase for people who would like to extremely optimize with buildkit caching.
