### ISSUE TITLE
Looking forward to adding the "ffmpeg" plugin

### ISSUE THREAD

**Issue by jefferyjob** [mlocati/docker-php-extension-installer#427]
If you can add the "ffmpeg" plug-in, that would be great

**Comment by mlocati** [comment]
There's no `ffmpeg` package in the PECL repository: https://pecl.php.net/package-search.php?pkg_name=ffmpeg

**Comment by jefferyjob** [comment]
Well, thank you for replying to me

**Comment by jefferyjob** [comment]
closed
