### ISSUE TITLE
One MILLION of docker pulls!

### ISSUE THREAD

**Issue by mlocati** [mlocati/docker-php-extension-installer#429]
Well, I never thought this project would have so much traction... thanks everybody.

**Comment by drpayyne** [comment]
Thank you for this! I recently discovered this repo and it has been _very_ useful for my projects.

**Comment by Hipska** [comment]
Hi, using your tool a lot, but just figured out there is the command `docker-php-ext-install` does that one makes your tool obsolete?

**Comment by mlocati** [comment]
@Hipska yep, my script uses `docker-php-ext-install`, but does a lot more
