### ISSUE TITLE
"Operation not permitted" on previous docker versions

### ISSUE THREAD

**Issue by ohaag** [mlocati/docker-php-extension-installer#430]
Hello

I'm not sure if it is something you changed recently or not, I was able to build my Dockerfile with docker 19.03.12 before.
Now, it still works in 20.10.8, but on the following versions I couldn't build anymore:

- 20.10.2 (MacOS)
- 20.10.0 (2nd MacOS)
- 19.03.12 (Runner gitlab)

For all Mac where I was able to reproduce this thing, a docker update fixed the issue, but I think it could be common to use your project in a CI with fixed docker version like I did.

Sorry for the lack of informations, but I think it is better to be aware of something like this early.

Here are the docker instructions with the trace of the CI :
```sh
FROM $REGISTRY/lizeo-php-docker/php:7.4-alpine-supervisor
ARG USER=tyrebot

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN set -ex; \
    chmod +x /usr/local/bin/install-php-extensions; sync; \
    install-php-extensions pdo_pgsql pcntl;
```
```sh
/bin/sh /usr/src/php/ext/pdo_pgsql/libtool --mode=compile cc -I/usr/local/include/php/ext -I. -I/usr/src/php/ext/pdo_pgsql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_pgsql/include -I/usr/src/php/ext/pdo_pgsql/main -I/usr/src/php/ext/pdo_pgsql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/pdo_pgsql/pdo_pgsql.c -o pdo_pgsql.lo 
make: /bin/sh: Operation not permitted
make: *** [Makefile:192: pdo_pgsql.lo] Error 127
The command '/bin/sh -c set -ex;     chmod +x /usr/local/bin/install-php-extensions; sync;     install-php-extensions pdo_pgsql pcntl;' returned a non-zero code: 2
```

**Comment by mlocati** [comment]
This is not caused by my script, and there's nothing I can do about that.

See https://github.com/mlocati/docker-php-extension-installer/issues/378

**Comment by ohaag** [comment]
Ok, thank you for this explained example.
