### ISSUE TITLE
Missing MSSQL support for Debian Bullseye/11

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#432]
see https://github.com/mvorisek/image-php/actions/runs/1243314446 and https://github.com/mvorisek/image-php/commit/0868d7263af21537661db5a326e0450cd41e7050 source files/changes.

This repo should test againt Debian Buster & Bullseye images.

**Comment by mlocati** [comment]
Bullseye *is* supported.
But the sqlserver stuff doesn't work for it yet.
See https://github.com/mlocati/docker-php-extension-installer#special-requirements

**Comment by mlocati** [comment]
PS: the problem is that Microsoft hasn't published yet an sql server driver (msodbcsql17) for Debian 11 (bullseye).

Compare (Debian  10)
https://packages.microsoft.com/debian/10/prod/pool/main/m/

with (Debian  11)
https://packages.microsoft.com/debian/11/prod/pool/main/m/

**Comment by mvorisek** [comment]
Thanks. In git history I found https://github.com/mlocati/docker-php-extension-installer/commit/a8749d10016ba37719b8722f3dfb8b11df4b9b16 .

I belive the drivers are installed in https://github.com/mlocati/docker-php-extension-installer/blob/d466cc52665911c22cc4804fc4f26fa41b8cd2c2/install-php-extensions#L1399

very often, official repos takes months or even years to adapt to a new distro release. Can you please try using repo for Debian Buster/10 for Debian Bullseys/11+ OS?

**Comment by mvorisek** [comment]
The Debian 10 package requires `multiarch-support`. This dep needs to be either removed from the package or faked like in my experiment

https://github.com/mvorisek/image-php/compare/bullseye#diff-559e0106c0e7faedc4cc5b6b3a26fbac9d5d107287e14ad5de13175cb7ca8d38R15

(inspired by https://askubuntu.com/questions/888663/how-to-fake-resolve-a-dependency-in-apt-get )

**Comment by mlocati** [comment]
> This dep needs to be either removed from the package or faked like in my experiment

Why?

**Comment by mlocati** [comment]
> Can you please try using repo for Debian Buster/10 for Debian Bullseys/11+ OS?

> This dep needs to be either removed from the package or faked like in my experiment

I will not do that. Why? Because the dep may be used by other packages and/or utilities. By not actually installing it, we may break other stuff.

But of course you are free to do that yourself: if install-php-extensions sees that the Microsoft drivers are already installed, it won't try to install them again

**Comment by mvorisek** [comment]
> I will not do that. Why? Because the dep may be used by other packages and/or utilities. By not actually installing it, we may break other stuff.

It is safe as that package is not available for Debian 11 and probably never will.

Cleaner solution is to download the .dpkg, extract it, remove the multiarch dependency and pack it again.

> 
But of course you are free to do that yourself: if install-php-extensions sees that the Microsoft drivers are already installed, it won't try to install them again

That is also a solution and I will do that :)
