### ISSUE TITLE
XDebug 3 installation error 

### ISSUE THREAD

**Issue by zlodes** [mlocati/docker-php-extension-installer#433]
Hi!

I'm having an error while installation of `xdebug-^3`:

```
install-php-extensions v.1.2.60
### INSTALLING REMOTE MODULE xdebug ###
  (installing version 3.1.0beta2)

In Pickle.php line 81:
                                                                             
  http error while loading information for xdebug-3.1.0beta2: unknown error  
```

I thought that I had connection troubles and tried to use VPN connection and got the same result. 

Dockerfile example to reproduce:
```Dockerfile 
FROM php:8.0

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions xdebug-^3
```

<details>
<summary>Full build log</summary>

Deploying '<unknown> Dockerfile: tests/Dockerfile'...
Building image...
Preparing build context archive...
[==================================================>]1/1 files
Done

Sending build context to Docker daemon...
[==================================================>]  245.0B
Done

Step 1/3 : FROM php:8.0
 ---> 1ecee270c294
Step 2/3 : ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
Downloading [==================================================>] 111.6kB

 ---> Using cache
 ---> ef6e4b024d11
Step 3/3 : RUN chmod +x /usr/local/bin/install-php-extensions &&     install-php-extensions xdebug-^3
 ---> Running in e24273431c88
install-php-extensions v.1.2.60
### INSTALLING REMOTE MODULE xdebug ###
  (installing version 3.1.0beta2)

In Pickle.php line 81:
                                                                             
  http error while loading information for xdebug-3.1.0beta2: unknown error  
                                                                             

install [--no-convert] [--defaults] [--source] [--with-configure-options WITH-CONFIGURE-OPTIONS] [--save-logs SAVE-LOGS] [--dry-run] [--php PHP] [--ini INI] [--tmp-dir TMP-DIR] [--version-override [VERSION-OVERRIDE]] [--] [<path>]

Error response from daemon: The command '/bin/sh -c chmod +x /usr/local/bin/install-php-extensions &&     install-php-extensions xdebug-^3' returned a non-zero code: 1
Failed to deploy '<unknown> Dockerfile: tests/Dockerfile': Can't retrieve image ID from build stream
</details>

**Comment by mlocati** [comment]
I think it it's an error of pickle, not of my script.

For example, this works:

```sh
$ install -v --dry-run --no-interaction xdebug-3.0.4
  - Installing xdebug (3.0.4): Downloading (100%)
 Extracting archive+-----------------------------------+--------+
| Package name                      | xdebug |
| Package version (current release) | 3.0.4  |
| Package status                    | stable |
+-----------------------------------+--------+
```

but this doesn't:

```sh
$ pickle install -v --dry-run --no-interaction xdebug-3.1.0beta2

In Pickle.php line 81:

  [Exception]
  http error while loading information for xdebug-3.1.0beta2: unknown error


Exception trace:
  at phar:///tmp/pickle/src/Package/Convey/Command/Pickle.php:81
 Pickle\Package\Convey\Command\Pickle->fetchPackageJson() at phar:///tmp/pickle/src/Package/Convey/Command/Pickle.php:96
 Pickle\Package\Convey\Command\Pickle->prepare() at phar:///tmp/pickle/src/Base/Abstracts/Package/Convey/Command.php:62
 Pickle\Base\Abstracts\Package\Convey\Command->__construct() at phar:///tmp/pickle/src/Package/Convey/Command/Factory.php:54
 Pickle\Package\Convey\Command\Factory::getCommand() at phar:///tmp/pickle/src/Package/Convey.php:56
 Pickle\Package\Convey->__construct() at phar:///tmp/pickle/src/Console/Helper/PackageHelper.php:119
 Pickle\Console\Helper\PackageHelper->convey() at phar:///tmp/pickle/src/Console/Command/InstallerCommand.php:217
 Pickle\Console\Command\InstallerCommand->execute() at phar:///tmp/pickle/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///tmp/pickle/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at phar:///tmp/pickle/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at phar:///tmp/pickle/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at phar:///tmp/pickle/bin/pickle:38
 require() at /tmp/pickle:10

install [--no-convert] [--defaults] [--source] [--with-configure-options WITH-CONFIGURE-OPTIONS] [--save-logs SAVE-LOGS] [--dry-run] [--php PHP] [--ini INI] [--tmp-dir TMP-DIR] [--version-override [VERSION-OVERRIDE]] [--] [<path>]
```

**Comment by mlocati** [comment]
See https://github.com/FriendsOfPHP/pickle/issues/242
