### ISSUE TITLE
Support for SourceGuardian loader

### ISSUE THREAD

**Issue by drpayyne** [mlocati/docker-php-extension-installer#438]
Just like Ioncube loader, the SourceGuardian loader could be added to this repo too as it is very useful and used in many PHP projects.

link: https://www.sourceguardian.com/loaders.html

I'm creating this issue to track this and I will look into checking how I myself can contribute this in a PR, but if anyone wants to take this, please feel free to.

**Comment by mlocati** [comment]
See #442

**Comment by drpayyne** [comment]
Thank you! Could you please check https://github.com/mlocati/docker-php-extension-installer/issues/439#issuecomment-929028862? I think it's relevant to this.
