### ISSUE TITLE
fetching APKINDEX.tar.gz fails

### ISSUE THREAD

**Issue by ad-on-is** [mlocati/docker-php-extension-installer#441]
I'm running this script in a CI/CD pipeline, and for the past few days I'm getting this error:

install-php-extensions v.1.2.61
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
ERROR: Job failed: execution took longer than 1h0m0s seconds

**Comment by mlocati** [comment]
It's a network issue: the apk command can't contact the Alpine Linux CDN website.

Check your environment.
