### ISSUE TITLE
Missing CMakeLists.txt.

### ISSUE THREAD

**Issue by pandarhys** [mlocati/docker-php-extension-installer#458]
Hi

I'm getting the following, I'm trying to install the GD library after upgrading my php version.

#13 123.9 -- Installing: /usr/include/libyuv/video_common.h
#13 123.9 Installing libavif
#13 128.9 curl: (6) Could not resolve host: codeload.github.com
#13 128.9 unzip: short read
#13 128.9 CMake Error: The source directory "/tmp/src/tmp.afcPLE" does not appear to contain CMakeLists.txt.
#13 128.9 Specify --help for usage, or press the help button on the CMake GUI.

php config

FROM php:8.1.0RC5-fpm-alpine

RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini && \
        sed -i -e "s/^ *memory_limit.*/memory_limit = 4G/g" /usr/local/etc/php/php.ini && \
        sed -i -e "s/^ *upload_max_filesize .*/upload_max_filesize  = 4G/g" /usr/local/etc/php/php.ini && \
        sed -i -e "s/^ *post_max_size .*/post_max_size  = 4G/g" /usr/local/etc/php/php.ini

RUN mkdir -p /var/www/html

RUN apk --no-cache add shadow && usermod -u 1000 www-data

RUN docker-php-ext-install pdo pdo_mysql

ADD  https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions imagick

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
install-php-extensions gd

RUN apk --no-cache add shadow && usermod -u 1000 www-data

RUN chown -R www-data:www-data /var/www/html

**Comment by mlocati** [comment]
>  curl: (6) Could not resolve host: codeload.github.com

This seems a network connection issue

**Comment by pandarhys** [comment]
> gith

Hi

It only seems to happen on php:8.1.0RC5-fpm-alpine and php:8.1-rc-fpm-alpine. No issue on php:7.4.12-fpm-alpine but I need to use php 8.

**Comment by mlocati** [comment]
I'm sorry that's not something under the control of the `install-php-extensions`.
To check for possible network issues you can try to run this command:

```sh
curl -I https://codeload.github.com/AOMediaCodec/libavif/tar.gz/refs/tags/v0.9.2
```

And it's working for me with both `php:8.1.0RC5-fpm-alpine` and `php:8.1-rc-fpm-alpine` - here's a sample session:

```
$ docker run --rm -it php:8.1-rc-fpm-alpine sh

# curl -I https://codeload.github.com/AOMediaCodec/libavif/tar.gz/refs/tags/v0.9.2

HTTP/2 200
access-control-allow-origin: https://render.githubusercontent.com
content-disposition: attachment; filename=libavif-0.9.2.tar.gz
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: application/x-gzip
etag: "b18c75b591fb8c1fe764696cd1accc49c70b6bfe00a88903337c17e127e06202"
strict-transport-security: max-age=31536000
vary: Authorization,Accept-Encoding,Origin
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
date: Tue, 02 Nov 2021 13:50:24 GMT
x-github-request-id: F043:9503:1FE50E:26E58A:61814220
```

(please remark the [`200`](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#200) in the first line)

**Comment by pandarhys** [comment]
> I'm sorry that's not something under the control of the `install-php-extensions`. To check for possible network issues you can try to run this command:
> 
> ```shell
> curl -I https://codeload.github.com/AOMediaCodec/libavif/tar.gz/refs/tags/v0.9.2
> ```
> 
> And it's working for me with both `php:8.1.0RC5-fpm-alpine` and `php:8.1-rc-fpm-alpine` - here's a sample session:
> 
> ```
> $ docker run --rm -it php:8.1-rc-fpm-alpine sh
> 
> # curl -I https://codeload.github.com/AOMediaCodec/libavif/tar.gz/refs/tags/v0.9.2
> 
> HTTP/2 200
> access-control-allow-origin: https://render.githubusercontent.com
> content-disposition: attachment; filename=libavif-0.9.2.tar.gz
> content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
> content-type: application/x-gzip
> etag: "b18c75b591fb8c1fe764696cd1accc49c70b6bfe00a88903337c17e127e06202"
> strict-transport-security: max-age=31536000
> vary: Authorization,Accept-Encoding,Origin
> x-content-type-options: nosniff
> x-frame-options: deny
> x-xss-protection: 1; mode=block
> date: Tue, 02 Nov 2021 13:50:24 GMT
> x-github-request-id: F043:9503:1FE50E:26E58A:61814220
> ```
> 
> (please remark the [`200`](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#200) in the first line)

Thank you, I will try this tonight, for now I've rolled back PHP version and its working. Must be something wrong with my docker-compose set up. It only dislikes gd. Thank you again for you patience.
