### ISSUE TITLE
Support Openswoole?

### ISSUE THREAD

**Issue by madalinignisca** [mlocati/docker-php-extension-installer#459]
Hi. There are 2 swoole extensions. I'm still confused with what is actually happening with it's community, but from my perspective, Openswoole looks like to be the official. Can you add openswoole please?

**Comment by mlocati** [comment]
> I'm still confused with what is actually happening with it's community

Here's why: https://news-web.php.net/php.pecl.dev/17446

Basically @matyhtf added to the swoole extension [this code](https://github.com/swoole/swoole-src/blob/372fdb824a91173bfe4892b3a75e4662473b64d3/ext-src/php_swoole_library.h#L7261-L7285) that downloads a tar.gz from a server (`business.swoole.com`, resolving to 118.25.177.99 at the moment, [located in China](https://www.ip2location.com/demo/118.25.177.99)), and injected its code into the web server.
@doubaokun asked @matyhtf to remove that code (in an offensive way), @matyhtf refused to do it and [revoked write access](https://github.com/swoole/swoole-src/issues/4434#issuecomment-942805782) for @doubaokun.

So @doubaokun created the openswoole alternative extension.
