### ISSUE TITLE
pthreads on 7.2

### ISSUE THREAD

**Issue by alexjeen** [mlocati/docker-php-extension-installer#477]
Hi there,

Thanks for your library, makes my life a lot easier :)

I was wondering why pthreads is not available? On both Alpine and Debian I am able to install it (when zts is enabled):

    RUN curl -sSL https://github.com/krakjoe/pthreads/archive/master.zip -o /tmp/pthreads.zip \
    && unzip /tmp/pthreads.zip -d /tmp \
    && cd /tmp/pthreads-* \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && rm -rf /tmp/pthreads*

**Comment by mlocati** [comment]
You should ask the pthreads maintainers to publish a new release on pecl which is compatible with  PHP 7.2

**Comment by alexjeen** [comment]
You are 100% right, maybe, it makes sense for these versions (and PHP 8.0) to install this fork: https://github.com/pmmp/pthreads
