### ISSUE TITLE
[feature] Install symfony-cli

### ISSUE THREAD

**Issue by gander** [mlocati/docker-php-extension-installer#489]
Allow installation binaries of https://github.com/symfony-cli/symfony-cli/releases

**Comment by mlocati** [comment]
I'm not going to provide support for specific vendor tools

**Comment by gander** [comment]
composer and only composer?

**Comment by mlocati** [comment]
> composer and only composer?

composer is used by many projects, non only symfony ones.
This project is already complex enough, I really don't have time to support custom tools for symfony, laravel, doctrine, concretecms, typo3, joomla, drupal, whatever...
