### ISSUE TITLE
Building extension from source

### ISSUE THREAD

**Issue by ruudk** [mlocati/docker-php-extension-installer#493]
First of all, thanks for this amazing utility. It makes installing PHP extensions a breeze. 😍 

I would like to request a feature: allow building some extensions from source.

For example, the [setup-php GitHub Action](https://github.com/shivammathur/setup-php) allows passing a list of extensions like this:
```yaml
with:
    extensions: gd,redis-5.3.5,memcached-php-memcached-dev/php-memcached@d3b8ce13f13cee3017aa8a00a0cfb2e7709154d8
````

As you can see, `memcached` is installed from `php-memcached-dev/php-memcached` with commit `d3b8ce13f13cee3017aa8a00a0cfb2e7709154d8`. 

Is this something that can be added at some point?

**Comment by mlocati** [comment]
I guess we can add support for this. I'll try to take a look at that when I have some spare time

**Comment by ruudk** [comment]
@mlocati Would be great if you could accept one time donations :)

**Comment by mlocati** [comment]
> @mlocati Would be great if you could accept one time donations :)

That's already possible :wink:

1. Click the `Sponsor` button
   ![immagine](https://user-images.githubusercontent.com/928116/148797675-3288fcdb-a6eb-4359-89f3-554b3c0e903e.png)
2. Click the https://paypal.me/mlocati link
   ![immagine](https://user-images.githubusercontent.com/928116/148797877-ce4275e4-3dee-4216-bc33-47395b9ff9f4.png)

**Comment by ruudk** [comment]
I mean via GitHub. That makes billing easier ;)

**Comment by mlocati** [comment]
> I mean via GitHub. That makes billing easier ;)

When they introduced GitHub Sponsor it was not possible to enable one-time donations, but it seems they enabled it now

**Comment by ruudk** [comment]
@mlocati Great, can you enable it as well then 😊 ?

**Comment by mlocati** [comment]
> can you enable it as well then 😊 ?

Done :wink:

**Comment by ruudk** [comment]
@mlocati Tested, and it works 🍕 🍻

**Comment by mlocati** [comment]
@ruudk Thank you very much for testing!!! 😄

**Comment by mvorisek** [comment]
I am interested in this feature as well. I would welcome also an option to specify local path of the source. It should be easy to implement.

Then it would be possible to checkout a source from GH, but as almost all non-local sources are on GH, I would still welcome a native GH support.

**Comment by mlocati** [comment]
What about https://github.com/mlocati/docker-php-extension-installer/pull/538?
