### ISSUE TITLE
`libavif` build slows `gd` ext install 37x, install using package manager

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#514]
### Version of install-php-extensions

1.4.16 / latest

### Error description

see https://github.com/php/php-src/issues/8118

`gd` ext install is 37x slower since PHP 8.1
and more than doubles the total Docker image build time

### Expected state

I would expect the `libavif` (and `libavif-dev` for build) installed using package manager which should be much faster than building it during the `gd` ext install.

**Comment by mlocati** [comment]
You can use the `IPE_GD_WITHOUTAVIF` env var: https://github.com/mlocati/docker-php-extension-installer#configuration

**Comment by mvorisek** [comment]
Yes, thanks, but if the libs can be installed via apt/apk, why are they built at all?

**Comment by mlocati** [comment]
Because they are buggy: https://bugs.php.net/bug.php?id=81217

**Comment by mvorisek** [comment]
Thanks for the link.

According https://bugs.launchpad.net/ubuntu/+source/libavif/+bug/1943658#yui_3_10_3_1_1645286820496_284 `libavif` v0.9.3-2 or newer is needed

Debian support https://packages.debian.org/bullseye-backports/libavif-dev
Ubuntu support/changelog https://launchpad.net/ubuntu/+source/libavif/+changelog
Alpine support https://pkgs.alpinelinux.org/package/edge/community/x86_64/libavif-dev

**Comment by mvorisek** [comment]
fixed: https://github.com/mlocati/docker-php-extension-installer/pull/653
