### ISSUE TITLE
Release v1.4.16 introduced BC break for sqlsrv ext

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#515]
### Version of install-php-extensions

1.4.16

### Error description

see https://github.com/mlocati/docker-php-extension-installer/pull/512#issuecomment-1047133374

I did a few experiments and the v1.4.16 has broken all CI pipelines /w MSSQL.

Even revert of https://github.com/mvorisek/image-php/commit/73116867fc873f465354b930aea9537e4d25d880 did not fix the issue. The only fix for us was a downgrade to v1.4.15.

I belive such issue can be prevent in the future /w real DB testing, here is an example how to start such services for GH actions: https://github.com/atk4/data/blob/4e6cc944c6eaadab1bc63c902dabbb7e7a48f8bb/.github/workflows/test-unit.yml#L91-L116

### Docker image

any

**Comment by mvorisek** [comment]
Closing as the BC break is introduced by ODBC Driver 18.0 [1] release and such upgrade must be done sooner or later.

[1] https://techcommunity.microsoft.com/t5/sql-server-blog/odbc-driver-18-0-for-sql-server-released/ba-p/3169228

**Comment by mlocati** [comment]
Thanks for inspecting the issue!
