### ISSUE TITLE
'Unzip' command unknown - when installing 'zip' extension

### ISSUE THREAD

**Issue by Kaapiii** [mlocati/docker-php-extension-installer#52]
On my dev docker image I install the following php extensions (simplified Dockerfile):

```docker
FROM php:7.2-fpm
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions \
    && sync \
    && install-php-extensions --cleanup \
    gd exif imagick zip mcrypt ldap intl gettext odbc pdo_mysql pdo_pgsql 
    pdo_sqlsrv sqlsrv redis opcache apcu imap bcmath xdebug
```

If I create e new concrete5 project inside the container with: 
"`docker-compose exec php72-fpm bash -c "composer create-project -n concrete5/composer .`"

Composer/PHP shows the following warning. See **As there is no 'unzip' command installed zip files ....** (From line 2:)
```bash
Installing concrete5/composer (v1.1.9)
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing concrete5/composer (v1.1.9): Downloading (100%)         
Created project in .
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

**Comment by mlocati** [comment]
That warning is unrelated to `docker-php-extension-installer`: it simply says that docker can't find the `unzip` command, so it's using the PHP zip extension (which is correctly installed by `install-php-extensions`).
You have 2 options: ignore this warning, or install the `unzip` command (with `apt update && apt install -y unzip`).

**Comment by Kaapiii** [comment]
OK. Thanks
