### ISSUE TITLE
Ext must be checked before enable/install

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#520]
### Version of install-php-extensions

latest

### Error description

In some cases, ext might be built successfully, but fail to start.

`docker-php-extension-installer` must run command like `php -d display_startup_errors=1 -d display_errors=1 -d error_reporting=32767 -d extension=xxx -r "echo 'test';"` before the ext is to be enabled/installed and if any warning like:
```
Warning: PHP Startup: Unable to load dynamic library 'oci8.so' (tried: /usr/local/lib/php/extensions/
no-debug-non-zts-20210903/oci8.so (...) in Unknown on line 0
```

is printed install must be interrupted, eg. ext ini file must not be written.

This behaviour is important so `docker-php-extension-installer xxx || echo "install failed"` fails, but the php can still start without any warnings.

**Comment by mlocati** [comment]
We already check if an extension is built successfully AND if it gets loaded correctly in the tests:

https://github.com/mlocati/docker-php-extension-installer/blob/1.4.17/scripts/check-installed-extension.php#L30

**Comment by mlocati** [comment]
In order to understand what's going wrong for you please provide the relevant part of your Dockerfile

**Comment by mvorisek** [comment]
https://github.com/mvorisek/image-php/blob/9b1a5805c54a1643813c2b9e37d186a052090598/data/8.2-alpine/Dockerfile

here I **try** to install unsupported xdebug on PHP 8.2

https://github.com/mvorisek/image-php/blob/9b1a5805c54a1643813c2b9e37d186a052090598/test.php run by simple command: `php test.php` fails with:

```
 ERROR - missing xdebug configuration: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
```
https://github.com/mvorisek/image-php/runs/5439137054?check_suite_focus=true#step:5:168

`docker-php-extension-installer` must run some simple php command with startup errors reporting enabled (see desc above) prior writing any configuration, otherwise php can be easily left in non-working state

**Comment by mvorisek** [comment]
this can be probably implemented in https://github.com/mlocati/docker-php-extension-installer/blob/c14bd17/install-php-extensions#L1293

if any ext install will corrupt the php, the newly written configuration must be reverted and non-zero exit code must be set

**Comment by mvorisek** [comment]
@mlocati after a lot of work I have been able to prebuilt base image for easy reproduction:

```
FROM ghcr.io/mvorisek/image-php:81git-zts-alpine-base as basic

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions bcmath
RUN php -r 'print_r(array_intersect(get_loaded_extensions(), ["bcmath", "Zend OPcache"]));'
RUN install-php-extensions opcache
RUN php -r 'print_r(array_intersect(get_loaded_extensions(), ["bcmath", "Zend OPcache"]));'
```

output:
```
...

Step 4/6 : RUN php -r 'print_r(array_intersect(get_loaded_extensions(), ["bcmath", "Zend OPcache"]));'
 ---> Running in cc4eda12242a
Array
(
    [32] => bcmath
)
Removing intermediate container cc4eda12242a

...

 Step 6/6 : RUN php -r 'print_r(array_intersect(get_loaded_extensions(), ["bcmath", "Zend OPcache"]));'
 ---> Running in 909731e804b6

Warning: Failed loading Zend extension 'opcache.so' (tried: /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so (Error relocating /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so: _tsrm_ls_cache: initial-exec TLS resolves to dynamic definition in /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so), /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so.so: No such file or directory)) in Unknown on line 0
Array
(
    [32] => bcmath
)
Removing intermediate container 909731e804b6

...
```

both bcmath and opcache ext builds pass, but notice the php startup warning

the issue is broken ABI of the ext when compiled /w ZTS support on Alpine, this is known issue and I do not report it here

what I report is the `docker-php-extension-installer` unsafe behaviour, the installer must run some simple php command with startup errors reporting enabled (see desc above) and assert there are no warnigs/errors prior writing any configuration, otherwise php can be easily left in a broken state

this can be probably implemented in https://github.com/mlocati/docker-php-extension-installer/blob/c14bd17/install-php-extensions#L1293

the expected output is non-zero exit code & no php ini configuration written

**Comment by mvorisek** [comment]
@mlocati can you please keep this issue open?

**Comment by mlocati** [comment]
I've implemented this check in #533, but only for "remote" PHP modules (that is, all the modules except the [bundled ones](https://github.com/php/php-src/tree/master/ext)).

Implementing it for the bundled modules is rather complex because:
1. those modules [are compile](https://github.com/mlocati/docker-php-extension-installer/blob/1.4.24/install-php-extensions#L2122) using `docker-php-ext-install`
2. `docker-php-ext-install` [automatically "enables"](https://github.com/docker-library/php/blob/f2754514dafb2fa33d1b4cd7a152a35bacebf95f/docker-php-ext-install#L119) the installed extensions

So, in order to check the compiled extensions, we'd need to disable these extensions, check if they can be loaded, then re-enable them.
But enabling and disabling extensions is not so easy.

So. in #534 I simply check if, after installing a bundled extension, PHP keeps running fine.

**Comment by mlocati** [comment]
For example, using your [sample case](https://github.com/mlocati/docker-php-extension-installer/issues/520#issuecomment-1060498677), the command `install-php-extensions opcache` would

1. print this error:
   ```
   PHP has problems after installing the "opcache" extension:
   
   Warning: Failed loading Zend extension 'opcache.so' (tried: 
   /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so (Error relocating
   /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so: _tsrm_ls_cache: initial-exec TLS resolves
   to dynamic definition in /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so),
   /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so.so (Error loading shared library
   /usr/local/lib/php/extensions/no-debug-zts-20210902/opcache.so.so: No such file or directory)) in
   Unknown on line 0
   ```
2. return a non-zero exit code (so the docker build process should abort as expected)

**Comment by mvorisek** [comment]
> enabling and disabling extensions is not so easy.

My usecase for this issue is to use the installer for php-src devel like `install-php-extensions opcache || echo "opcache install failed"` and continue with other CI tasks.

If the check from #534 fails, then the installer should not left php unusable.

Even there is no `docker-php-ext-disable`, the "enable" ini files have a deterministic name:
https://github.com/docker-library/php/blob/f2754514dafb2fa33d1b4cd7a152a35bacebf95f/docker-php-ext-enable#L111

if the install check fails, can the enabling ini file be simply renamed to something like `.ini-disabled`?

**Comment by mlocati** [comment]
See https://github.com/mlocati/docker-php-extension-installer/pull/536
