### ISSUE TITLE
`pdo_oci` config.m4 checks are always false on Alpine

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#523]
### Version of install-php-extensions

latest

### Error description

On Alpine images, all `pdo_oci` config.m4 checks are always false:

```
checking if we're at 64-bit platform... yes
checking Oracle version... 21.1
checking for oci.h... /usr/lib/oracle/21.1/client64/lib/sdk/include
checking for OCIEnvCreate in -lclntsh... no
checking for OCIEnvNlsCreate in -lclntsh... no
checking for OCIStmtFetch2 in -lclntsh... no
checking for PDO includes... /usr/local/include/php/ext
```
source: https://github.com/mvorisek/image-php/runs/5451037385?check_suite_focus=true#step:4:3978

but on Debian images, these checks are non-false:
```
checking if we're at 64-bit platform... yes
checking Oracle version... 21.1
checking for oci.h... /usr/lib/oracle/21.1/client64/lib/sdk/include
checking for OCIEnvCreate in -lclntsh... yes
checking for OCIEnvNlsCreate in -lclntsh... yes
checking for OCIStmtFetch2 in -lclntsh... yes
checking for PDO includes... /usr/local/include/php/ext
```
source: https://github.com/mvorisek/image-php/runs/5451038354?check_suite_focus=true#step:4:3293

the usage of this installer is like:
```
install-php-extensions pdo_oci
```

if the config.m4 checks are false, multibyte support is broken

as the Oracle Instant Client libs are installed the same on both platforms, I expect the config.m4 checks to be the same too (same on Alpine as on Debian)

maybe something needs to be added to the PATH on Alpine

### Docker image

see desc

**Comment by mlocati** [comment]
I guess it's a question that should be asked to the PHP maintainers...

**Comment by mvorisek** [comment]
@mlocati is it possible to build the OCI lib with always with `HAVE_OCISTMTFETCH2`? We know what OCI libs we download, so it will be always correct.

**Comment by mlocati** [comment]
We can't define `HAVE_OCISTMTFETCH2` manually: it's [defined by the `config.m4` file](https://github.com/php/php-src/blob/php-8.2.5/ext/pdo_oci/config.m4#L178).

What `config.m4` does? It tries to compile a simple program containing the `OCIStmtFetch2` function by linking to the `clntsh` library: if it suceedes, `HAVE_OCISTMTFETCH2` is defined to `1`.
If it fails, that means that `clntsh` can't be found: if we maually patch `config.m4` to always define `HAVE_OCISTMTFETCH2`, the compilation of the PHP extension would fail because the `clntsh` library won't be found.

I'm going to check why the `clntsh` library can't be found.

**Comment by mvorisek** [comment]
It seems the LD fix for Alpine is not complete or some extra dep needs to be installed.

In https://github.com/mvorisek/image-php I fixed this by `sed -E 's~#if HAVE_OCILOBREAD2$~#if 1~' -i ext/pdo_oci/oci_statement.c`. The https://github.com/php/php-src/blob/PHP-8.2.6/ext/pdo_oci/tests/bug60994.phpt test passes then even on Alpine... But I am not sure if this hotpatching can/should be done in the installer itself as this does not address the reason and can change anytime.

**Comment by mvorisek** [comment]
@mlocati let's please fix this issue by patching the ext for Alpine using this command:

```
sed -E 's~#if HAVE_OCILOBREAD2$~#if 1~' -i ext/pdo_oci/oci_statement.c
```

In https://github.com/mvorisek/image-php/blob/8d6cedaf0c/make.php#L323 I have been using it for more than a year and no issues were reported. It fixed https://github.com/php/php-src/issues/8197 well.

For Debian no patch is needed as `#if HAVE_OCILOBREAD2` is working, but for Alpine, the patch is needed in order to support large strings (they are corrupted otherwise - related PR https://github.com/atk4/data/pull/974 containing a testcase).
