### ISSUE TITLE
Configure GD on buster

### ISSUE THREAD

**Issue by gisostallenberg** [mlocati/docker-php-extension-installer#53]
To configure GD on Debian Buster or PHP 7.4 the arguments should be different, see https://github.com/php/php-src/blob/07fc0764d1ca33bc9a7e5ccb0506f835827c402a/UPGRADING#L746

The arguments on https://github.com/mlocati/docker-php-extension-installer/blob/e6288d0a1d3f6d80e1edd236f2712c6793a4ec0c/install-php-extensions#L333 and
https://github.com/mlocati/docker-php-extension-installer/blob/e6288d0a1d3f6d80e1edd236f2712c6793a4ec0c/install-php-extensions#L335 should be
`docker-php-ext-configure gd --enable-gd --with-webp --with-jpeg --with-xpm --with-freetype`

**Comment by gisostallenberg** [comment]
It turns out zip has to be configured using `docker-php-ext-configure zip` instead of `docker-php-ext-configure zip --with-libzip`

**Comment by mlocati** [comment]
@gisostallenberg thanks for the report. I checked all the extensions with 7.4.0RC3 (see [here](https://travis-ci.org/mlocati/docker-php-extension-installer/builds/596183959) and [here](https://travis-ci.org/mlocati/docker-php-extension-installer/builds/596209984)), but it seems that it was too early.

I'm going to check all the extensions locally, and send a pull request to fix the issues with PHP 7.4.0.

**Comment by gisostallenberg** [comment]
@mlocati I tested some more and it turns out to be related to PHP 7.4 only and not to buster. So using 7.3 on buster, your script works fine.
Thanks for this script which normally makes life easier!

**Comment by mlocati** [comment]
I tested locally all the [supported extensions](https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions) for PHP 7.4, and only GD and ZIP have problems.
I'll fix them in #54

**Comment by mlocati** [comment]
@gisostallenberg now the script should correctly install the GD & ZIP extensions on PHP 7.4.

**Comment by gisostallenberg** [comment]
Thanks you so much for your active support and quick help!
