### ISSUE TITLE
Support solr with PHP 8.1

### ISSUE THREAD

**Issue by mlocati** [mlocati/docker-php-extension-installer#549]
Their master branch should be ok: we just need that they publish a new version (keep an eye on https://pecl.php.net/package-changelog.php?package=solr for a version greater than 2.5.1)

**Comment by xmacaba** [comment]
Version 2.6.0 released on 2022-11-09.
https://pecl.php.net/package/solr/2.6.0

**Comment by mlocati** [comment]
Already fixed by #656
