### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by BrekiTomasson** [mlocati/docker-php-extension-installer#55]
Just a quick question, rather than a trouble ticket. Are there any plans to support Alpine distros in the future? The biggest difference has to do with installing prerequisites - it uses `apk add` instead of `apt-get install`, basically.

**Comment by mlocati** [comment]
Well, I'm not sure that what actually changes is only the name of the command, but also the packaged and where they are stored.
BTW, yes, I think that it'd be really great, and it's already in my to do list. I only have to find the time to do that

**Comment by mlocati** [comment]
@BrekiTomasson #56 is ready to be merged.
This night I'll execute a script that will check all the supported extensions for PHP 5.6&rarr;7.4 (on Alpine and on Debian).
If everything is ok, I'll merge that pull request, and you'll be able to use the `install-php-extensions` script on Alpine docker images.
As you can see in that PR, it required *a bit* more work than replacing `apt-get install` with `apk add `:wink:
