### ISSUE TITLE
`package.xml` should not be required when installing from source

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#558]
https://github.com/mlocati/docker-php-extension-installer/pull/538 added support to install from source. Thank you!

currently, this installer relies on `package.xml` file present which is too strict, as some packages like xdebug update this file only for PECL release, but not in source/GH

xdebug example:

https://github.com/xdebug/xdebug/blob/master/package.xml#L45-L48

```
 <version>
  <release>3.0.4</release>
  <api>3.0.4</api>
 </version>
```

and https://github.com/xdebug/xdebug/blob/master/package.xml#L196-L199
```
   <php>
    <min>7.2.0</min>
    <max>8.0.99</max>
   </php>
```

however the source does support PHP up to 8.2.99 (in theory, 8.1.4 tested) and all in-code versions are set to `3.2.0-dev` (https://github.com/xdebug/xdebug/blob/master/php_xdebug.h#L21)

Repro code:

run
```
install-php-extensions xdebug/xdebug@7b4fcfe6ae300e272113fa612d64b19815bece80
```
on any PHP 8.1 image

it fails currently as the version constraints from `package.xml` from the source are checked:

```
### INSTALLING REMOTE MODULE xdebug ###
  (installing version 3.0.4 from /tmp/src/tmp.UtGaCHipVj/xdebug-7b4fcfe6ae300e272113fa612d64b19815bece80)
pecl/xdebug requires PHP (version >= 7.2.0, version <= 8.0.99), installed version is 8.1.4
No valid packages found
install failed
```

Expected behaviour:

when installing from source, `package.xml` file should be completely ignored, this file is solely for PECL distribution (and not used by php build/module nor available in bundled modules)

**Comment by mlocati** [comment]
So, how could the script know which package and which version ot is going to be installed? These are information of5en required to correctly build the package.

**Comment by mvorisek** [comment]
the name seems to be reliably parseable from `config.m4` (`config.m4.in`) where is always a `PHP_NEW_EXTENSION` entry incl. possible ext deps defined by `PHP_ADD_EXTENSION_DEP`

but the version is not available until the ext is compiled in global `ZEND_EXT_API zend_extension zend_extension_entry`

for now, I am closing this issue, in the future, we might consult it with the php core guys, but I doubt there is a better way to parse the version /wo at least expanding C macros in all files

**Comment by mvorisek** [comment]
Here is minimal `package.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<package version="1.0">
 <name>pdo_sqlsrv</name>
 <summary>Microsoft Drivers for PHP for SQL Server (PDO_SQLSRV)</summary>
 <description>x</description>
 <license>MIT</license>
 <maintainers>
  <maintainer>
   <user>davidengel</user>
   <name>David Engel</name>
   <email>davidengel@microsoft.com</email>
   <role>lead</role>
  </maintainer>
 </maintainers>
 <release>
  <version>5.99.0</version>
  <date>2020-01-01</date>
  <state>stable</state>
  <notes>x</notes>
  <filelist>
   <dir name="/">
   <file name="*" role="src" />
   </dir>
  </filelist>
 </release>
</package>
```

It is based on https://pear.php.net/manual/en/developers.packagedef.intro.php and pdo_sqlsrv pecl `package.xml`. Version `1.0` is better as the required format is less strict.
