### ISSUE TITLE
Installing libsodium

### ISSUE THREAD

**Issue by therool** [mlocati/docker-php-extension-installer#561]
### Version of install-php-extensions

latest

### Error description

Issue installing "libsodium" from https://pecl.php.net/package/libsodium due the pecl package name does not match the compiled extension name and the "getModuleFullPath" generates an error.

To install sodium extension in php7.1 you have to install "libsodium" pecl package which compiles the "sodium.so" extension but the script throws error due it expects that the installed extension would be "libsodium.so" but in this case the pecl package name is different to the compiled extension name.

In previous versions it was possible to bypass this issue by adding the "IPE_DONT_ENABLE=1" flag to the command "IPE_DONT_ENABLE=1 install-php-extensions libsodium" which skipped the "getModuleFullPath" check and then it would be possible to enable the module with "docker-php-ext-enable sodium/docker-php-ext-enable-sodium".

In the meantime instead of using the latest version I am using the version 1.4.15 from https://github.com/mlocati/docker-php-extension-installer/releases/download/1.4.15/install-php-extensions. 

### Docker image

php:7.1-fpm-alpine

### Minimal Dockerfile

```Dockerfile
# add sodium linux library and libsodium php extension
RUN apk add libsodium-dev
RUN IPE_DONT_ENABLE=1 install-php-extensions libsodium
RUN docker-php-ext-enable sodium
```

**Comment by mlocati** [comment]
sodium (or libsodium) was not supported by `install-php-extensions`.

BTW I've just published version 1.5.8 which supports it for PHP 5.6, 7.0 and 7.1.

PS: you won't need the `apk add libsodium-dev` / `docker-php-ext-enable sodium` lines: `install-php-extensions` will do that for you.
