### ISSUE TITLE
PHP 8.1 sodium.so goes missing after extension install

### ISSUE THREAD

**Issue by dnagy** [mlocati/docker-php-extension-installer#564]
### Version of install-php-extensions

v.1.5.8

### Error description

I will try to explain this issue to my best knowledge, please let me know if you need further information.
I have encountered a strange issue. When building a Dockerfile based on a `PHP 8.0` image, everything goes well. Sodium is already included in the image and after installing further extensions, everything is fine.
However if I do the same thing with a `PHP 8.1` image, after installing the extensions, `sodium.so` goes missing. I have included the relevant steps to reproduce this issue for you.

I have tried to include sodium in the extensions to be installed, however it says that sodium is already installed. It's strange that it does not say the same thing about opcache, which is also included in the base image, instead it's just rebuilding it.

To make things a bit weirder, the issue is not present on my desktop computer, only on a server I'm using. I would suspect that the issue might be due to the docker version difference, but since it's working just fine with `PHP 8.0`, I thought you might have an idea what causes this.

### Docker image

php:8.1.4-apache

### Minimal Dockerfile

```Dockerfile
FROM php:8.0.2-apache
COPY --from=mlocati/php-extension-installer:1.5.8 /usr/bin/install-php-extensions /usr/local/bin/
RUN ls -la /usr/local/lib/php/extensions/no-debug-non-zts-20200930
RUN install-php-extensions intl opcache
RUN ls -la /usr/local/lib/php/extensions/no-debug-non-zts-20200930

FROM php:8.1.4-apache
COPY --from=mlocati/php-extension-installer:1.5.8 /usr/bin/install-php-extensions /usr/local/bin/
RUN ls -la /usr/local/lib/php/extensions/no-debug-non-zts-20210902
RUN install-php-extensions intl opcache
RUN ls -la /usr/local/lib/php/extensions/no-debug-non-zts-20210902
```

**Comment by mlocati** [comment]
I've tried to replicate the issue with no luck, both on my PC and on GitHub Actions (see [this code](https://github.com/mlocati/test/blob/326bae665c20ba1ff6d625d31172d2344e06a739/.github/workflows/test.yml) and [its output](https://github.com/mlocati/test/runs/6003604841)).
If I can't replicate the issue I can't understand what's going wrong...

**Comment by dnagy** [comment]
I'm sorry for the late response, I was investigating our infrastructure based on you response. It turned out that our build server had a very strange issue which for some reason only affected one version of PHP. I'm really sorry for taking your time and I really appreciate that you tried to help!
