### ISSUE TITLE
Option to download extensions from PECL by http

### ISSUE THREAD

**Issue by hustlahusky** [mlocati/docker-php-extension-installer#583]
Hello, @mlocati. I faced another networking issue: sometimes server unable to connect to https://pecl.php.net/, so pickle cannot download extensions. Weird thing is that problem arises only with https requests, but server still able to establish connection using http.

So I've done a PR to pickle FriendsOfPHP/pickle#257, that allows to download extensions using http with `PICKLE_PECL_UNSAFE` environment variable. I also saw that you've done a lot of contributions to pickle over last time, I hope you can review and merge my PR. Or maybe you could provide a way to use custom build of pickle in `install-php-extensions`.

**Comment by mlocati** [comment]
It's a pickle related issue, so I'm closing this issue.
