### ISSUE TITLE
Documentation: List of required external source URLs

### ISSUE THREAD

**Issue by bahag-schlachterk** [mlocati/docker-php-extension-installer#606]
Having a "protected" CI/CD-System (or development system inside a company in general) sitting behind a proxy, it might be necessary to have URLs whitelisted before they can be accessed, causing the builds to fail.

Currently I had to look into the code to find that
https://aomedia.googlesource.com/
was required to be accessible in order to build the gd extension on alpine and php > 7.x
It would be really nice if there was a list of such URLs so we could hand them over to our admins.

**Comment by mlocati** [comment]
It depends on the extensions that you need to install.
First of all, if you have to fetch packages from the PECL repository, you'll need to enable `https://pecl.php.net` (and maybe `http://pecl.php.net`).
Furthermore, the script installs many packages and libraries by fetching their source code from many websites.
You may want to check the list of the packages you need, and check the relevant source code.

The full list of domains that are referred to in the script may be retrieved with this command:

```sh
curl -sSLf -o - https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
  | grep -Eio '(https?|ftp)://[a-z0-9.]+' \
  | sort -u
```

Which, at the moment, results in:

```
http://archive.apache.org
http://pear.php.net
http://pecl.php.net
http://www.xmailserver.org
https://aomedia.googlesource.com
https://blackfire.io
https://bugs.launchpad.net
https://chromium.googlesource.com
https://code.videolan.org
https://codeload.github.com
https://composer.github.io
https://docs.microsoft.com
https://download.microsoft.com
https://download.oracle.com
https://downloads.apache.org
https://downloads.ioncube.com
https://getcomposer.org
https://git.osgeo.org
https://github.com
https://gitlab.alpinelinux.org
https://hub.docker.com
https://jprs.co.jp
https://packages.microsoft.com
https://raw.githubusercontent.com
https://www.bytereef.org
https://www.ioncube.com
https://www.sourceguardian.com
```
