### ISSUE TITLE
xdebug installation fails on 8.x debian (missing lib/php-header.h)

### ISSUE THREAD

**Issue by schmunk42** [mlocati/docker-php-extension-installer#613]
### Version of install-php-extensions

v.1.5.29

### Error description

Build fails in Docker build for `RUN install-php-extensions xdebug`.
With `fatal error: lib/php-header.h: No such file or directory`

See for example https://github.com/yiisoft/yii-docker/runs/7444548717?check_suite_focus=true#step:6:752 - also tested with the command above.

```
2: compilation terminated.
2: make: *** [Makefile:286: src/lib/lib.lo] Error 1
2:  cc -I. -I/tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1 -I/tmp/pickle.tmp/pickle-7f747bef79dcb11e3af9f2d35a5c23574d431cf4/include -I/tmp/pickle.tmp/pickle-7f747bef79dcb11e3af9f2d35a5c23574d431cf4/main -I/tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1/src -I/tmp/pickle.tmp/pickle-7f747bef79dcb11e3af9f2d35a5c23574d431cf4/src -DHAVE_CONFIG_H -g -O2 -DZEND_COMPILE_DL_EXT=1 -c /tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1/src/lib/usefulstuff.c -MMD -MF src/lib/usefulstuff.dep -MT src/lib/usefulstuff.lo  -fPIC -DPIC -o src/lib/.libs/usefulstuff.o
2: make: *** [Makefile:304: src/lib/var.lo] Error 1
2: make: *** [Makefile:262: src/base/base.lo] Error 1
2: /tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1/src/lib/compat.c:42:10: fatal error: lib/php-header.h: No such file or directory
2:    42 | #include "lib/php-header.h"
2:       |          ^~~~~~~~~~~~~~~~~~
2: compilation terminated.
2: make: *** [Makefile:271: src/lib/compat.lo] Error 1
2: /tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1/src/lib/str.c:23:10: fatal error: lib/php-header.h: No such file or directory
2:    23 | #include "lib/php-header.h"
2:       |          ^~~~~~~~~~~~~~~~~~
2: compilation terminated.
2: make: *** [Makefile:298: src/lib/str.lo] Error 1
2: In file included from /tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1/src/lib/usefulstuff.c:33:
2: /tmp/pickle.tmp/xdebug/xdebug-3.2.0alpha1/php_xdebug.h:28:10: fatal error: lib/php-header.h: No such file or directory
2:    28 | #include "lib/php-header.h"
2:       |          ^~~~~~~~~~~~~~~~~~
2: compilation terminated.
2: make: *** [Makefile:268: src/lib/usefulstuff.lo] Error 1The command '/bin/sh -c install-php-extensions         xdebug' returned a non-zero code: 1
```

### Docker image

php:8.x

### Minimal Dockerfile

```Dockerfile
FROM php:8.1-apache
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions \
        xdebug
```

**Comment by CodeCasterNL** [comment]
According to the [docs](https://github.com/mlocati/docker-php-extension-installer), it shouldn't try to install prerelease versions:

> Pre-release versions extensions available on PECL can be setup by suffixing the extension's name with its state i.e. alpha, beta, rc, preview, devel or snapshot. For example:

A workaround until that's fixed:

    install-php-extensions xdebug-^3.1

**Comment by b1rdex** [comment]
Having the same problem with Alpine.
<img width="618" alt="image" src="https://user-images.githubusercontent.com/312855/180251161-a363d455-a332-4229-ba33-ff43fa2e71de.png">

Actually, this is kinda strange, because the version is marked as beta on pecl: 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/312855/180251745-ff1ee8b5-cf38-4f3d-a813-c472be1d2922.png">

For me `install xdebug` that prints `(installing version stable)` should not be installing the beta versions :)

@mlocati, what do you think about the issue?

**Comment by schmunk42** [comment]
@mlocati @CodeCasterNL I tried to modify all extension installations to `-stable`.

But with this image https://github.com/yiisoft/yii2-docker/actions/runs/2718005323 I run into problems for PHP <7.2 now.

Actually either I should be able to install a `stable` version of the extension for all PHP versions.
Or as mentioned by @b1rdex I should explicitly tell the installer that I want a alpha or beta version.

**Comment by schmunk42** [comment]
I am reopening this, please let us know if we should create a new ticket for the issues described above.

**Comment by CodeCasterNL** [comment]
@schmunk42 

> ### INSTALLING REMOTE MODULE mongodb ###
>  (installing version stable)
> pecl/mongodb requires PHP (version >= 7.2.0, version <= 8.99.99), installed version is 7.1.33

That's a different issue AFAIK.

**Comment by schmunk42** [comment]
Yes, but I am stuck there, because I can not build all images from 5.6 to 8.1, due to the fact that for 8.x it tries to install the 3.2alpha.

That's why I followed your advice also there to use `-stable` but this leads to the error you just mentioned.

If I just use it for `xdebug-stable` it still fails below 7.2

**Comment by igoooor** [comment]
Issue is not resolved for me using `php:8.1.8-fpm-alpine3.16`
`RUN install-php-extensions xdebug`
exits with:
```
The command '/bin/sh -c install-php-extensions xdebug' returned a non-zero code: 1
2022-07-22T11:08:12.549574363Z stdout P 2: configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers
```
Do we need to do any extra step to have it working agian?

**Comment by b1rdex** [comment]
@igoooor use `xdebug-stable`

**Comment by igoooor** [comment]
thanks for the quick answer.
Is that a temporary fix, or should I always use `xdebug-stable` from now on?

**Comment by CodeCasterNL** [comment]
> Yes, but I am stuck there, because I can not build all images from 5.6 to 8.1, due to the fact that for 8.x it tries to install the 3.2alpha.
> 
> That's why I followed your advice also there to use `-stable` but this leads to the error you just mentioned.
> 
> If I just use it for `xdebug-stable` it still fails below 7.2, see https://github.com/yiisoft/yii2-docker/runs/7466830525?check_suite_focus=true

So two days ago it used to work? Did it detect the PHP version and according Mongo (and other extension) version or did Mongo recently publish a new version that won't work with PHP < 7.2?

**Comment by b1rdex** [comment]
> thanks for the quick answer. Is that a temporary fix, or should I always use `xdebug-stable` from now on?

@igoooor this issue consist of multiple problems.

1. xdebug alpha release is missing a file: https://github.com/xdebug/xdebug/pull/851 and that's why it errors on install
2. pickle has a bug – it picks not a stable version by default: https://github.com/FriendsOfPHP/pickle/issues/247 (and that's why xdebug-alpha is installed)

If xdebug alpha release had no errors, then you'd silently get an alpha version this thread wouldn't exist at all :D

So this is not a docker-php-extension-installer issue at all. I'll try to dig the problem with pickle.

**Comment by schmunk42** [comment]
> So two days ago it used to work? Did it detect the PHP version and according Mongo (and other extension) version or did Mongo recently publish a new version that won't work with PHP < 7.2?

Yes, these builds went just fine: https://github.com/yiisoft/yii2-docker/actions/runs/2702056407 
(Note: There are ENVs for specific versions, but they are unused AFAIR)

Then, 2 days ago, the 8.x builds broke, due to the alpha version.

**Comment by CodeCasterNL** [comment]
@schmunk42 
Your build (7.1-fpm, debian, 1, -2.9.8) on 2022-07-20 [installed mongodb 1.11](https://github.com/yiisoft/yii2-docker/runs/7421877173?check_suite_focus=true#step:6:3389), which [is PHP 7.1 compatible](https://www.mongodb.com/docs/drivers/php/#language-compatibility).

Build (7.1-fpm, debian, 1, -2.9.8) today [failed](https://github.com/yiisoft/yii2-docker/runs/7466684277?check_suite_focus=true#step:6:3363) with

> pecl/mongodb requires PHP (version >= 7.2.0, version <= 8.99.99), installed version is 7.1.33

This would indicate that it (but which "it"? Pickle?) doesn't properly detect the PHP version in use anymore to determine the extension version to install, and that it tries to install 1.12 or up (which dropped PHP 7.1 support).

**Comment by schmunk42** [comment]
> Build (7.1-fpm, debian, 1, -2.9.8) today [failed](https://github.com/yiisoft/yii2-docker/runs/7466684277?check_suite_focus=true#step:6:3363) with

That's because I also added `-stable` to mongodb, see https://github.com/yiisoft/yii2-docker/commit/844bca2c713da69f0bb792c1298dcc3b6ab57c3f#diff-ed02e61dc347b6860c1d27ec862b61edbaf946278dcf92348a5a1a4a4c05f3f8R59

Because I though that would be the proper way to install a stable version for the installed PHP version.
But it looks to me like it just picks the very latest stable version of the extension and does not care about the PHP version.

**Comment by b1rdex** [comment]
Okay, looks like I figured out the problem with pickle and prepared a fix – https://github.com/FriendsOfPHP/pickle/pull/259
Please review/test it if you have a possibility.

**Comment by mlocati** [comment]
I'm closing this issue, since it's not related to the install-php-extensions (see https://bugs.xdebug.org/view.php?id=2105 and https://github.com/FriendsOfPHP/pickle/issues/247 instead)

**Comment by schmunk42** [comment]
@mlocati Just to understand how things work under the hood...

This needs to be fixed in pickle and/or xdebug itself, right?
If it is fixed, do they need to release a new version so the extension installer will pick up the fix?

**Comment by mlocati** [comment]
The xdebug bug has already been fixed in the latest beta version, but pickle should install the last *stable* version by default.

**Comment by b1rdex** [comment]
> but pickle should install the last _stable_ version by default

I created a PR to fix that, please review when you have time: https://github.com/FriendsOfPHP/pickle/pull/259
