### ISSUE TITLE
Respect / take into account Proxy Settings if given

### ISSUE THREAD

**Issue by bahag-schlachterk** [mlocati/docker-php-extension-installer#615]
I was facing a problem when using the installer to install mcrypt on a more encapsulated system which requires a proxy server to be used.
As this server varies among our landscape, we hand it into the build process by using --build-arg when doing a docker build.

This worked quite well so far, but now failed when trying to install mcrypt.
Everything seemed to work, even the download of external packages required by the build process takes into account these settings if given. It took me a bit of research to fully understand the issue:
The environment variables are not taken into account by pear, which is used to install the mcrypt extension.
Current workaround is to place the following in the Dockerfile:

`RUN pear config-set http_proxy $http_proxy`

If I can find the time I will also create patch/pull request to have this kind of recognition directly built into the extension installer.

**Comment by croensch** [comment]
At least pickle picked up the proxy itself, with V2 / #679 this changed.

**Comment by mlocati** [comment]
Fixed by #692
