### ISSUE TITLE
sqlsrv install failed

### ISSUE THREAD

**Issue by ROG3RB0T** [mlocati/docker-php-extension-installer#616]
### Version of install-php-extensions

install-php-extensions v.1.5.33

### Error description

root@9ee58f084c8a:/var/www/html# install-php-extensions sqlsrv    
install-php-extensions v.1.5.33
#StandWithUkraine
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://deb.debian.org/debian stretch-updates InRelease
Hit:3 http://deb.debian.org/debian stretch Release
Hit:4 http://security.debian.org/debian-security stretch/updates InRelease
Hit:6 https://packages.microsoft.com/debian/9/prod stretch InRelease
Reading package lists...
### MARKING PRE-INSTALLED PACKAGES AS IN-USE ###
unixodbc was already set to manually installed.
### INSTALLING REMOTE MODULE sqlsrv ###
Installing the Microsoft SQL Server ODBC Driver
- installing the Microsoft APT key
OK
- installing the APT package
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package msodbcsql17

### Docker image

php:7.0.33-apache

### Minimal Dockerfile

```Dockerfile
FROM php:7.0.33-apache

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions sqlsrv
```

**Comment by mlocati** [comment]
```
$ curl -sSLf \
  -o /usr/local/bin/install-php-extensions \
  https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions

$ chmod +x /usr/local/bin/install-php-extensions

$ install-php-extensions sqlsrv
install-php-extensions v.1.5.34
#StandWithUkraine
Updating channel "pecl.php.net"
Update of Channel "pecl.php.net" succeeded
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [59.2 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [782 kB]
Get:5 http://deb.debian.org/debian stretch Release [118 kB]
Get:6 http://deb.debian.org/debian stretch Release.gpg [3177 B]
Get:7 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Fetched 8135 kB in 2s (4030 kB/s)
Reading package lists...
### INSTALLING REQUIRED PACKAGES ###
# Packages to be kept after installation: libltdl7 libodbc1 libreadline7 odbcinst odbcinst1debian2 readline-common unixodbc
# Packages to be used only for installation: apt-transport-https gnupg gnupg-agent libassuan0 libcurl3-gnutls libksba8 libltdl-dev libnpth0 pinentry-curses unixodbc-dev
[...omissis...]

$ php --ri sqlsrv

sqlsrv

sqlsrv support => enabled
ExtensionVer => 5.3.0

Directive => Local Value => Master Value
sqlsrv.WarningsReturnAsErrors => On => On
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240
```

Are you sure you are using the `php:7.0.33-apache` image?

**Comment by ROG3RB0T** [comment]
I made a correction in my Dockerfile this way because I'm using a Mac book pro with M1 chip.

FROM --platform=linux/x86_64 php:7.0.33-apache

Thank you for your response
