### ISSUE TITLE
Unable to install extensions on PHP 8.1

### ISSUE THREAD

**Issue by MichaelMackus** [mlocati/docker-php-extension-installer#625]
### Version of install-php-extensions

v.1.5.37

### Error description

The command `install-php-extensions gd intl pdo_mysql opcache zip` is not working in a `php:8.1-fpm` docker container. I checked and each of these extensions appears to be supported for building in PHP 8.1 so I'm not sure the issue.

I get the following output after trying to install the extensions:

`
failed to solve: executor failed running [/bin/sh -c install-php-extensions gd intl pdo_mysql opcache zip]: exit code: 1
`

Along with a bunch of messages like this:

```
#0 111.9 [0/1] Re-running CMake...
#0 111.9 --- aom_configure: Detected CPU: x86_64
#0 112.4 -- Configuring done
#0 112.5 -- Generating done
#0 112.5 -- Build files have been written to: /tmp/src/tmp.vsLIEPDPzl/my.build
#0 112.5 [0/1] Re-running CMake...
#0 112.5 --- aom_configure: Detected CPU: x86_64
#0 113.0 -- Configuring done
#0 113.1 -- Generating done
#0 113.1 -- Build files have been written to: /tmp/src/tmp.vsLIEPDPzl/my.build
#0 113.1 [0/1] Re-running CMake...
#0 113.1 --- aom_configure: Detected CPU: x86_64
#0 113.6 -- Configuring done
#0 113.7 -- Generating done
#0 113.7 -- Build files have been written to: /tmp/src/tmp.vsLIEPDPzl/my.build
#0 113.7 [0/1] Re-running CMake...
#0 113.7 --- aom_configure: Detected CPU: x86_64
#0 114.2 -- Configuring done
#0 114.3 -- Generating done
#0 114.3 -- Build files have been written to: /tmp/src/tmp.vsLIEPDPzl/my.build
#0 114.3 [0/1] Re-running CMake...
#0 114.3 --- aom_configure: Detected CPU: x86_64
#0 114.8 -- Configuring done
#0 114.8 -- Generating done
#0 114.9 -- Build files have been written to: /tmp/src/tmp.vsLIEPDPzl/my.build
#0 114.9 [0/1] Re-running CMake...
#0 114.9 --- aom_configure: Detected CPU: x86_64
#0 115.4 -- Configuring done
#0 115.4 -- Generating done
#0 115.5 -- Build files have been written to: /tmp/src/tmp.vsLIEPDPzl/my.build
```

### Docker image

php:8.1-fpm - same result on php:8.1-cli

### Minimal Dockerfile

```Dockerfile
FROM  php:8.1-fpm

COPY --from=mlocati/php-extension-installer:latest /usr/bin/install-php-extensions /usr/bin/

RUN apt update && apt install git unzip -yq && \
    apt-get clean autoclean; apt-get autoremove --yes; rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN install-php-extensions gd intl pdo_mysql opcache zip
```

**Comment by kdevan** [comment]
I'm getting the same error but different output. 

`failed to solve: executor failed running [/bin/sh -c install-php-extensions @composer pdo_pgsql pgsql igbinary redis xdebug]: exit code: 1`

In my case I'm getting connection timeout trying to connect to https://pecl.php.net. Maybe temporary pecl server issue. Re-running failed on a different extension, so pecl seems to be finicky right now. I've had this working for quite awhile and just ran into this for the first time right now... 

Maybe unrelated since your output messages are different but thought I'd mention.

**Comment by StrangePeanut** [comment]
Same here. Fails at imagick install due to pecl.php.net being down.

**Comment by kdevan** [comment]
Aaaaand pecl is back. If you're still running into this issue then it's a separate issue and i'm sorry for derailing.

**Comment by mlocati** [comment]
> [0/1] Re-running CMake...

This issue has been already [reported multiple times](https://github.com/mlocati/docker-php-extension-installer/issues?q=is%3Aissue+%22Re-running+CMake%22), but since I can't replicate it, I can't fix it.

See also https://github.com/mlocati/docker-php-extension-installer/issues/614#issuecomment-1202846906.

**Comment by StrangePeanut** [comment]
Can confirm everything works fine since pecl.php.net is back up. Since this is a common issue that pops up every so often, perhaps a solution would be to include verified pecl.php.net mirrors if there are any?

**Comment by mlocati** [comment]
> a solution would be to download from mirrors if there are any?

I'm not aware of any official mirror, and for security reasons I wouldn't adopt any unofficial one...

**Comment by cjunge** [comment]
An alternative would be to download and build each extension. This is basically what pecl is doing anyway. The tricky part is handling latest/different versions.

eg:
```
curl -fsSL https://github.com/xdebug/xdebug/archive/refs/tags/$XDEBUG_VERSION.tar.gz -o xdebug.tar.gz \
    && mkdir -p /tmp/xdebug \
    && tar -xf xdebug.tar.gz -C /tmp/xdebug --strip-components=1 \
    && rm xdebug.tar.gz \
    && docker-php-ext-configure /tmp/xdebug --enable-xdebug \
    && docker-php-ext-install /tmp/xdebug \
    && rm -r /tmp/xdebug
```

**Comment by mlocati** [comment]
I'm not going to search where the source code resides for every extension, given also that it may change across time.

**Comment by MichaelMackus** [comment]
Hmm still happening for me... so must be unrelated to the pecl servers. Seems hard to reproduce, I actually got 1 successful build but I need to be able to build this full container. I guess I'll keep trying. Has anybody found any workarounds?

**Comment by MichaelMackus** [comment]
Also, it might help to add more messaging or information on why C-Make is failing... I looked in the log folder but there's not a simple "cmake.log" or anything I could find to specifically add to this issue.

**Comment by 1Jackob1** [comment]
I've got same error only with gd extension and only on docker desktop for windows with wsl 2 backend, may be it wil help to reproduce and fix this error

**Comment by arcanisgk** [comment]
> I've got same error only with gd extension and only on docker desktop for windows with wsl 2 backend, may be it wil help to reproduce and fix this error

i have use it:

```bash
RUN install-php-extensions pdo_mysql
RUN install-php-extensions Reflection
RUN install-php-extensions session
RUN install-php-extensions SimpleXML
RUN install-php-extensions SPL
RUN install-php-extensions sqlite3
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions gd
RUN install-php-extensions curl
RUN install-php-extensions imap
RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl
RUN IPE_ICU_EN_ONLY=1 install-php-extensions http
RUN install-php-extensions json
RUN install-php-extensions mailparse
RUN install-php-extensions mbstring
RUN install-php-extensions readline
RUN install-php-extensions soap
RUN install-php-extensions xml
RUN install-php-extensions xmlrpc
RUN install-php-extensions bz2
RUN install-php-extensions zlib
RUN install-php-extensions dba
RUN install-php-extensions ldap
RUN install-php-extensions xdebug
RUN install-php-extensions @composer
```

**Comment by 1Jackob1** [comment]
@arcanisgk thx!

**Comment by typoworx-de** [comment]
I'm also having similar problems with different php-extensions. Here for example with zip:
```
FROM php:8.1-fpm-bullseye

RUN set -ex; \
  IPE_GD_WITHOUTAVIF=1 \
  install-php-extensions zip
```

Error during build in Dockerfile:
```
#22 92.30 + docker-php-ext-install -j12 zip
#22 92.30 make: *** No rule to make target 'zip', needed by 'all'.  Stop.
------
failed to solve: executor failed running [/bin/bash -c set -ex; IPE_GD_WITHOUTAVIF=1   install-php-extensions zip]: exit code: 2
```

The funny thing is.... skipping installing extensions in my custom build and running exactly the same command in the running docker-container works!
```
# docker-php-ext-install -j12 zip
```

It's driving me crazy as I'm juggling around on this now a few days trying to get it working. And always during Dockerfile build it's crashing, but running it in the build container works.

What can be the reason for this?!

**Comment by chosroes** [comment]
I also can't install some extensions (apcu/grpc/imagick, etc)
Always the same error :
#0 35.70 ### INSTALLING REMOTE MODULE apcu ###
#0 35.86 No releases available for package "pecl.php.net/apcu"
#0 35.86 install failed

**Comment by mlocati** [comment]
> ```shell
> curl -sSLf -o /dev/null https://pecl.php.net/get/apcu
> ```

Or even better:

```sh
curl -sSLf https://pecl.php.net/rest/r/apcu/allreleases.xml
```

**Comment by chosroes** [comment]
I get this :

`<?xml version="1.0" encoding="UTF-8" ?>
<a xmlns="http://pear.php.net/dtd/rest.allreleases"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink"     xsi:schemaLocation="http://pear.php.net/dtd/rest.allreleases
    http://pear.php.net/dtd/rest.allreleases.xsd">
 <p>apcu</p>
 <c>pecl.php.net</c>
 <r><v>5.1.22</v><s>stable</s></r>
 <r><v>5.1.21</v><s>stable</s></r>
 <r><v>5.1.20</v><s>stable</s></r>
 <r><v>5.1.19</v><s>stable</s></r>
 <r><v>5.1.18</v><s>stable</s></r>
 <r><v>5.1.17</v><s>stable</s></r>
 <r><v>5.1.16</v><s>stable</s></r>
 <r><v>5.1.15</v><s>stable</s></r>
 <r><v>5.1.14</v><s>stable</s></r>
 <r><v>5.1.13</v><s>stable</s></r>
 <r><v>5.1.12</v><s>stable</s></r>
 <r><v>5.1.11</v><s>stable</s></r>
 <r><v>5.1.10</v><s>stable</s></r>
 <r><v>5.1.9</v><s>stable</s></r>
 <r><v>5.1.8</v><s>stable</s></r>
 <r><v>5.1.7</v><s>stable</s></r>
 <r><v>5.1.6</v><s>stable</s></r>
 <r><v>5.1.5</v><s>stable</s></r>
 <r><v>5.1.4</v><s>stable</s></r>
 <r><v>4.0.11</v><s>stable</s></r>
 <r><v>5.1.3</v><s>stable</s></r>
 <r><v>5.1.2</v><s>stable</s></r>
 <r><v>4.0.10</v><s>stable</s></r>
 <r><v>5.1.0</v><s>beta</s></r>
 <r><v>4.0.8</v><s>stable</s></r>
 <r><v>4.0.7</v><s>beta</s></r>
 <r><v>4.0.6</v><s>beta</s></r>
 <r><v>4.0.5</v><s>beta</s></r>
 <r><v>4.0.4</v><s>beta</s></r>
 <r><v>4.0.3</v><s>beta</s></r>
 <r><v>4.0.2</v><s>beta</s></r>
 <r><v>4.0.1</v><s>beta</s></r>
 <r><v>4.0.0</v><s>beta</s></r>
</a>%`

**Comment by chosroes** [comment]
![image](https://user-images.githubusercontent.com/1119471/229753828-e7daae72-ad9e-46f1-9949-e2af2f012638.png)

**Comment by mlocati** [comment]
So, pecl is working for you (maybe it was a transient problem).
Could you try to run `install-php-extensions apcu` again now?

**Comment by qleroy** [comment]
In my case I could not install `xmlrpc`, consistently over three tries.
```
install-php-extensions xmlrpc
...
#12 46.08 ### INSTALLING REMOTE MODULE xmlrpc ###
#12 46.08   (installing version beta)
#12 46.16 No releases available for package "pecl.php.net/xmlrpc"
#12 46.16 install failed
```
I am using php:8.1

**Comment by mlocati** [comment]
@qleroy Same answer as above

**Comment by akserikawa** [comment]
Seems like this keeps happening at random. In my case different errors pop up when installing xdebug at random builds.
Once I retry building my image a couple times everything goes ok. Weird stuff

It's either:

> No releases available for package "pecl.php.net/xdebug"

or

> Package "xdebug" does not have REST info xml available

**Comment by mlocati** [comment]
That's caused by network problems (likely the pecl webserver is down).

There's nothing I can do about that.

**Comment by arcanisgk** [comment]
I'm still thinking about the possibility of a validation interface prior to the installation of packages that validates which packages have problems... the truth is that I like to do it through the terminal when I work with linux but it s[t]uck when errors appear in the middle of an installation from docker... when trying to run an automated install script...

the time is gold...
