### ISSUE TITLE
Error fetching the latest stable version

### ISSUE THREAD

**Issue by Gounlaf** [mlocati/docker-php-extension-installer#635]
### Version of install-php-extensions

latest

### Error description

Hi,

I'm not really sure, but I think there is an issue while retrieving the latest version stable of an extension.
If i'm right, the "latest publish" version is selected, but not the latest one.

As a result, if release are not in order on PECL, it leads to some mismatch.
Take `protobuf`: they have released some patch (security issues). As you can see in attachment, the release order on PECL is ordered by date, not by versions.

`protobuf-stable` take [3.18.3](https://pecl.php.net/package/protobuf/3.18.3) instead of [3.21.6](https://pecl.php.net/package/protobuf/3.21.6), leading to building issue.

![image](https://user-images.githubusercontent.com/236413/191967315-c185fcb5-d969-404c-b101-0c68b56ee2c6.png)

### Docker image

php:8.1

### Minimal Dockerfile

```Dockerfile
FROM php:8.1

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions protobuf-stable grpc-stable
```

**Comment by mlocati** [comment]
Same as #633

**Comment by Gounlaf** [comment]
My bad. I didn't make the link between ><

**Comment by mlocati** [comment]
For the time being, I've hardcoded the latest protobuf version (see #636)
