### ISSUE TITLE
Installing libavif curl: (22) The requested URL returned error: 

### ISSUE THREAD

**Issue by mreduar** [mlocati/docker-php-extension-installer#640]
### Version of install-php-extensions

v.1.5.41

### Error description

Today our pipelines started to fail due to the curl error.
```
Installing libavif curl: (22)
curl: (22) The requested URL returned error:
```

Before the recent update this had never happened to us.
Pipelines had to be run 3 times before it installed correctly

### Docker image

php:8.1-fpm

### Minimal Dockerfile

```Dockerfile
script:
            - apt-get update
            - apt-get install -y mariadb-client
            - curl -sSLf -o /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && chmod +x /usr/local/bin/install-php-extensions && install-php-extensions gd pdo_mysql pcov exif
            - php -d pcov.enabled=1 ./vendor/bin/pest --coverage --min=95 -d memory_limit=-1
```
```

**Comment by mlocati** [comment]
I've just tried these exact same commands, and everything worked flawlessly for me.
Maybe you've had a temporary network failure?

**Comment by mreduar** [comment]
It runs directly in bitbucket containers. Let me try more times to see if the error continues.

**Comment by mreduar** [comment]
It honestly seems like it only happened that one time. Sorry for the inconvenience.
