### ISSUE TITLE
Slow build 900+ second:

### ISSUE THREAD

**Issue by arcanisgk** [mlocati/docker-php-extension-installer#645]
### Version of install-php-extensions

lastes

### Error description

Slow build 900+ second:

![image](https://user-images.githubusercontent.com/1207306/195893086-78b8e146-93b0-43de-928a-7220d6a67a0a.png)

### Docker image

php:8.1.11-fpm

### Minimal Dockerfile

i have create this repor to done the setup expected: 

[repository](https://github.com/arcanisgk/Minos)

i need to run mutiple times:

`ctrl+c` to cancel

`docker-compose up --build --force-recreate`

to get the build finiches becouse some data is on cached:

![image](https://user-images.githubusercontent.com/1207306/195895841-54d89efa-773c-4983-b59a-b28c68a9192a.png)

**Comment by mlocati** [comment]
See the [Configuration section](https://github.com/mlocati/docker-php-extension-installer#configuration), in particular the part about GD.

Also, calling `install-php-extensions` once per extension is more time consuming that calling `install-php-extensions` just once passing it all the extensions you require.

That is:

```
install-php-extensions foo
install-php-extensions bar
install-php-extensions baz
```

is slower than

```
install-php-extensions foo bar baz
```
