### ISSUE TITLE
Use libavif-dev instead of compiling by own

### ISSUE THREAD

**Issue by shyim** [mlocati/docker-php-extension-installer#651]
Hey,

I found some prebuild packages for avif support in Alpine packages to improve the CI speed. I guess anyone would thanks us to not compile this slow packages.

```
apk add --no-cache libavif-dev aom-dev dav1d-dev
```

**Comment by shyim** [comment]
Before: 1h 25m 28s
https://github.com/shyim/shopware/actions/runs/3349584981

After: 44m 26s
https://github.com/shyim/shopware/actions/runs/3349584981

**Comment by mlocati** [comment]
> `apk add --no-cache libavif-dev aom-dev dav1d-dev`

When I added support for AVIF on PHP 8.1 images, the latest Alpine version was 3.14.
With that Alpine version, using those pre-compiled system libraries caused GD to fails to handle AVIF images with this error:

```
imageavif(): avif error - Could not encode image: No codec available
```

But starting from Alpine 3.15 everything seems to work as expected: see #653.
Thanks!

**Comment by shyim** [comment]
Thanks also for adding it so fast ❤️
