### ISSUE TITLE
Can't install xdebug and apcu ono php 8.1

### ISSUE THREAD

**Issue by Yeine** [mlocati/docker-php-extension-installer#654]
### Version of install-php-extensions

latest

### Error description

Both with the same error: Can't resolve https://objects.githubusercontent.com/

### Docker image

php:8.1-fpm-alpine

### Minimal Dockerfile

```Dockerfile
#syntax=docker/dockerfile:1.4

# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG PHP_VERSION=8.1

# Prod image
FROM php:${PHP_VERSION}-fpm-alpine AS app_php

# php extensions installer: https://github.com/mlocati/docker-php-extension-installer
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions apcu;
RUN install-php-extensions xdebug;
```

**Comment by mlocati** [comment]
This issue has nothing to do with the `install-php-extension`.
See also #497, and in particular https://github.com/mlocati/docker-php-extension-installer/issues/497#issuecomment-1047229999
