### ISSUE TITLE
Support cassandra

### ISSUE THREAD

**Issue by maxm86545** [mlocati/docker-php-extension-installer#665]
Actual src https://github.com/nano-interactive/ext-cassandra/tree/v1.3.x

PECL is outdated and not support PHP 8.x https://pecl.php.net/package/cassandra

https://github.com/nano-interactive/ext-cassandra/issues/30

**Comment by mlocati** [comment]
Can't they update the code on the PECL repository?

**Comment by maxm86545** [comment]
No. This is a fork and there are problems with PECL. More https://github.com/nano-interactive/ext-cassandra/issues/30#issuecomment-1158131603
