### ISSUE TITLE
Caching of extensions

### ISSUE THREAD

**Issue by shyim** [mlocati/docker-php-extension-installer#666]
Just a stupid idea:

Currently, we always build the extensions from source in the `Dockerfile` which takes like 2-3 minutes with a good CPU.  
Can't we make a global cache with `extensionName-${ extensionName }-php-${ version }-(musl/glibc)` and build that extension.so file once and upload it there.

Then `install-php-extensions` could look into that cache if it exists, downloads that so file and installs the required apk/apt packages (libraries without dev). I guess this would save a lot of CPU resources on everyone's ci.

IDK I am thinking here too simple, but managing the CI / the storage could be annoying but it would benefit our all CI's and maybe safe some co2.

For storage maybe GitHub releases any extension is a release and the so files are uploaded as artifact on that release

**Comment by mlocati** [comment]
You can run `docker commit` after installing the extensions, and use it for later steps

**Comment by mvorisek** [comment]
apt will still require some CPU time and internet bandwith

what is your usecase? if you you use some standard base image, you can prebuild your of Docker image or use https://github.com/mvorisek/image-php for example, which has almost all extensions enabled

**Comment by shyim** [comment]
Building the docker images is a pain if you also want to have multi arch builds. QEMU arm64 with some php extensions takes almost an hour to run.  

It feels for me like really wasted time of resources when everyone has to build the PHP extensions from source

**Comment by shyim** [comment]
I will look by my own and have already an idea 🤔

**Comment by maxxer** [comment]
@shyim mind sharing your ideas/solutions? thanks

**Comment by typoworx-de** [comment]
How about using docker BUILDKIT caching?
