### ISSUE TITLE
Uninstall feature

### ISSUE THREAD

**Issue by Legion112** [mlocati/docker-php-extension-installer#667]
I would like to install and extension which is required only during image build run PHP code and after uninstall that extension

**Comment by mlocati** [comment]
What are you trying to achieve? Just disable the PHP extension? Or free up some space?

**Comment by Legion112** [comment]
I am trying to run phive tool which is requiring gpg to run. 


I actually could move running phive to separate build stage that they gpg extension won't be install on final image

**Comment by mlocati** [comment]
You can simply "disable" the PHP extension by running

```sh
rm "$(php-config --ini-dir)/docker-php-ext-<extension>.ini"
```

**Comment by Legion112** [comment]
Deleting config won't delete files with extention.

**Comment by mlocati** [comment]
You can delete the ini file and the extension so file, as well as the apt/apk system packages required by the package.
But I don't think I'm going to implement this feature: it'd require tracking the dependencies for any PHP extension installed (maybe in different steps, not in just one call to the script): it'd overcomplicate the script, and for just a tiny number of users.
