### ISSUE TITLE
Installing extensions behind firewall. 

### ISSUE THREAD

**Issue by Legion112** [mlocati/docker-php-extension-installer#668]
### Version of install-php-extensions

mlocati/php-extension-installer:1.5

### Error description

Our CI is in a protected firewall which limits request that could go outside. Is there a way to not make request to github.com?
```
[stage-0 2/2] RUN  --mount=type=bind,from=harbor.noones.tools/docker-hub-proxy/mlocati/php-extension-installer:1.5,source=/usr/bin/install-php-extensions,target=/usr/local/bin/install-php-extensions       install-php-extensions apcu-5.1.22 redis-5.3.7
#6 sha256:3b8c5beaf162b8047ba99cbc0d1635177e0ca3ad0a044617f30a459ff2485e5e
#6 0.229 install-php-extensions v.1.5.49
#6 0.229 #StandWithUkraine
#6 132.2 curl: (28) Failed to connect to github.com port 443 after 130412 ms: Couldn't connect to server
#6 ERROR: executor failed running [/bin/sh -c install-php-extensions apcu-5.1.22 redis-5.3.7]: exit code: 28
```

### Docker image

php:8.1-cli-alpine

### Minimal Dockerfile

```Dockerfile
FROM php:8.1-cli-alpine

RUN  --mount=type=bind,from=mlocati/php-extension-installer:1.5,source=/usr/bin/install-php-extensions,target=/usr/local/bin/install-php-extensions \
      install-php-extensions apcu-5.1.22 redis-5.3.7
```

**Comment by Legion112** [comment]
The question is why does it make requests to GitHub?
Is there a debug mode to see the whole output of the script to see which request is making the script?

**Comment by enumag** [comment]
If you look for github.com in https://github.com/mlocati/docker-php-extension-installer/blob/master/install-php-extensions you'll see are can be plenty of cases when such requests happen. Most likely it's impossible to use this without GitHub.

**Comment by mlocati** [comment]
> What exactly is pulled out of GitHub? Archive with extension code?

@Legion112 everything's written in the script:

1. you can use the script to install extensions from GitHub: see
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/README.md#installing-from-source-code
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/install-php-extensions#L277
2. the AVIF system library source code (used by the GD php extension for PHP 8.1+) is fetched from GitHub:
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/install-php-extensions#L2031
3. the enchant system library source code (used by the enchant php extension) is fetched from GitHub:
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/install-php-extensions#L2212
4. the firebird system library source code (used by the interbase and pdo_firebird php extensions) is fetched from GitHub for Alpine Linux:
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/install-php-extensions#L2292
5. the cmark system library source code (used by the cmark php extension) is fetched from GitHub:
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/install-php-extensions#L2519
6. the gearman system library source code (used by the gearman php extension) is fetched from GitHub for Alpine Linux:
   - https://github.com/mlocati/docker-php-extension-installer/blob/1.5.49/install-php-extensions#L2641

... and so on.

**Comment by mlocati** [comment]
> Is there a debug mode to see the whole output of the script to see which request is making the script?

Sure: simply add this line right after `set -o nounset`:

```sh
set -x
```
