### ISSUE TITLE
rdkafka install error php:8.1-fpm

### ISSUE THREAD

**Issue by maciejsk** [mlocati/docker-php-extension-installer#675]
### Version of install-php-extensions

docker error after add rdkafka ext

### Error description

 > [stage-0 4/7] RUN docker-php-ext-install pdo pdo_pgsql mbstring bcmath zip exif opcache rdkafka:
#7 2.322 error: /usr/src/php/ext/rdkafka does not exist
#7 2.322
#7 2.322 usage: /usr/local/bin/docker-php-ext-install [-jN] [--ini-name file.ini] ext-name [ext-name ...]
#7 2.322    ie: /usr/local/bin/docker-php-ext-install gd mysqli
#7 2.322        /usr/local/bin/docker-php-ext-install pdo pdo_mysql
#7 2.322        /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop
#7 2.322
#7 2.322 if custom ./configure arguments are necessary, see docker-php-ext-configure
#7 2.322
#7 2.322 Possible values for ext-name:
#7 2.372 bcmath bz2 calendar ctype curl dba dl_test dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlwriter xsl zend_test zip
#7 2.372
#7 2.372 Some of the above modules are already compiled into PHP; please check
#7 2.372 the output of "php -i" to see which modules are already loaded.

### Docker image

php:8.1-fpm

### Minimal Dockerfile

```Dockerfile
FROM php:8.1-fpm

WORKDIR "/application"

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    libpq-dev \
    librdkafka-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Install PHP extensions   https://github.com/mlocati/docker-php-extension-installer
RUN docker-php-ext-install pdo pdo_pgsql mbstring bcmath zip exif opcache rdkafka
```

**Comment by mlocati** [comment]
When you created this issue, you have been presented this message:

```
Please remark that this project is about the install-php-extensions command, not about docker-php-ext-install.
```
