### ISSUE TITLE
openswoole 22.0.0, change enable-swoole-curl to enable-hook-cur

### ISSUE THREAD

**Issue by timaelliott** [mlocati/docker-php-extension-installer#700]
In openswoole 22.0.0, they changed the compile option from `--enable-swoole-curl` to `--enable-hook-curl`. The prior no longer has any effect on this version.

https://pecl.php.net/package-changelog.php?package=openswoole&release=22.0.0

**Comment by mlocati** [comment]
Thanks! I missed that change.
PS: they also removed the `--enable-swoole-json` compile option: see https://mlocati.github.io/pecl-info/#openswoole
