### ISSUE TITLE
The documentations says that the extensions will be automatically enabled yet they are installed but not enabled for neither fpm or cli.

### ISSUE THREAD

**Issue by manu144x** [mlocati/docker-php-extension-installer#715]
### Version of install-php-extensions

latest

### Error description

As stated in the title, no extension is enabled, yet the documentation says they are.

I had to revert back to docker for some of them, docker commands automatically enables them too.

### Docker image

php:7.4-fpm

### Minimal Dockerfile

```Dockerfile
FROM php:7.4-fpm

# For these, docker seems to do a better job:
RUN apt-get update && apt-get install -y git zlib1g-dev
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install opcache
# FOR ALL THE OTHER THAT ARE SPREAD AROUND:
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions gd xml bcmath odbc intl mbstring ldap sqlite3 redis curl zip
```

**Comment by mlocati** [comment]
I guess you have to restart thr fpm service

**Comment by mlocati** [comment]
`install-php-extension` already does the same operations performed by `docker-php-ext-enable`, unless you define the `IPE_DONT_ENABLE` environment variable.
