### ISSUE TITLE
Allow Blackfire for PHP version 8.2

### ISSUE THREAD

**Issue by BeyerJC** [mlocati/docker-php-extension-installer#742]
Hi ! 
Does something speak against allowing blackfire on PHP 8.2 ? Support on extension side was added https://blog.blackfire.io/blackfire-now-supports-php-8-2.html.

Im not too deep into this extension yet. Are there any blockers or do we only have to allow the new version ?

**Comment by mlocati** [comment]
> Does something speak against allowing blackfire on PHP 8.2 ?

The only reason why `install-php-extensions` doesn't support it yet is because I wasn't aware that they created a version compatible with PHP 8.2 :wink:

See #743
