### ISSUE TITLE
pdo_sqlsrv cannot be installed on Debian Bookworm

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#757]
### Version of install-php-extensions

latest

### Error description

The problem is probably somewhere around https://github.com/mlocati/docker-php-extension-installer/blob/0fe930eef/install-php-extensions#L1954

Debian Bookworm is a new Debian major release released a few days ago. All extensions should be probably tested with it in nightly.

### Docker image

php 8.2 bookworm

### Details

CI output https://github.com/mvorisek/image-php/actions/runs/5297724259/jobs/9589666998#step:13:14022:
```
 ### INSTALLING REMOTE MODULE pdo_sqlsrv ###
Installing the Microsoft SQL Server ODBC Driver
- installing the Microsoft APT key
- adding the Microsoft APT source list
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Get:4 https://packages.microsoft.com/debian/12/prod bookworm InRelease [3597 B]
Err:4 https://packages.microsoft.com/debian/12/prod bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists...
W: GPG error: https://packages.microsoft.com/debian/12/prod bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/debian/12/prod bookworm InRelease' is not signed.
```

**Comment by DIReports** [comment]
The public key error is fixed when [line 1967](https://github.com/mlocati/docker-php-extension-installer/blob/a87b75296d9dfd70ef2294c7d68ab30a10729720/install-php-extensions#L1967)
`curl -sSLf -o /etc/apt/trusted.gpg.d/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc`
is replace by
`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --yes --output /usr/share/keyrings/microsoft-prod.gpg`

However it seems there are no msodbcsql packages available yet.
`E: Unable to locate package ^msodbcsql[0-9]+$`

**Comment by mvorisek** [comment]
fixed in https://github.com/mlocati/docker-php-extension-installer/pull/765
