### ISSUE TITLE
IPE_ICU_EN_ONLY must still allow to install `icu-data-full` on Alpine

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#766]
### Version of install-php-extensions

latest

### Error description

It seems this installer locks the ICU to `icu-data-en`. This is wrong as upgrade to `icu-data-full` must be always possible, as it may be required by some other packages, like https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium

build output: https://github.com/mvorisek/image-php/actions/runs/5357097802/jobs/9717488147#step:19:207

### Docker image

php:8.2-cli-alpine

### Minimal Dockerfile

```Dockerfile
RUN apk update \
    && apk upgrade \
    && apk add bash git make unzip gnupg ca-certificates coreutils \
    && rm -rf /var/cache/apk/*
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN IPE_ICU_EN_ONLY=1 install-php-extensions \
    bcmath \
    exif \
    gd \
    gmp \
    igbinary \
    imagick \
    imap \
    intl \
    mysqli \
    oci8 \
    opcache \
    pcntl \
    pdo_mysql \
    pdo_oci \
    pdo_pgsql \
    pdo_sqlsrv \
    redis \
    sockets \
    tidy \
    xdebug \
    xsl \
    zip
RUN apk update apk add chromium chromium-chromedriver nss-tools

```

(`IPE_ICU_EN_ONLY` cannot be removed from the DockerFile, as the DockerFile here is simplified and published /wo the last command, ie. the image is build based another image with `IPE_ICU_EN_ONLY`)

**Comment by mlocati** [comment]
> ### Docker image
> 
> php:8.2-cli

`IPE_ICU_EN_ONLY` is only used in Alpine, whereas `php:8.2-cli` is debian.

Did you mean `php:8.2-cli-alpine` ?

**Comment by mvorisek** [comment]
Yes, I corrected it in the description too.

**Comment by mlocati** [comment]
> Minimal Dockerfile
> ```Dockerfile
> RUN apk update \
> ```

This is missing `FROM php:...`, it's not a Dockerfile...

> ```Dockerfile
> RUN IPE_ICU_EN_ONLY=1 install-php-extensions \
>     bcmath \
>     exif \
>     gd \
>     gmp \
>     igbinary \
>     imagick \
>     imap \
>     intl \
>     mysqli \
>     oci8 \
>     opcache \
>     pcntl \
>     pdo_mysql \
>     pdo_oci \
>     pdo_pgsql \
>     pdo_sqlsrv \
>     redis \
>     sockets \
>     tidy \
>     xdebug \
>     xsl \
>     zip
> ```

Are you sure that in order to reproduce the issue we really need to install all these extensions? If not, it's not a *minimal* Dockerfile.

> ```dockerfile
> RUN apk update apk add chromium chromium-chromedriver nss-tools
> ```

Did you mean the following, right? 

```dockerfile
RUN apk update && apk add chromium chromium-chromedriver nss-tools
```

So, a really minimal Dockerfile would have been:

```Dockerfile
FROM php:8.2-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl

RUN apk update && apk add chromium
```

Sorry to be so picky, but maintaining this project is really time intensive, and it'd be really useful to have a *minimal* and *working* Dockerfile so that I can test it quickly 😉

Now that I have a minimal working dockerfile I can check what's going wrong

**Comment by mvorisek** [comment]
Thank you and sorry for the maximal repro, at that moment, I did not have a local Docker access.

---

Based on `icu-libs` docs https://pkgs.alpinelinux.org/package/edge/main/x86_64/icu-libs:

![image](https://github.com/mlocati/docker-php-extension-installer/assets/2228672/9d54ab5d-37c5-4b56-a28a-0e3c648819a9)

the `icu-data-en` package is required. Thankfully, this is a limitation of the Alpine website/docs, and `icu-data-full` package satisfy `icu-libs` too. Given this, the `icu-data-en` package is kept instaleld even if not required explicitly.

I tested `apk del icu-data-en` localy now and it output:
```
World updated, but the following packages are not removed due to:
  icu-data-en: icu-libs
```

which is exactly what we want. `icu-data-en` may be needed to be installed explicitly first to choose the right alternative, but then the data `icu-data-en` package does not need to be added explicitly. I belive it should be done by this installer.

**Comment by mlocati** [comment]
> I tested `apk del icu-data-en` localy

Try ([as I wrote above](https://github.com/mlocati/docker-php-extension-installer/issues/766#issuecomment-1604486855)) with:

```sh
apk del icu-data-en icu-libs
apk add icu-libs
```

**Comment by mvorisek** [comment]
`apk del icu-data-en` should be run by this installed after the install, as analysed in my post.

**Comment by mlocati** [comment]
AFAIK many PHP extensions (`intl` for example) require `icu-libs`, and `icu-libs` requires that one of `icu-data-en` or `icu-data-full` is installed.

Am I wrong?

**Comment by mvorisek** [comment]
Yes, like in Debian some packages require "A or B". `icu-libs` require `icu-data-en` or `icu-data-full`.

So if `apk del icu-data-en` is run, `icu-libs` will keep one of the data package installed.

So this installer must explicitly install `icu-libs` but not `icu-data-en`.

**Comment by mlocati** [comment]
> So this installer must explicitly install icu-libs but not icu-data-en.

Isn't that what happens when you don't specify `IPE_ICU_EN_ONLY`,?

**Comment by mvorisek** [comment]
No, one of the ICU data package was locked... Should be fixed by #768.

**Comment by mvorisek** [comment]
@mlocati can this issue be reopened please?

The minimal repro is:
```
FROM php:8.2-cli-alpine
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl
RUN apk update && apk add chromium
```

as `icu-data-en` package will be kept required by `icu-libs`, I expect from this installer `icu-data-en` package not explicitly required, ie. run someting like `apk del icu-data-en` before the installer finish.

**Comment by mvorisek** [comment]
see https://github.com/mvorisek/image-php/blob/master/data/8.2-alpine/Dockerfile#L39 Dockerfile for example.

We build small image with `IPE_ICU_EN_ONLY=1`. We explicitly tell we need AT LEAST `icu-data-en`. When some other package needs full `icu-data-full` later, the upgrade should not be blocked, as `icu-data-en` is full subpackage, so nothing is effectively removed.

**Comment by mvorisek** [comment]
> I don't know a way to do that. Do you?

I am telling is here - `apk del icu-data-en` run by the installer itself.

> No: we explicitly tell apk to install EXACTLY icu-data-en

I view `IPE_ICU_EN_ONLY=1` option as: en ICU is enough, but I full ICU is fine as well.

**Comment by mlocati** [comment]
> I am telling it here - `apk del icu-data-en` run by the installer itself. Then I do not need it to be run in my Dockerfile manually :)

As I wrote a ton of times, `icu-libs` requires that either `icu-data-en` or `icu-data-full` is installed, so we can't uninstall `icu-data-en`. For example, here's a sample session (inside a `php:8.2-cli-alpine` docker image)

```
# IPE_ICU_EN_ONLY=1 install-php-extensions intl
[... omissis ...]

# php -m | grep intl
intl

# apk del icu-data-en
World updated, but the following packages are not removed due to:
  icu-data-en: icu-libs
```

The only way to uninstall `icu-data-en` is to uninstall `icu-libs` too, but then the PHP extensions depending on it would break;

```
# apk del icu-data-en icu-libs
(1/2) Purging icu-libs (73.2-r1)
(2/2) Purging icu-data-en (73.2-r1)

# php --ri intl
Warning: PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/intl.so (Error loading shared library libicuio.so.73: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20220829/intl.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/intl.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20220829/intl.so.so: No such file or directory)) in Unknown on line 0
Extension 'intl' not present.
```



>> No: we explicitly tell apk to install EXACTLY icu-data-en
> 
> I view `IPE_ICU_EN_ONLY=1` option as: en ICU is enough, but I full ICU is fine as well.

If `install-php-extensions`  sees that `IPE_ICU_EN_ONLY=1`, it asks apk to install `icu-data-en`.
That's what it does.

Please submit a pull request if you know a way to do what you'd like should be done: I don't know a way to do it.

**Comment by mvorisek** [comment]
```
# apk del icu-data-en
World updated, but the following packages are not removed due to:
  icu-data-en: icu-libs
```

this is exactly what we want. The `icu-data-en` will not longer be required explicitly, but ` icu-libs` will keep the package correctly installed.

**Comment by mlocati** [comment]
I understrood very well that you would like to install `icu-data-en` instead of `icu-data-full`, but still allow apk installing `icu-data-full` when required.

Did you understand that I'm asking how you would do it?

**Comment by mvorisek** [comment]
Based on https://github.com/mlocati/docker-php-extension-installer/issues/766#issuecomment-1630483641 post it seems you do not understand it well. `icu-libs` should never be uninstalled. `apk del icu-data-en` prints `World updated, but the following packages are not removed due to: icu-data-en: icu-libs` which doesn't mean nothing has been done.

Please try these demos:
```
FROM php:8.2-cli-alpine
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl
RUN apk update && apk add chromium
```
and
```
FROM php:8.2-cli-alpine
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN IPE_ICU_EN_ONLY=1 install-php-extensions intl
RUN apk del icu-data-en
# notice package "icu-data-en" was not uninstalled, but now ICU data upgrade is possible
RUN apk update && apk add chromium
```

**Comment by mlocati** [comment]
Now it's clear: `apk del icu-data-en` doesn't uninstall `icu-data-en`, but it tells apk that it's no more required.

**Comment by mvorisek** [comment]
Thank you, Michele!
