### ISSUE TITLE
Latest grpc extension (1.59.2) fails to install from source on alpine

### ISSUE THREAD

**Issue by nocive** [mlocati/docker-php-extension-installer#825]
### Version of install-php-extensions

v2.1.60

### Error description

```
install-php-extensions grpc/grpc@v1.59.2
(...)
41.20 ### INSTALLING REMOTE MODULE grpc ###
41.21   (installing version 1.59.2 from /tmp/src/tmp.lBPMAj/grpc-1.59.2)
41.69 ERROR: file /tmp/src/tmp.lBPMAj/grpc-1.59.2/third_party/abseil-cpp/absl/algorithm/algorithm.h does not exist
```

### Docker image

php:8.2.12-fpm-alpine3.18

**Comment by mlocati** [comment]
It seems that grpc can't be built from the GitHub repository: I thing they do some extra steps to prepare the package.

I won't add support for this (I really can't maintain the pre-release steps for every package).

**Comment by nocive** [comment]
Fair enough.

I'd be happy to implement it, but it doesn't seem to fit the design, so I wanted to get some feedback first :)
We would at least need to clone the submodules, but I suspect that alone would not be enough.
