### ISSUE TITLE
undefined symbol: ZSTR_INIT_LITERAL

### ISSUE THREAD

**Issue by jawira** [mlocati/docker-php-extension-installer#826]
### Version of install-php-extensions

v.1.5.37

### Error description

I get this error when installing xdebug extension:

`undefined symbol: ZSTR_INIT_LITERAL`

Full output:

```
### INSTALLING REMOTE MODULE xdebug ###
  - Installing xdebug (latest-stable): Downloading (100%)         
+-----------------------------------+-------------+
| Package name                      | xdebug      |
| Package version (current release) | 3.3.0alpha3 |
| Package status                    | alpha       |
+-----------------------------------+-------------+
Removing symbols from /usr/local/lib/php/extensions/no-debug-non-zts-20210902/xdebug.so... done (1817136 bytes saved).
Check if the xdebug module can be loaded... Error loading the "xdebug" extension:
php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/xdebug.so: undefined symbol: ZSTR_INIT_LITERAL
1 error occurred:
	* Status: The command '/bin/sh -c install-php-extensions xdebug' returned a non-zero code: 1, Code: 1
```

I assumed the error appears because an alpha version of xdebug is installed, so I fixed de error explicitly installing Xdebug v3.2.2 

`RUN install-php-extensions xdebug-3.2.2`

Nevertheless I think this error should be fixed.

Thanks :)

### Docker image

php:8.1-fpm

### Minimal Dockerfile

```Dockerfile
FROM php:8.1-fpm

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions xdebug
```

**Comment by mlocati** [comment]
> ### Version of install-php-extensions
> 
> v.1.5.37

This is a rather old version: do you have the same issue with the most recent one ( v.2.1.60)?

**Comment by jawira** [comment]
You are right, a simple _docker pull_ fixed the issue.

Thanks for your time! :)
