### ISSUE TITLE
No zip or unzip installed

### ISSUE THREAD

**Issue by AmirRezaM75** [mlocati/docker-php-extension-installer#836]
### Version of install-php-extensions

2.1

### Error description

I tried to install PHP `zip` extension and it was installed successfully. But when trying to install project dependencies using `composer install`. I got following error: 
> As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' (21.01+) may remediate them

I guess binary files have been removed in cleaning unused packages phase.

### Docker image

php:8.2-fpm

### Minimal Dockerfile

```Dockerfile
FROM php:8.2-fpm

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions

RUN install-php-extensions mbstring exif pcntl bcmath gd zip pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

```

**Comment by mlocati** [comment]
The `php:8.2-fpm` docker image doesn't come with the `unzip` command pre-installed:

```
$ docker run --rm -it php:8.2-fpm unzip -v
/usr/local/bin/docker-php-entrypoint: 9: exec: unzip: not found
```

With `install-php-extensions zip` you are installing the zip PHP extension, not the zip system command, which is very different.

You have 2 options:

1. adding `RUN apt-get update && apt-get install -qy unzip` to your dockerfile

2. use `install-php-extensions` to install composer

In the second case, `install-php-extensions` will also install the `unzip` system command.
If you choose the second option, you can replace these lines

```Dockerfile
RUN install-php-extensions mbstring exif pcntl bcmath gd zip pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
```

with

```Dockerfile
RUN install-php-extensions mbstring exif pcntl bcmath gd zip pdo_mysql @composer
```
