### ISSUE TITLE
Unable to install `relay` on `8.2.13-fpm-alpine3.19`

### ISSUE THREAD

**Issue by PAXANDDOS** [mlocati/docker-php-extension-installer#851]
### Version of install-php-extensions

v.2.1.70

### Error description

When running Alpine 3.19 and trying to install `relay` (maybe more extensions are affected, I only tried "intl pcntl pdo_mysql redis relay zip") encountered an error saying that `libssl1.1 (no such package)`

Which is true, `libssl1.1` does not exist on 3.19
3.19 (libssl3 only): [pkgs.alpinelinux.org](https://pkgs.alpinelinux.org/packages?name=libssl*&branch=v3.19)
3.18 (libssl3 and 1.1): [pkgs.alpinelinux.org](https://pkgs.alpinelinux.org/packages?name=libssl*&branch=v3.18)

And the log:
```log
------
 > [app production  3/11] RUN install-php-extensions relay     && rm /usr/local/bin/install-php-extensions:
0.255 install-php-extensions v.2.1.70
0.255 #StandWithUkraine
1.474 Updating channel "pecl.php.net"
2.101 Channel "pecl.php.net" is up to date
2.106 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
2.442 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
2.813 v3.19.0-48-gefae5fa1bd4 [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]
2.813 v3.19.0-47-g0c9562db690 [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]
2.813 OK: 22985 distinct packages available
4.119 FAILED TO LIST THE WHOLE PACKAGE LIST FOR
4.119 lz4-libs zstd-libs libssl1.1
4.119
4.119 COMMAND OUTPUT:
4.119 ERROR: unable to select packages:
4.119   libssl1.1 (no such package):
4.119     required by: world[libssl1.1]
4.119
4.119 ERROR: apk failed
------
failed to solve: process "/bin/sh -c install-php-extensions relay     && rm /usr/local/bin/install-php-extensions" did not complete successfully: exit code: 1
```

### Docker image

php:8.2-fpm-alpine

### Minimal Dockerfile

```Dockerfile
FROM php:8.2-fpm-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions relay \
    && rm /usr/local/bin/install-php-extensions
```

**Comment by mlocati** [comment]
The root cause is that they recently [switched to Alpine 3.19](https://github.com/docker-library/php/pull/1471) as the default version for PHP 8.2, which isn't tested at the moment.
I'm going to add support for Alpine 3.19.
BTW #1471 should fix this #851.
