### ISSUE TITLE
libssl: "ERROR: unsatisfiable constraints" 

### ISSUE THREAD

**Issue by shinsenter** [mlocati/docker-php-extension-installer#854]
### Version of install-php-extensions

v.2.1.71

### Error description

I think the following error has been occurring since I upgraded to version 2.1.71 today. I'm not sure of the exact cause of the error, but it was working perfectly fine with an older version. 

```
0.129 install-php-extensions v.2.1.71
0.129 #StandWithUkraine
0.222 ### FIXING LETS ENCRYPT CA CERTIFICATES ###
0.222 - old Alpine Linux detected: we should fix the certificates
0.223 - disabling the DST_Root_CA_X3 certificate
0.224 - refreshing the certificates
0.238 WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
1.473 Updating channel "pecl.php.net"
1.901 Update of Channel "pecl.php.net" succeeded
1.918 fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/aarch64/APKINDEX.tar.gz
2.302 fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/aarch64/APKINDEX.tar.gz
2.685 v3.7.3-184-gffd32bfd09 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
2.685 v3.7.3-194-gcddd1b2302 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
2.685 OK: 8876 distinct packages available
2.833 FAILED TO LIST THE WHOLE PACKAGE LIST FOR
2.833 freetype libjpeg-turbo libpng libxpm libwebp libintl gmp icu-libs libmemcached-libs zstd postgresql-libs libstdc++ ^libssl[0-9]+(\.[0-9]+)*$ tidyhtml-libs libuuid libxslt yaml libzip 
2.833 
2.833 COMMAND OUTPUT:
2.833 ERROR: unsatisfiable constraints:
2.833   ^libssl[0-9]+(\.[0-9]+)*$ (missing):
2.833     required by: world[^libssl[0-9]+(\.[0-9]+)*$]
2.833 
2.833 ERROR: apk failed
```

### Docker image

php:7.0-fpm-alpine 

### Minimal Dockerfile

```Dockerfile
FROM php:7.0-fpm-alpine 

ARG IPE_SOURCE=https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
ADD --chmod=755 $IPE_SOURCE /usr/local/bin/

RUN install-php-extensions @fix_letsencrypt
```

**Comment by mlocati** [comment]
Which Alpine version are you using?

**Comment by shinsenter** [comment]
@mlocati 
It seems like it was built based on Alpine 3.7

<img width="891" alt="Screenshot 2023-12-15 at 17 13 25" src="https://github.com/mlocati/docker-php-extension-installer/assets/2082119/22ca8dab-a9a4-4ad4-bf04-cbc8db037ce3">

**Comment by mlocati** [comment]
We "only" support Alpine 3.9+: see https://github.com/mlocati/docker-php-extension-installer#easy-installation-of-php-extensions-in-official-php-docker-images ("Alpine-based docker images: since Alpine 3.9 (minimum PHP version: 7.1)") and https://github.com/mlocati/docker-php-extension-installer/pull/763

**Comment by shinsenter** [comment]
> We "only" support Alpine 3.9+: see https://github.com/mlocati/docker-php-extension-installer#easy-installation-of-php-extensions-in-official-php-docker-images ("Alpine-based docker images: since Alpine 3.9 (minimum PHP version: 7.1)") and #763

@mlocati 
Oh, I see.
I appreciate you taking the time to respond. Thank you for the information.
