### ISSUE TITLE
add swow extension

### ISSUE THREAD

**Issue by mryfan** [mlocati/docker-php-extension-installer#861]
Hello, can you add swow extension ?   address: [https://github.com/swow/swow](https://github.com/swow/swow)

**Comment by mlocati** [comment]
Is there any reason why that extension is not published on PECL?

It'd be much easier to maintain support for it if it was published on PECL.

**Comment by mryfan** [comment]
Maybe the influence is not enough. haha! Well, that's it for now. I can add it to the dockerfile myself.  thank you
