### ISSUE TITLE
Support for PDO_Informix

### ISSUE THREAD

**Issue by Bamuel** [mlocati/docker-php-extension-installer#878]
To install pdo_informix for php.
You need will need Informix Client SDK installed as a prerequisite

**Comment by mlocati** [comment]
Is the Informix Client SDK available for download? Where?

**Comment by Bamuel** [comment]
https://www-01.ibm.com/marketing/iwm/iwm/web/pickUrxNew.do?source=ifxdl

Its a manual download

**Comment by mlocati** [comment]
If there isn't a way to install the SDK automatically I won't add support for informix.

Why? Because every single PHP extension is tested in GitHub Actions: if the script can't install the prerequisites, then we can't test the PHP extension.

**Comment by Bamuel** [comment]
I wonder if it will let you install the PDO without the informix sdk/drivers?

**Comment by mlocati** [comment]
> I wonder if it will let you install the PDO without the informix sdk/drivers?.

With "PDO" do you mean "pdo_informix"?
If so, the SDK must be installed in order to compile the PHP extension ([see here](https://www.php.net/pdo-informix#ref.pdo-informix.installation)).

> That why you don't need to configure php.

I'm sorry I don't understand...

**Comment by Bamuel** [comment]
Issue closed due to sdk requires manual download.
