### ISSUE TITLE
Saxon extensions doesn't install due to exit command

### ISSUE THREAD

**Issue by leroy0211** [mlocati/docker-php-extension-installer#887]
### Version of install-php-extensions

v.2.2.1

### Error description

The `saxon` library will not install due to an exit [here](https://github.com/mlocati/docker-php-extension-installer/blob/68552b1e16307f0413b623d5a714c7fd66f6d968/install-php-extensions#L3549). 

After continuing the installation by running them myself, it works fine and the extension will be loaded. 

Just remove the `exit` line.

### Docker image

php:8.2-cli

### Minimal Dockerfile

```Dockerfile
FROM php:8.2-cli

ADD     https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/


RUN     chmod +x /usr/local/bin/install-php-extensions \
        && apt update \
        && install-php-extensions saxon
```

Verify with:

```bash
docker run -it --rm [image] php -m 
```

**Comment by mlocati** [comment]
Saxon isn't officially supported.

Until today... see #889
