### ISSUE TITLE
Support ioncube loader on PHP 8.3

### ISSUE THREAD

**Issue by vkoori** [mlocati/docker-php-extension-installer#895]
I want to install ioncube on PHP 8.3 and given following error:

```
438.3 ### INSTALLING REMOTE MODULE ioncube_loader ###
438.3 Downloading ionCube Loader... done.
479.3 cp: cannot stat '/tmp/src/tmp.Mmxi9nI3db/ioncube/ioncube_loader_lin_8.3.so': No such file or directory

```

**Comment by mlocati** [comment]
As you can [read in the list of supported extensions](https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions) PHP 8.3 is not supported for ioncube loader.
The reason? People at ioncube haven't released (yet) a version supporting PHP 8.3.
