### ISSUE TITLE
Missed extension

### ISSUE THREAD

**Issue by ashkraba** [mlocati/docker-php-extension-installer#897]
### Version of install-php-extensions

latest

### Error description

RUN docker-php-source extract  && docker-php-ext-install exif sodium sockets intl opcache xml dom curl zip pgsql mbstring gd pdo_pgsql redis pcntl

error: /usr/src/php/ext/redis does not exist

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dl_test dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell random readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlwriter xsl zend_test zip

### Docker image

php:8.3.3-cli

**Comment by mlocati** [comment]
This project is not about `docker-php-ext-install`
