### ISSUE TITLE
Installing "tideways" fails on alpine x86_64 image

### ISSUE THREAD

**Issue by Gemineye** [mlocati/docker-php-extension-installer#905]
### Version of install-php-extensions

install-php-extensions v.2.2.6

### Error description

It seems that it does not find the "remote module"

/srv/http #  install-php-extensions tideways 
install-php-extensions v.2.2.6
#StandWithUkraine
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
v3.19.1-360-g40349bf1b08 [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]
v3.19.1-361-g303ed052119 [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]
OK: 22993 distinct packages available
### INSTALLING REQUIRED PACKAGES ###
# Packages to be kept after installation: 
# Packages to be used only for installation: m4 libbz2 perl autoconf libmd dpkg pkgconf dpkg-dev libmagic file libstdc++-dev jansson binutils libgomp libatomic gmp isl26 mpfr4 mpc1 gcc musl-dev libc-dev g++ perl-error perl-git git-perl make re2c
(1/28) Installing m4 (1.4.19-r3)
(2/28) Installing libbz2 (1.0.8-r6)
(3/28) Installing perl (5.38.2-r0)
(4/28) Installing autoconf (2.71-r2)
(5/28) Installing jansson (2.14-r4)
(6/28) Installing binutils (2.41-r0)
(7/28) Installing libmd (1.1.0-r0)
(8/28) Installing dpkg (1.22.1-r0)
(9/28) Installing pkgconf (2.1.0-r0)
(10/28) Installing dpkg-dev (1.22.1-r0)
(11/28) Installing libmagic (5.45-r1)
(12/28) Installing file (5.45-r1)
(13/28) Installing libstdc++-dev (13.2.1_git20231014-r0)
(14/28) Installing libgomp (13.2.1_git20231014-r0)
(15/28) Installing libatomic (13.2.1_git20231014-r0)
(16/28) Installing gmp (6.3.0-r0)
(17/28) Installing isl26 (0.26-r1)
(18/28) Installing mpfr4 (4.2.1-r0)
(19/28) Installing mpc1 (1.3.1-r1)
(20/28) Installing gcc (13.2.1_git20231014-r0)
(21/28) Installing musl-dev (1.2.4_git20230717-r4)
(22/28) Installing libc-dev (0.7.2-r5)
(23/28) Installing g++ (13.2.1_git20231014-r0)
(24/28) Installing perl-error (0.17029-r2)
(25/28) Installing perl-git (2.43.0-r0)
(26/28) Installing git-perl (2.43.0-r0)
(27/28) Installing make (4.4.1-r2)
(28/28) Installing re2c (3.1-r0)
Executing busybox-1.36.1-r15.trigger

OK: 379 MiB in 82 packages
### INSTALLING REMOTE MODULE tideways ###
Downloading tideways from 
/usr/local/bin/install-php-extensions: line 2628: 1: parameter not set

### Docker image

php:8.3-fpm-alpine

**Comment by mlocati** [comment]
> wget -O tideways.tar.gz "[https://tideways.s3.amazonaws.com/extension/${TIDEWAYS_EXTENSION_VERSION}/tideways-php-${TIDEWAYS_EXTENSION_VERSION}-alpine-${ARCH}.tar.gz](https://tideways.s3.amazonaws.com/extension/$%7BTIDEWAYS_EXTENSION_VERSION%7D/tideways-php-$%7BTIDEWAYS_EXTENSION_VERSION%7D-alpine-$%7BARCH%7D.tar.gz)"

What's the value of `TIDEWAYS_EXTENSION_VERSION` ? I don't want to keep watching at the tideways website everyday to check if there's a new version.

That's why the script looks for tarball links in the https://tideways.com/profiler/downloads page.

The problem is they changed the name of the alpine tarballs from
`tideways-php-...-alpine.tar.gz`
to
`tideways-php-...-alpine-x86_64.tar.gz`

#907 should fix this issue.

**Comment by Gemineye** [comment]
@mlocati I see, thanks for the quick feedback!
