### ISSUE TITLE
Add wikidiff2

### ISSUE THREAD

**Issue by xtexChooser** [mlocati/docker-php-extension-installer#916]
[Wikidiff2](https://github.com/wikimedia/mediawiki-php-wikidiff2) is a diff engine used by MediaWiki.
It would be great to be able to install the extension with this script.

**Comment by xtexChooser** [comment]
> Do you know if they have plans to publish wikidiff2 to pecl.php.net?

I created a ticket on WMF phabricator: <https://phabricator.wikimedia.org/T363810>

**Comment by mlocati** [comment]
So, it seems wikidiff2 will never be published on pecl...

**Comment by xtexChooser** [comment]
thanks!
