### ISSUE TITLE
Installed PHP extension is not loading in mac M2 chip

### ISSUE THREAD

**Issue by aungmyatmoethegreat** [mlocati/docker-php-extension-installer#924]
### Version of install-php-extensions

v.2.2.14

### Error description

When I check the php modules with `php -m` installed extensions are not even showing.
```


1dff27fb3a07:/var/www/html$ php -m
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
random
readline
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]

1dff27fb3a07:/var/www/html$```

### Docker image

dunglas/frankenphp:lastest-php-8.3-alpine

### Minimal Dockerfile

```Dockerfile
ARG PHP_VERSION=8.3
ARG FRANKENPHP_VERSION=latest
ARG COMPOSER_VERSION=2.7.6

FROM dunglas/frankenphp:${FRANKENPHP_VERSION}-php${PHP_VERSION}-alpine

RUN apk update; \
    apk upgrade; \
    apk add --no-cache  \
    bash \
    curl \
    supervisor \
    nodejs \
    npm  \
    libsodium-dev \
    librdkafka-dev \
    g++ \
    make \
    autoconf \
    && apk del autoconf g++ make  \
    && rm -rf /var/cache/apk/* /tmp/* /var/tmp/* \

RUN install-php-extensions \
        redis \
        rdkafka \
        exif \
        pdo_mysql \
        zip \
        sockets \
        pcntl \
        opcache \
        mongodb \
        gd \
        opcache \
        intl \
        bcmath
```

**Comment by mlocati** [comment]
Have you tried to add

```Dockerfile
RUN php -m
````

At the end of your dockerfile?

**Comment by aungmyatmoethegreat** [comment]
Here is dockerfile that can produce above issue.
```dockerfile
**
WORKDIR ${WORK_DIR}

RUN apk update; \
    apk upgrade; \
    apk add --no-cache  \
    bash \
    curl \
    supervisor \
    nodejs \
    npm  \
    libsodium-dev \
    librdkafka-dev \
    g++ \
    make \
    autoconf \
    && apk del autoconf g++ make  \
    && rm -rf /var/cache/apk/* /tmp/* /var/tmp/* \

RUN install-php-extensions \
        redis \
        rdkafka \
        exif \
        pdo_mysql \
        zip \
        sockets \
        pcntl \
        opcache \
        mongodb \
        gd \
        opcache \
        intl \
        bcmath


RUN install-php-extensions @composer-${COMPOSER_VERSION}


RUN php -m
**
```

**Comment by aungmyatmoethegreat** [comment]
I am facing this issue today. It's working for a long time with mac m2 chip. I am using orbstack and tried to use docker desktop and same issue is still occured. So that I am revered back to the orbstack due to the perf and file system issue of docker desktop.

**Comment by aungmyatmoethegreat** [comment]
docker version
Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        5dc9bcc
 Built:             Tue Mar 19 15:02:31 2024
 OS/Arch:           darwin/arm64
 Context:           orbstack

Server: Docker Engine - Community
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       e63daec
  Built:            Tue Mar 19 15:05:27 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.17
  GitCommit:        3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by aungmyatmoethegreat** [comment]
This can be related with  #896? I am currently using 

```
ARG PHP_VERSION=8.3
ARG FRANKENPHP_VERSION=latest

FROM dunglas/frankenphp:${FRANKENPHP_VERSION}-php${PHP_VERSION}-alpine
```
image and it pull the latest version of this installer.

https://github.com/dunglas/frankenphp/blob/3d065eda3587ceed32a132f11c3d97c7b57c0317/Dockerfile#L24

**Comment by mlocati** [comment]
From your log file it seems that install-php-extensions is not executed: the build process breaks before it's called.

If so, the issue is not related to install-php-extensions

**Comment by aungmyatmoethegreat** [comment]
I found it's compact issue btw. If i disable Rosetta in M2. It's working again.
