### ISSUE TITLE
Error Installing FTP Extension for PHP 8.4: Unrecognized Options `--with-openssl-dir`

### ISSUE THREAD

**Issue by ghostwriter** [mlocati/docker-php-extension-installer#938]
### Version of install-php-extensions

$ install-php-extensions ftp

### Error description

According to the PHP 8.4 [UPGRADING.INTERNALS](https://github.com/php/php-src/blob/93c3ebd209f2111f986a0db4c7b6ddb7284fd71c/UPGRADING.INTERNALS#L112) the `--with-openssl-dir` configure option has been removed.

SSL support in `ext/ftp` and `ext/mysqlnd` is now enabled implicitly when building with `ext/openssl` (`--with-openssl`), or explicitly by using the new configure options `--with-ftp-ssl` and `--with-mysqlnd-ssl`.

### Docker image

php:8.4-rc-cli-alpine

### Minimal Dockerfile

```Dockerfile
FROM php:8.4-rc-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions ftp
```

**Comment by mlocati** [comment]
Superseeded by #940

**Comment by ghostwriter** [comment]
```
if [ $(php -r "echo version_compare(PHP_VERSION, '8.3.999', '>');") = 1 ]; then \
      sed -i 's/--with-openssl-dir=\/usr/--with-ftp-ssl/' /usr/local/bin/install-php-extensions; \
    fi; 
```
