### ISSUE TITLE
Installing `gd` and `vips` extensions causes a build error 

### ISSUE THREAD

**Issue by Cephra** [mlocati/docker-php-extension-installer#954]
### Version of install-php-extensions

latest

### Error description

Hi,

I'm currently trying to build a local dev docker image to run an app locally.

Not sure if this is the right project to put this, if not I'd be happy if you could guide me to the right one.

I get the following errors during the `RUN install-php-extensions ...` build step, it's related to CMake:
**Note**: It's just tail of the log, but basically it's a lot of errors related to libavif

```
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c:519:17: error: 'AOME_THREEFOUR' undeclared here (not in a function); did you mean 'AOME_THREEFIVE'?
42.31   519 |     { { 3, 4 }, AOME_THREEFOUR }, { { 3, 5 }, AOME_THREEFIVE }, { { 4, 5 }, AOME_FOURFIVE },
42.31       |                 ^~~~~~~~~~~~~~
42.31       |                 AOME_THREEFIVE
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c:519:17: error: incompatible types when initializing type 'enum aom_scaling_mode_1d' using type 'const struct aomOptionDef *'
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c: In function 'aomCodecEncodeImage':
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c:580:33: error: 'AOM_USAGE_GOOD_QUALITY' undeclared (first use in this function)
42.31   580 |         unsigned int aomUsage = AOM_USAGE_GOOD_QUALITY;
42.31       |                                 ^~~~~~~~~~~~~~~~~~~~~~
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c:580:33: error: initialization of 'unsigned int' from 'const struct aomScalingModeMapList *' makes integer from pointer without a cast [-Werror=int-conversion]
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c:597:28: error: 'AOM_USAGE_REALTIME' undeclared (first use in this function)
42.31   597 |                 aomUsage = AOM_USAGE_REALTIME;
42.31       |                            ^~~~~~~~~~~~~~~~~~
42.31 /tmp/src/tmp.tA1D6t988N/libavif-1.0.3/src/codec_aom.c:597:26: error: assignment to 'unsigned int' from 'const struct aomScalingModeMapList *' makes integer from pointer without a cast [-Werror=int-conversion]
42.31   597 |                 aomUsage = AOM_USAGE_REALTIME;
42.31       |                          ^
42.31 cc1: all warnings being treated as errors
42.31 make[2]: *** [CMakeFiles/avif.dir/build.make:303: CMakeFiles/avif.dir/src/codec_aom.c.o] Error 1
42.31 make[2]: *** Waiting for unfinished jobs....
42.53 make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/avif_internal.dir/all] Error 2
42.53 make[1]: *** Waiting for unfinished jobs....
42.57 make[1]: *** [CMakeFiles/Makefile2:162: CMakeFiles/avif.dir/all] Error 2
42.57 make: *** [Makefile:149: all] Error 2
------
Dockerfile:9
--------------------
   7 |     ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
   8 |     
   9 | >>> RUN install-php-extensions pdo_mysql mysqli zip xsl gd intl opcache exif ffi vips
  10 |     
  11 |     RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
--------------------
ERROR: failed to solve: process "/bin/sh -c install-php-extensions pdo_mysql mysqli zip xsl gd intl opcache exif ffi vips" did not complete successfully: exit code: 2
```

Removing `vips` from the dependencies will fix it, so it's definetly related to that.

**Also note**: I've tried php versions 8.1, 8.2, and 8.3. They all produce the error.

### Docker image

php:8.3-fpm-bullseye

### Minimal Dockerfile

```Dockerfile
FROM php:8.3-fpm-bullseye

RUN apt-get update && apt-get install -y \
        git \
        unzip 

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions pdo_mysql mysqli zip xsl gd intl opcache exif ffi vips

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
```

**Comment by mlocati** [comment]
> ### Minimal Dockerfile
> 
> ```dockerfile
> FROM php:8.3-fpm-bullseye
> 
> RUN apt-get update && apt-get install -y \
>         git \
>         unzip 
> 
> ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
> 
> RUN install-php-extensions pdo_mysql mysqli zip xsl gd intl opcache exif ffi vips
> 
> RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
> ```

Is this really the *minimal* dockerfile required to replicate the issue?

**Comment by Cephra** [comment]
> > ### Minimal Dockerfile
> > ```dockerfile
> > FROM php:8.3-fpm-bullseye
> > 
> > RUN apt-get update && apt-get install -y \
> >         git \
> >         unzip 
> > 
> > ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
> > 
> > RUN install-php-extensions pdo_mysql mysqli zip xsl gd intl opcache exif ffi vips
> > 
> > RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
> > ```
> 
> Is this really the _minimal_ dockerfile required to replicate the issue?

Hey, firstly, thank you for the timely response and for pointing that out. I've played around with it some more and removed everything but the extension installer and vips. This is what I tried and it works:

```Dockerfile
FROM php:8.3-fpm-bullseye

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions vips
```

However, if I add all the extensions back in, it produces the error again.

Here's the Dockerfile:
```Dockerfile
FROM php:8.3-fpm-bullseye

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions pdo_mysql mysqli zip xsl gd intl opcache exif ffi vips
```

I apologize for the confusion caused by the `apt-get` and composer. This should be now be the most minimal Dockerfile to reproduce the issue and it's just using the extension installer.

**Comment by mlocati** [comment]
Do you experience the issue of you install gd (and only it)?

**Comment by Cephra** [comment]
Nice find! Thanks a lot for your efforts!
