### ISSUE TITLE
Auto discover extensions with composer 

### ISSUE THREAD

**Issue by leroy0211** [mlocati/docker-php-extension-installer#966]
It would be nice to add the possibility to discover the required packages by scanning composer. For example by running `composer check-platform-reqs` you get a list of extensions. 

But also keep the ability to add additional packages as well. 

Or is there already some support for I couldn't find?

**Comment by mlocati** [comment]
You can do something like this:

```sh
install-php-extensions $(composer check-platform-reqs 2>/dev/null | cut -d' ' -f1 | grep -E '^ext-.' | sed -E 's/^ext-//')
```

Explanation:

- with `composer check-platform-reqs 2>/dev/null` we list all the requirements (with `2>/dev/null` we ignore errors eventually printed out by composer). It outputs for example
   ```
   ext-curl             *      success
   ext-redis            *      success
   composer-plugin-api  2.6.0  success
   ```
- with `cut -d' ' -f1` we only take the first "field" (considering fields separated by spaces); this would results for example in
   ```
   ext-curl
   ext-redis
   composer-plugin-api
   ```
- with `grep -E '^ext-.'` we only take the lines that start with `ext-`, for example:
   ```
   ext-curl
   ext-redis
   ```
- with `sed -E 's/^ext-//'` we finally remove the leading `ext-`, for example:
   ```
   curl
   redis
   ```

**Comment by leroy0211** [comment]
Thanks!  I'm using something similar.  I understand this is not something planned.  Was just wondering if this would be something interesting to add.

**Comment by mlocati** [comment]
Nope, I don't plan to add this feature
