### ISSUE TITLE
GraphicsMagick Support

### ISSUE THREAD

**Issue by domhaas** [mlocati/docker-php-extension-installer#97]
Hi there,

any plans to support GraphicsMagick-Extension?
Thank you in advance.

Dom

**Comment by mlocati** [comment]
Done (please remark that the name of the PHP extension is `gmagick`: `GraphicsMagick` is the name of the library used by the `gmagick` PHP extension)

**Comment by domhaas** [comment]
> Done (please remark that the name of the PHP extension is `gmagick`: `GraphicsMagick` is the name of the library used by the `gmagick` PHP extension)

Thank you!
