### ISSUE TITLE
Imagick failing to install: (ERROR: `make -j10 INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuseryraaVX/install-imagick-3.7.0" install' failed)

### ISSUE THREAD

**Issue by jaydrogers** [mlocati/docker-php-extension-installer#979]
### Version of install-php-extensions

v.2.5.0

### Error description

I received a [user report](https://github.com/serversideup/docker-php/discussions/442) from @manusiakemos that Imagick was not installing.

I broke the issue down to have it very minimal and reproducible with the official PHP images and it is still appearing. Please follow my Docker file below to see the following error:

```
22.24 Saved /tmp/pear/temp/imagick/ImagickPixel_arginfo.h
22.25 In /tmp/pear/temp/imagick/Imagick.stub.php:
22.25 Unterminated preprocessor conditions
22.26 make: *** [Makefile:196: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
22.26 ERROR: `make -j10 INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuserAdMKLn/install-imagick-3.7.0" install' failed
```

Before I open this up on Imagick, I wanted to check in to see if it was something to how the installer installs it? Thanks for maintaining this @mlocati! I am beyond grateful for all the work you do for the PHP community ❤️

### Docker image
- php:8.3-cli, php:8.3-cli-alpine

#### Debian
```Dockerfile
FROM php:8.3-cli

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions imagick
```

#### Alpine
```Dockerfile
FROM php:8.3-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions imagick
```

**Comment by jaydrogers** [comment]
I apologize for the confusion...

Today I learned imagick isn't supported in PHP 8.3 https://github.com/Imagick/imagick/issues/640

It's even clearly labeled in the README of this project 😆🤦‍♂️

Sorry to blow up your inbox! Closing this issue 👍

**Comment by fragkp** [comment]
Out "fix" is to use the current master branch version of imagick:
https://github.com/Imagick/imagick/issues/643#issuecomment-2086949716

**Comment by jaydrogers** [comment]
Thanks for posting your solution! 🙌
