### ISSUE TITLE
Unable to find the package.xml file in the directory

### ISSUE THREAD

**Issue by ghostwriter** [mlocati/docker-php-extension-installer#984]
### Version of install-php-extensions

install-php-extensions krakjoe/pcov@7d764c7c2555e8287351961d72be3ebec4d8743f

### Error description

```
1.169 + install-php-extensions krakjoe/pcov@7d764c7c2555e8287351961d72be3ebec4d8743f
1.177 install-php-extensions v.2.5.1
1.178 #StandWithUkraine
1.406 Downloading source from https://codeload.github.com/krakjoe/pcov/tar.gz/7d764c7c2555e8287351961d72be3ebec4d8743f
1.538 Unable to find the package.xml file in the directory
1.538 /tmp/src/tmp.lbphFj/pcov-7d764c7c2555e8287351961d72be3ebec4d8743f
———
```

### Docker image

php:8.4-rc-cli

### Minimal Dockerfile

```Dockerfile
FROM php:8.4-rc-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN set -euxo pipefail && \
    apk update && \
    apk upgrade && \
    install-php-extensions krakjoe/pcov@7d764c7c2555e8287351961d72be3ebec4d8743f
```

**Comment by mlocati** [comment]
In order to install a package, pecl (user by installl-php-extension) requires that packages provide a file named package.xml.

And (as described by the error message) there's no package.xml file in the root directory of https://github.com/krakjoe/pcov/tree/7d764c7c2555e8287351961d72be3ebec4d8743f

**Comment by ghostwriter** [comment]
do we need to parse a package.xml (or package2.xml) file to extract the module name and version, is that required to install an extension or can we bypass that?

**Comment by mlocati** [comment]
Since pecl requires that package.xml file, we can't bypass its existence.

**Comment by ghostwriter** [comment]
wait i'm confused. https://pecl.php.net/package/pcov 

why is it required to install using extension-installer but also not required by pecl?

**Comment by mlocati** [comment]
I checked the code: package.xml is required by `installl-php-extension` in order to know the name and the version of the package.
