### ISSUE TITLE
Cleanup does not leave already installed packages

### ISSUE THREAD

**Issue by gisostallenberg** [mlocati/docker-php-extension-installer#99]
As far as I can see cleanup (run by default since f164c691cdafd0b10242a4bb251ed6b96e59f2d8) does not leave already installed packages, but please correct me if I'm wrong.
This means that the following will not work
```Dockerfile
RUN apt-get install -y --no-install-recommends \
    a-package-i-need-later-on-and-is-needed-by-an-extension
RUN install-php-extensions an-extension
RUN something-that-needs-a-package-i-need-later-on-and-is-needed-by-an-extension
```

Shouldn't just the delta of what was on the system and what is later on on the system be cleaned?

**Comment by mlocati** [comment]
I think that the cause of this issue is [this line](https://github.com/mlocati/docker-php-extension-installer/blob/572050a69b646d596b93b421abdff4426a4a679b/install-php-extensions#L638). Could you try to remove it and see if it fixes your issue?

**Comment by mlocati** [comment]
@gisostallenberg any feedback?

**Comment by gisostallenberg** [comment]
I'm running the builds at the moment, I'll give you feedback within the next hour.

**Comment by gisostallenberg** [comment]
Sorry for my late response, this does not seem to fix the issue.

**Comment by mlocati** [comment]
It's really strange. Could you post the output of the `install-php-extensions` command?

**Comment by gisostallenberg** [comment]
It is rather large, so I put it in pastebin: https://pastebin.com/LxhKRELJ
That is the most recent version of the command with only the mentioned line removed

**Comment by mlocati** [comment]
And what's the package that you had installed before running `install-php-extensions` that's no more there after running it (that is, the `a-package-i-need-later-on-and-is-needed-by-an-extension` [you mentioned above](https://github.com/mlocati/docker-php-extension-installer/issues/99#issue-552318261)?

**Comment by mlocati** [comment]
> It is rather large, so I put it in pastebin

PS: you can add attachments to messages simply by dropping files over the github area where you are writing a message

**Comment by gisostallenberg** [comment]
libssl-dev is missing

**Comment by gisostallenberg** [comment]
> > It is rather large, so I put it in pastebin
> 
> PS: you can add attachments to messages simply by dropping files over the github area where you are writing a message

Ah, of course, I knew, but just did not think of putting it in a file

**Comment by gisostallenberg** [comment]
For future reference [output.log](https://github.com/mlocati/docker-php-extension-installer/files/4098453/output.log)

**Comment by mlocati** [comment]
Which PHP docker image are you using?

**Comment by mlocati** [comment]
The problem with `libssl-dev` is that it can't be installed together with `libssl1.0-dev`.

`libssl1.0-dev` is required to compile the `imap`/`mongo`/`mongodb`/`zip` PHP extensions, so the script installs it.
Since the two versions are not compatible, `apt` uninstalls `libssl-dev` (see the `Removing libssl-dev:amd64 (1.1.0l-1~deb9u1) ...` line in your log).

Since `libssl1.0-dev` is required only to compile the extensions, the script uninstalls it when it's done, and you can install `libssl-dev` *after* running `install-php-extensions`. Sorry, but I don't think it's something that can be fixed.

**Comment by gisostallenberg** [comment]
IMO after installing the extensions the system should be restored to the state before.
I think this can be achieved by saving a list of all installed packages before installing the packages required to compile the extensions and then restoring that list after purging all packages just installed.

I'm not an expert on this, but the list can be retrieved using 
```bash
dpkg --get-selections | grep -v deinstall | awk '{ print $1 }'
```

**Comment by mlocati** [comment]
Done in #101

**Comment by gisostallenberg** [comment]
@mlocati Thank you so much
