### ISSUE TITLE
Can't install pdo_sqlsrv for php:8.2-fpm-alpine3.20

### ISSUE THREAD

**Issue by b1ek** [mlocati/docker-php-extension-installer#998]
### Version of install-php-extensions

it is on latest

### Error description

```
### INSTALLING REMOTE MODULE pdo_sqlsrv ###
Installing the Microsoft SQL Server ODBC Driver
curl: (6) Could not resolve host: download.microsoft.com
The command '/bin/sh -c install-php-extensions pdo_sqlsrv' returned a non-zero code: 6
```

### Docker image

php:8.2-fpm-alpine3.20

### Minimal Dockerfile

```Dockerfile
FROM php:8.2-fpm-alpine3.20

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/install-php-extensions
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN install-php-extensions gd imagick openssl pdo_sqlsrv bcmath ctype curl dom fileinfo json mbstring pdo tokenizer xml xmlwriter session imagick
```

**Comment by mlocati** [comment]
> Could not resolve host: download.microsoft.com

Please check that your container doesn't have network issues.

**Comment by b1ek** [comment]
nope. `curl https://download.microsoft.com` connects without issues

**Comment by mlocati** [comment]
The script users curl to download a file from the download.microsoft.com website:

https://github.com/mlocati/docker-php-extension-installer/blob/master/install-php-extensions#L2144
