### ISSUE TITLE
Smaller print when installing composer?

### ISSUE THREAD

**Issue by Nayte91** [mlocati/docker-php-extension-installer#999]
Hello,

I just found this article: https://blog.codito.dev/2022/11/composer-binary-only-docker-images/

And I wonder how do you install composer when we ask for it with your script; I'll check later by browsing and understanding your code, but until, I put the article here in an issue, hoping it can be useful,

Best regards

**Comment by mlocati** [comment]
Here's how the script installs composer:

https://github.com/mlocati/docker-php-extension-installer/blob/2.6.1/install-php-extensions#L2470

**Comment by mlocati** [comment]
Closing because it's a discussion and not an issue.
